### ISSUE TITLE
Upload support in the worker

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#100]
We need to implement support for uploading images, according to the information given in the Target struct. This proposal should be considered complete when the features exposed in the UI by https://github.com/weldr/cockpit-composer/pull/767 are implemented. A nice-to-have would be to support all the features the weldr API supports.

The suggestion is to use Mantle for the initial implementation. Though in the future, or if it makes more sense, we may want to use the SDKs provided by the cloud providers directly, as Mantle is anyway just a think wrapper around these.

Proposed proritization:
 - [x] aws
 - [x] azure
 - [ ] vsphere
 - [ ] openstack
 - [ ] other supported formats (if any)

**Comment by msehnout** [comment]
@teg : just to make sure, your priority is AWS and mine is Azure, right?

**Comment by larskarlitski** [comment]
We're postponing the other output formats. Let's revisit this later.
