### ISSUE TITLE
Does it support UEFI for RHEL-8.3?

### ISSUE THREAD

**Issue by yuxisun1217** [osbuild/osbuild-composer#1008]
Hi there,
Does the osbuild-composer support building UEFI image of RHEL-8.3? I installed the image builder in a UEFI KVM virtual machine and built a vhd image. But it cannot boot up in UEFI firmware.

Version:
osbuild-composer                                            x86_64                                     20.1-1.el8

Thanks!

**Comment by yuxisun1217** [comment]
@gicmo , got it. Thank you so much!

**Comment by teg** [comment]
Correct, this is on our roadmap, and it would be a simple addition, but we do not support this for 8.3.

**Comment by ondrejbudai** [comment]
We do support UEFI for RHEL 8.4, AFAIK there are no plans to backport this feature to 8.3.
