### ISSUE TITLE
Upload support in the weldr API

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#101]
We need to reach parity with lorax-composer's upload support. This proposal extends the current routes to support uploads (including authentication tokens), and passes them (with the compose) to the worker as Target structs. Implementing uploading in the worker is outside the scope of this proposal.

The proposal should be considered complete when the features used by https://github.com/weldr/cockpit-composer/pull/767 are implemented and tested.

An additional nice-to-have would be a full implementation and test of all the features that lorax-composer supports.

Suggested prioritization, if relevant:

- [ ] aws
- [ ] azure
- [ ] vsphere
- [ ] openstack
- [ ] other supported formats (if any)

**Comment by jkozol** [comment]
The following routes need to be updated for uploading through cockpit-composer:

```
POST /compose
GET /compose/info/<compose_uuid>
GET /compose/status/<uuids>
```

The following routes should be updated:
```
GET /compose/failed
GET /compose/finished
GET /compose/queue
````

The following routes should be implemented:
```
POST /compose/uploads/schedule/<compose_uuid>
POST /upload/reset/<upload_uuid
GET /upload/info/<upload_uuid>
GET /upload/log/<upload_uuid>
DELETE /upload/delete/<upload_uuid>
DELETE /upload/cancel/<upload_uuid>
```

The following routes would be nice to have implemented for parity:
```
POST /upload/providers/save
GET /upload/providers
DELETE /upload/providers/delete/<provider_name>/<profile>
```
