### ISSUE TITLE
Add RHEL 8.4 support

### ISSUE THREAD

**Issue by jkozol** [osbuild/osbuild-composer#1013]
osbuild-composer needs to support producing rhel 8.4 images. This work will be based off of the current support for rhel 8.3 images and off of the official 8.4 nightlies found here: http://download-ipv4.eng.brq.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/iso/

**Comment by jkozol** [comment]
There are numerous differences between the official rhel 84 qcow2 and our image based off of the rhel 83 image. They are as follows:

An additional "rescue" bootmenu entry.
```
    {
      "grub_arg": "--unrestricted",
      "grub_class": "kernel",
      "grub_users": "$grub_users",
      "id": "rhel-20200929154808-0-rescue-724317cf905047a2b52844ebed98adf9",
      "initrd": "/initramfs-0-rescue-724317cf905047a2b52844ebed98adf9.img",
      "linux": "/vmlinuz-0-rescue-724317cf905047a2b52844ebed98adf9",
      "options": "$kernelopts",
      "title": "Red Hat Enterprise Linux (0-rescue-724317cf905047a2b52844ebed98adf9) 8.4 (Ootpa)",
      "version": "0-rescue-724317cf905047a2b52844ebed98adf9"
    },
```

The firewall is enabled for cockpit.
```
  "firewall-enabled": ["ssh", "dhcpv6-client", "cockpit"],
```

There is an additional efi partition.
```
    [
      "UUID=7B77-95E7",
      "/boot/efi",
      "vfat",
      "defaults,uid=0,gid=0,umask=077,shortname=winnt",
      "0",
      "2"
    ],
```

There is a default hostname:
```
  "hostname": "localhost.localdomain",
```

The official image's default timezone is New_York:
```
  "timezone": "New_York"
```

Our osrelease is still for rhel 8.3. This is the official one:
```
  "os-release": {
    "ANSI_COLOR": "0;31",
    "BUG_REPORT_URL": "https://bugzilla.redhat.com/",
    "CPE_NAME": "cpe:/o:redhat:enterprise_linux:8.4:beta",
    "HOME_URL": "https://www.redhat.com/",
    "ID": "rhel",
    "ID_LIKE": "fedora",
    "NAME": "Red Hat Enterprise Linux",
    "PLATFORM_ID": "platform:el8",
    "PRETTY_NAME": "Red Hat Enterprise Linux 8.4 Beta (Ootpa)",
    "REDHAT_BUGZILLA_PRODUCT": "Red Hat Enterprise Linux 8",
    "REDHAT_BUGZILLA_PRODUCT_VERSION": "8.4",
    "REDHAT_SUPPORT_PRODUCT": "Red Hat Enterprise Linux",
    "REDHAT_SUPPORT_PRODUCT_VERSION": "8.4 Beta",
    "VERSION": "8.4 (Ootpa)",
    "VERSION_ID": "8.4"
  },
```

The official partition table is now gpt:
```
  "partition-table": "gpt",
  "partition-table-id": "D209C89E-EA5E-4FBD-B161-B461CCE297E0",
  "partitions": [
    {
      "bootable": false,
      "fstype": null,
      "label": null,
      "partuuid": "D3F22FC4-565E-4E9D-85E9-7676495135CB",
      "size": 1048576,
      "start": 1048576,
      "type": "21686148-6449-6E6F-744E-656564454649",
      "uuid": null
    },
    {
      "bootable": false,
      "fstype": "vfat",
      "label": null,
      "partuuid": "3D69D4E9-64FD-488A-BE74-B2B126210F2D",
      "size": 104857600,
      "start": 2097152,
      "type": "C12A7328-F81F-11D2-BA4B-00A0C93EC93B",
      "uuid": "7B77-95E7"
    },
    {
      "bootable": false,
      "fstype": "xfs",
      "label": "root",
      "partuuid": "65F646F8-9CD6-4595-A891-1E23D4694EF7",
      "size": 10629414912,
      "start": 106954752,
      "type": "0FC63DAF-8483-4772-8E79-3D69D8477DE4",
      "uuid": "efe8afea-c0a8-45dc-8e6e-499279f6fa5d"
    }
  ],
```

There are package version differences and numerous packages added and removed. Some of the packages added/removed are probably due to the numerous version differences.
Packages added to the official image:
```
    "authselect-compat-1.2.1-2.el8.x86_64", 
    "dbxtool-8-5.el8.x86_64", 
    "dosfstools-4.1-6.el8.x86_64", 
    "dracut-config-rescue-049-95.git20200804.el8.x86_64", 
    "efi-filesystem-3-2.el8.noarch", 
    "efivar-37-4.el8.x86_64", 
    "efivar-libs-37-4.el8.x86_64", 
    "grub2-efi-x64-2.02-90.el8.x86_64", 
    "mokutil-0.3.0-10.el8.x86_64", 
    "oddjob-0.34.5-2.el8.x86_64", 
    "oddjob-mkhomedir-0.34.5-2.el8.x86_64", 
    "psmisc-23.1-5.el8.x86_64", 
    "shim-x64-15-16.el8.x86_64", 
    "timedatex-0.5-3.el8.x86_64", 
```

Packages removed from the official image:
```
    "gpg-pubkey-d4082792-5b32db75", 
    "gpg-pubkey-fd431d51-4ae0493b", 
    "libgudev-232-4.el8.x86_64", 
    "linux-firmware-20200619-99.git3890db36.el8.noarch", 
    "python3-dnf-plugin-spacewalk-2.8.5-11.module+el8.1.0+3455+3ddf2832.noarch", 
    "python3-hwdata-2.3.6-3.el8.noarch", 
    "python3-netifaces-0.10.6-4.el8.x86_64", 
    "python3-newt-0.52.20-11.el8.x86_64", 
    "python3-pyOpenSSL-18.0.0-1.el8.noarch", 
    "python3-rhn-check-2.8.16-13.module+el8.1.0+3455+3ddf2832.x86_64", 
    "python3-rhn-client-tools-2.8.16-13.module+el8.1.0+3455+3ddf2832.x86_64", 
    "python3-rhn-setup-2.8.16-13.module+el8.1.0+3455+3ddf2832.x86_64", 
    "python3-rhnlib-2.8.6-8.module+el8.1.0+3455+3ddf2832.noarch", 
    "rhn-check-2.8.16-13.module+el8.1.0+3455+3ddf2832.x86_64", 
    "rhn-setup-2.8.16-13.module+el8.1.0+3455+3ddf2832.x86_64", 
    "rhnlib-2.8.6-8.module+el8.1.0+3455+3ddf2832.noarch", 
    "rhnsd-5.0.35-3.module+el8.1.0+3455+3ddf2832.x86_64", 
```

**Comment by larskarlitski** [comment]
Nice write up, thanks! It might make sense to compare against image-info from 8.3, because some of those we left out intentionally.

>  An additional "rescue" bootmenu entry.

I think this was the case in the 8.3 image as well. We left it out because it didn't work.

> There is an additional efi partition.

Summoning @gicmo for this one.

> The official partition table is now gpt:

This might be due to the image being supporting both GPT and MBR partitions. It's crazy, but osbuild supports it since https://github.com/osbuild/osbuild/pull/203

> Packages added to the official image:

To get the "official" package list more easily, check the [kickstarts](http://git.app.eng.bos.redhat.com/git/spin-kickstarts.git/tree/rhel8) (Red Hat internal link).

**Comment by jkozol** [comment]
@larskarlitski Thanks for the additional info and links. 

I compared the differences between the official rhel 8.3 and 8.4 images and I diffed the rhel-8.3 kickstarts with the 8.4 ones. There are no significant changes between 8.3 and 8.4. Do we still want to keep the differences I mentioned above? I would prefer to eliminate as many of them as possible. Excluding some of the minor package changes and the rescue entries, I believe I can fix the rest.

@gicmo @teg do you have any thoughts on what is feasible to change?

**Comment by larskarlitski** [comment]
> I compared the differences between the official rhel 8.3 and 8.4 images and I diffed the rhel-8.3 kickstarts with the 8.4 ones. There are no significant changes between 8.3 and 8.4. Do we still want to keep the differences I mentioned above? I would prefer to eliminate as many of them as possible. Excluding some of the minor package changes and the rescue entries, I believe I can fix the rest.

Good to know! I think for some of these, it makes sense to keep. For example, setting the hostname to `localhost.localdomain` is done by systemd automatically when none is set. There's no need for the image to contain it.

**Comment by teg** [comment]
I'm very late to the party here, and maybe this was already addressed in the PR, just to say: I agree to minimize the differences, except in the cases we are convinced the official ones are "wrong" (rescue kernels do not work I believe, hostname is not necessary, timezone I think makes no sense). Great write-up!
