### ISSUE TITLE
Many tests fail because of faulty mirrors

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#1031]
osbuild-composer's tests are downloading a lot of packages from a myriad of mirrors. Some of those are flaky, or not in sync, or rate-limit us.

Thist most often manifests itself like this in osbuild's output:
```
RuntimeError: org.osbuild.files: curl: error downloading {'url': 'https://mirrors.rit.edu/fedora/fedora/linux/releases/32/Everything/x86_64/os/Packages/g/geolite2-city-20191217-2.fc32.noarch.rpm'}: error code 28
```

**Comment by atodorov** [comment]
> osbuild-composer's tests are downloading a lot of packages from a myriad of mirrors. Some of those are flaky, or not in sync, or rate-limit us.

@larskarlitski I am curious about 2 items:
1) If a download fails doesn't dnf go to the next one, then next one, etc ? Is this causing real issues and failures to download packages or just annoying error messages in the logs ? 

2) Isn't there a Fedora mirror in AWS ? There should be. Quick search found the following resources, all of them a bit unclear:
https://fedoraproject.org/wiki/EC2_Mirrors
https://fedoraproject.org/wiki/Archive:Infrastructure/Mirroring/Amazon - contains a list of regional mirror URLs
https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/mirrormanager-S3-EC2-netblocks.html

but it looks like there should be mirroring infrastructure inside AWS and dnf is supposed to be using it.

**Comment by larskarlitski** [comment]
> @larskarlitski I am curious about 2 items:
> 
>     1. If a download fails doesn't dnf go to the next one, then next one, etc ? Is this causing real issues and failures to download packages or just annoying error messages in the logs ?

It does, but osbuild's file source doesn't implement the same logic. Mostly because we didn't know that dnf tries fetching files from mirrors that are *not* the one it downloaded the metadata from. This could be added, of course, but is a bit tricky.

>     2. Isn't there a Fedora mirror in AWS ? There should be. Quick search found the following resources, all of them a bit unclear:
>        https://fedoraproject.org/wiki/EC2_Mirrors
>        https://fedoraproject.org/wiki/Archive:Infrastructure/Mirroring/Amazon - contains a list of regional mirror URLs
>        https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/mirrormanager-S3-EC2-netblocks.html
> 
> 
> but it looks like there should be mirroring infrastructure inside AWS and dnf is supposed to be using it.

@dvdhrm is mirroring repositories in AWS for us: https://www.osbuild.org/rpmrepo/. This greatly alleviated the issue where we've already made the switch.

**Comment by atodorov** [comment]
@larskarlitski I believe this issue has been resolved meanwhile. Please close if you think so or provide some more up-to-date information.

**Comment by larskarlitski** [comment]
Yeah let's close this, as I don't think this has been as much of a problem as of late.

@ondrejbudai  feel free to reopen if my understanding of this is off.
