### ISSUE TITLE
Unhandled exception in dnf-json

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#1047]
https://github.com/osbuild/osbuild-composer/blob/931bd8be5723537b10cbbfdb89040b9f7418faf7/dnf-json#L31

It is far too easy to trigger this `assert` as a user. All one needs to do it to create a dummy `source` using `composer-cli` which will not contain any repo URL. We should catch the error *somewhere* and report it *somehow*.

Some ideas in no particular order:
 * handle the exception in `dnf-json` and return useful error message
 * disallow creation of such sources
 * verify sources in weldr api or rpmmd before passing them to `dnf-json`

**Comment by msehnout** [comment]
Reproducer:
```
~ $ cat /tmp/a
id="a"
name="a"
ignoressl=true
type="yum-baseurl"
~ $ sudo composer-cli sources add /tmp/a
~ $ sudo composer-cli blueprints depsolve rpmci-runner
2020-10-21 09:47:18,818: rpmci-runner: unexpected end of JSON input
blueprint: rpmci-runner v0.0.0
~ [1] $ sudo journalctl -xe --unit osbuild-composer | tail -20
Oct 21 09:45:37 localhost.localdomain osbuild-composer[10079]:     base = create_base(
Oct 21 09:45:37 localhost.localdomain osbuild-composer[10079]:   File "/usr/libexec/osbuild-composer/dnf-json", line 71, in create_base
Oct 21 09:45:37 localhost.localdomain osbuild-composer[10079]:     base.repos.add(dnfrepo(repo, base.conf))
Oct 21 09:45:37 localhost.localdomain osbuild-composer[10079]:   File "/usr/libexec/osbuild-composer/dnf-json", line 31, in dnfrepo
Oct 21 09:45:37 localhost.localdomain osbuild-composer[10079]:     assert False
Oct 21 09:45:37 localhost.localdomain osbuild-composer[10079]: AssertionError
Oct 21 09:46:19 localhost.localdomain osbuild-composer[8895]: 2020/10/21 09:46:19 GET /api/v1/blueprints/info/rmpci-runner
Oct 21 09:46:31 localhost.localdomain osbuild-composer[8895]: 2020/10/21 09:46:31 GET /api/v1/projects/source/list
Oct 21 09:46:34 localhost.localdomain osbuild-composer[8895]: 2020/10/21 09:46:34 DELETE /api/v1/projects/source/delete/a
Oct 21 09:47:01 localhost.localdomain osbuild-composer[8895]: 2020/10/21 09:47:01 POST /api/v1/projects/source/new
Oct 21 09:47:18 localhost.localdomain osbuild-composer[8895]: 2020/10/21 09:47:18 GET /api/v1/blueprints/depsolve/rpmci-runner
Oct 21 09:47:18 localhost.localdomain python3[10509]: detected unhandled Python exception in '/usr/libexec/osbuild-composer/dnf-json'
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]: Traceback (most recent call last):
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]:   File "/usr/libexec/osbuild-composer/dnf-json", line 120, in <module>
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]:     base = create_base(
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]:   File "/usr/libexec/osbuild-composer/dnf-json", line 71, in create_base
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]:     base.repos.add(dnfrepo(repo, base.conf))
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]:   File "/usr/libexec/osbuild-composer/dnf-json", line 31, in dnfrepo
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]:     assert False
Oct 21 09:47:18 localhost.localdomain osbuild-composer[10509]: AssertionError
```

**Comment by msehnout** [comment]
Isn't this already fixed by https://github.com/osbuild/osbuild-composer/pull/968 ? :man_facepalming:

**Comment by msehnout** [comment]
> Isn't this already fixed by #968 ? man_facepalming

It is ...

but we can still handle the `assert False` in `dnf-json`

**Comment by atodorov** [comment]
@msehnout IMO a `raise RuntimeError()` with a clearly written message would do the job here for dnf-json.

OTOH `sources add` shouldn't have allowed this to be added in the first place. Isn't this what #968 was supposed to do?

**Comment by msehnout** [comment]
> @msehnout IMO a `raise RuntimeError()` with a clearly written message would do the job here for dnf-json.
> 

@larskarlitski proposed `raise ValueError`. These are the descriptions for both:
https://docs.python.org/3/library/exceptions.html#ValueError
https://docs.python.org/3/library/exceptions.html#RuntimeError
I think both apply to this scenario. What to you think @ondrejbudai , @teg , and others?

> OTOH `sources add` shouldn't have allowed this to be added in the first place. Isn't this what #968 was supposed to do?

Yes, it is already fixed. I wasn't aware of the fact that I'm running an old version of osbuild-composer.

**Comment by ondrejbudai** [comment]
`KeyError` maybe?

https://docs.python.org/3/library/exceptions.html#KeyError

Honestly, don't spend much time on this one. :upside_down_face:

**Comment by msehnout** [comment]
This doesn't seem to be a huge issue. I'm closing this for now.
