### ISSUE TITLE
Investigate enabling gosec

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#1060]
@major proposed enabling [gosec](https://securego.io) for [image-builder](https://github.com/osbuild/image-builder) in https://github.com/osbuild/image-builder/pull/54.

Does it make sense to enable this on osbuild-composer as well? More static checks sound like a good idea to me.

**Comment by ondrejbudai** [comment]
Done 3 years ago! https://github.com/osbuild/osbuild-composer/commit/5a1460a6d1e350b82bdb763f4e51301857475934

**Comment by major** [comment]
@ondrejbudai ![https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdDU4Z3VldWM0N3ZjczlnZGViMDRjOXdoYW9hbjVhejJubmxta2YwNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Quh1CAKOTRCl9VVU3f/giphy.gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdDU4Z3VldWM0N3ZjczlnZGViMDRjOXdoYW9hbjVhejJubmxta2YwNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Quh1CAKOTRCl9VVU3f/giphy.gif)
