### ISSUE TITLE
rhel-84 builds fail on non-x86 arches

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1103]
```
GenericError: Failed to create the compose request: {"message":"Failed to depsolve base base packages for qcow2/s390x/rhel-84: DNF error occured: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\nmissing packages: efi-filesystem, efivar, efivar-libs, grub2-efi-x64, shim-x64"}
```

![image](https://user-images.githubusercontent.com/119861/100141982-7ac91200-2e93-11eb-85f7-1489f7ecb0fd.png)

**Comment by gicmo** [comment]
Yeah, S390x does not use `UEFI` but `zipl`.

**Comment by gicmo** [comment]
I think UEFI packages are pulled for all arches if the image is qcow2, which should also break ppc64le.
 https://github.com/osbuild/osbuild-composer/blob/8e86d9dcae30ee87730beecd79dcd66d2acf8f6d/internal/distro/rhel84/distro.go#L823

**Comment by teg** [comment]
This works ok for [RHEL-8.3 builds](https://brewweb.stage.engineering.redhat.com/brew/taskinfo?taskID=42116445), but fails for [RHEL-8.4](https://brewweb.stage.engineering.redhat.com/brew/taskinfo?taskID=42120676).

It seems like we added some arch-specific packages to arches that should not have them. Should be easy to fix *fingers crossed*.

**Comment by ondrejbudai** [comment]
I got this error when building aarch64:

```
GenericError: Failed to create the compose request: {"message":"Failed to depsolve base base packages for qcow2/aarch64/rhel-84: DNF error occured: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\nmissing packages: grub2-efi-x64, shim-x64"}
```

**Comment by ondrejbudai** [comment]
And ppc64le:

```
{"message":"Failed to depsolve base base packages for qcow2/ppc64le/rhel-84: DNF error occured: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\nmissing packages: efi-filesystem, efivar, efivar-libs, grub2-efi-x64, shim-x64"}
```

**Comment by larskarlitski** [comment]
Thanks @ondrejbudai for reporting this and pasting the error for all architectures!

Turns out, the x86_64 EFI-related packages slipped into the generic package list. Since we're only testing on x86_64, CI didn't catch it. I've filed #1104 to fix it.
