### ISSUE TITLE
osbuild-composer is underdocumented

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#1107]
There are few issues with our official documentation:

 * Documentation for composer-cli still refers to Weldr:
https://www.osbuild.org/documentation/

 * Documentation for blueprints is missing:
Probably the TDB part here: https://www.osbuild.org/documentation/

 * Documentation for APIs is missing

As we have become more than just a lorax-composer replacement, I think it would make sense to migrate all documentation to osbuild.org.

**Comment by teg** [comment]
Totally agree.

**Comment by msehnout** [comment]
New documentation lives in https://www.osbuild.org/guides/. We haven't yet agreed on any API docs unfortunately.
