### ISSUE TITLE
KojiAPI: Server panic if job ID matches InitJob

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#1154]
This is a pretty minor and unrealistic edge case.

The Koji API handlers require the ID of a Finalize Job because that's the job ID that's returned to the caller.  If the ID of an Init Job is submitted, the `JobStatus()` call to the worker succeeds (it's a valid Job ID) but the dependencies are empty.  The server assumes non-zero dependencies and tries to index the `deps` (see below).

https://github.com/osbuild/osbuild-composer/blob/d9f09c66f2ea4fd8ea15ca8a267e94fe988c0310/internal/kojiapi/server.go#L305
https://github.com/osbuild/osbuild-composer/blob/d9f09c66f2ea4fd8ea15ca8a267e94fe988c0310/internal/kojiapi/server.go#L358

Realistically, this can only happen if a caller manages to _guess_ the UUID of an Init Job, but perhaps we should detect this and return a 404 anyway.

**Comment by larskarlitski** [comment]
Agreed. It should probably verify the job type, no?

**Comment by achilleas-k** [comment]
Ideally yes.  Though it's the same story with the manifest.  We'll need a way to get the job type other than `RequestJob()` (which does a `Dequeue()`).

`JobStatus()` would be a candidate, but that's the function we agreed returns too many values already.

**Comment by larskarlitski** [comment]
Right. Probably we want to just go all the way and allow getting all information about a job back out of `jobqueue.JobQueue` that was put into it with `Enqueue()`. Something like:

```go
Job(id uuid.UUID) (jobType string, args json.RawMessage, dependencies []uuid.UUID, err error)
```

Or as separate calls, as you (@achilleas-k) already started in #1155. That might be less efficient, because it requires multiple lookups:

```go
JobType(id uuid.UUID) (string, error)
JobArgs(id uuid.UUID) (args json.RawMessage, error)
JobDependencies(id uuid.UUID) ([]uuid.UUID, error)
```

> I got a bit lost. Doesn't make sense for `JobStatus()` since the `jobqueue` knows nothing of the type (or any other part of the job struct).

Hm, I don't understand. `jobqueue` does know about the type.

**Comment by achilleas-k** [comment]
> Right. Probably we want to just go all the way and allow getting all information about a job back out of `jobqueue.JobQueue` that was put into it with `Enqueue()`. Something like:
> 
> ```go
> Job(id uuid.UUID) (jobType string, args json.RawMessage, dependencies []uuid.UUID, err error)
> ```

I'd be in favour of this.  It's basically the inverse function (signature-wise) of `Enqueue()` so matching the return of one to the arguments of the other feels natural.

> > I got a bit lost. Doesn't make sense for `JobStatus()` since the `jobqueue` knows nothing of the type (or any other part of the job struct).
> 
> Hm, I don't understand. `jobqueue` does know about the type.

Right.  Double-confusion.  Unscratch it.

**Comment by achilleas-k** [comment]
> > > I got a bit lost. Doesn't make sense for `JobStatus()` since the `jobqueue` knows nothing of the type (or any other part of the job struct).
> > 
> > 
> > Hm, I don't understand. `jobqueue` does know about the type.
> 
> Right. Double-confusion. Unscratch it.

I think what I meant originally was a (confusing) conflation of a couple of things:
1. `JobQueue` doesn't understand the type: As far as the `JobQueue` interface is concerned, `jobtype` is a string.  The mapping of job types to job structs (Init, Finalize, Build) happens on the Koji API level.
2. The `job` struct is part of the `fsJobQueue` implementation.  This isn't interesting or relevant though; the jobtype is still a property that should be stored and retrieved through all implementations of the `JobQueue` interface.

The first point is relevant here: The type validation can't happen in the job queue since it doesn't understand the type mapping, but we need to add some way of getting the type back out, which is what we agreed on in the previous message (the `Job()` method).

None of this is new information, I'm just explaining the information separation for posterity.

I have an implementation of the job type checking ready.  It follows #996, but I don't know if it should follow the PR or if we should close it and replace it with this one.  On the one hand the new PR addresses a different issue, on the other hand it rewrites a big part of it.

**Comment by larskarlitski** [comment]
Ah, thanks for unconfusing it all :)

> I have an implementation of the job type checking ready. It follows #996, but I don't know if it should follow the PR or if we should close it and replace it with this one. On the one hand the new PR addresses a different issue, on the other hand it rewrites a big part of it.

I don't have a preference either way, honestly.

**Comment by achilleas-k** [comment]
Let's keep them separate then.  Keep #996 as is and I'll open a followup PR.  Might add some more tests for the new fail conditions and there are some things I'd like to discuss on the PR when it's open, so best not to mix them up.
