### ISSUE TITLE
failed to parse error response: json: cannot unmarshal number into Go value of type api.Error

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1157]
```
failed to parse error response: json: cannot unmarshal number into Go value of type api.Error
```

This error showed in the log of a remote worker.
NVRA: `osbuild-composer-worker-26-1.el8eng.aarch64`

**Comment by larskarlitski** [comment]
Running against `osbuild-composer-26-1.20210106gitda6f5ba.el8` (please correct me if I'm wrong, @ondrejbudai).

**Comment by ondrejbudai** [comment]
I started `osbuild-remote-worker.service` against port 443 instead of 8700. Sigh...
