### ISSUE TITLE
Fedora-IOT image type isn't supported on aarch64

### ISSUE THREAD

**Issue by pciavald** [osbuild/osbuild-composer#1174]
### Description of problem

In image-builder's cockpit interface, on the create image modal, type dropdown does not show "Fedora IoT Commit (.tar)" on aarch64 images.

### Version or commit hash (if applicable)

Fails on [fedora33-server-aarch64](https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Server/aarch64/images/) and [fedora33-workstation-aarch64](https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/aarch64/images/).

Works on [fedora33-workstation x86 iso install](https://getfedora.org/en/workstation/download/).

### How often reproducible

Always

### Steps to Reproduce

1. start the image in virt-manager on a aarch64 host
2. update the system and [install components as per this guide](https://www.osbuild.org/news/2020-06-01-how-to-ostree-anaconda.html)
3. go to the cockpit interface, create a blueprint, click create image, select the type dropdown

### Actual results

"Fedora IoT Commit (.tar)" is not shown

### Expected results

"Fedora IoT Commit (.tar)" should be shown

### Additional info

after checking the repo sources composer-cli presents the same behavior

```
$ composer-cli compose types
ami
openstack
qcow2
```

**Comment by ondrejbudai** [comment]
Hello! Thanks for this issue! Building Fedora IOT images isn't currently supported by `osbuild-composer`.

It shouldn't be that hard to introduce the support: Mainly, it's needed to compare the package lists for x86_64 and aarch64.

The hard part might be to test this: Our `ostree.sh` test currently runs a VM but our team currently doesn't have any aarch64 machines that can run KVM VMs. FTR, I tried modifying `ostree.sh` to use an emulated machine (using qemu) but IRC Anaconda got stuck.

**Comment by pciavald** [comment]
Hi @ondrejbudai thank you for your fast answer !

I'm not sure that I understand what you mean by `Building Fedora IOT images isn't currently supported by osbuild-composer` as it does work on my machine running fedora33-workstation-x86 (maybe it shouldn't by the way, see at bottom), and is also demonstrated to work on a supposedly aarch64 machine in [this tutorial](https://www.osbuild.org/news/2020-06-01-how-to-ostree-anaconda.html).

About virtualization: 

I started fedora33-server-aarch64 without issue in qemu emulating aarch64 on x86 but it was painfully slow on a decent machine, I wouldn't recommend it (10+min boot time, good luck for the build :joy: ). 

However i'm currently running 2 kvm VMs on my [centos8](https://people.centos.org/pgreco/CentOS-Userland-8-aarch64-RaspberryPI-Minimal-4/) rpi4 including fedora33-server-aarch64 (in order to build the image I need, which I did not success yet because the Fedora IoT type is not present). 

I'm also currently deploying a new rpi4 with fedora33-server-aarch64 as host instead of VM, because I initially thought that the type Fedora IoT Commit was maybe not available because osbuild can't run kvm in kvm on rpi4, so i will enable kvm on this host. I can provide it for your tests if that is something you would see fit.

I'm currently stuck by this issue, could you help me by providing the way to enable manually this option so I can test the build on the new host ? I'm currently building an ostree OS for a commercial device we're going to release quite soon.

Bottom: Writing these lines I realized I actually successfully built a Fedora IOT image without additional packages on the x86 machine, I wonder what is the state of this image. As far as I understand it should not be functional as it must contain x86 packages in an aarch64 image ?

**Comment by ondrejbudai** [comment]
I'm sorry, I missed one word: Building Fedora IoT images for aarch64 isn't currently implemented. Building IoT images is available only for x86_64.

**Comment by pciavald** [comment]
Hi @ondrejbudai thank you for your answer.

Is it on the roadmap though ? To me IoT sounds more like arm than x86. I'm willing to help implementing and testing if you can guide me a little on what's to be done.

Are there alternatives to building our own OS using ostree for aarch64 rpi ?

**Comment by teg** [comment]
Hi @pciavald! Thanks for your interest! Fedora IoT support for aarch64 is definitely something we would like to have, and it should not be a lot of work, I think.

This is what we'll need to do:

### Definition

Each image type is defined for each distro and architecture in `internal/distro/*/distro.go`. We'd need to add an entry here for Fedora/aarch64. Take inspiration from `RHEL for Edge` as well as Fedora/x86_64.

As we are not the single source of truth for what makes Fedora IoT, we will need to look at the official definitions / .ks / commits to make our definition as close as possible to that. We don't want just a Fedora-based ostree image type, but actually Fedora IoT (or we would have to name it something else). @nullr0ute is the authority on Fedora IoT, so he would hopefully be happy to review/ack whatever we come up with, and @gicmo has done this in the past so might also have some insight.

### Testing

All image types need to be tested in our CI. For this, look in `test/cases`, and take inspiration from the current `RHEL for Edge` tests there.

**Comment by msehnout** [comment]
Here is the official kickstart mentioned above: https://pagure.io/fedora-kickstarts/blob/main/f/fedora-iot.ks

**Comment by oglok** [comment]
RHEL for Edge would be part of this issue, as ARM is a key target platform for edge devices.

**Comment by ondrejbudai** [comment]
We do support aarch64 for RHEL for Edge.

**Comment by zwtop** [comment]
I think the definition of Fedora-IoT is here: https://pagure.io/fedora-iot/ostree/blob/f34/f/fedora-iot-base.json.
To support building Fedora-IoT type image on aarch64, all that's left is testing?

**Comment by ondrejbudai** [comment]
fedora-iot-commit as supported on aarch64 since https://github.com/osbuild/osbuild-composer/pull/2461
