### ISSUE TITLE
RHEL 8.4 qcow2 images fail to depsolve on s390x and ppc64le

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1217]
`dbxtool` isn't available on `s390x` and `ppc64le`

Relevant commit: a3cb930d6a9e37a9c7ac985fc326b4288554758c

cc @jkozol

**Comment by larskarlitski** [comment]
This was fixed with https://github.com/osbuild/osbuild-composer/pull/1218, right?

**Comment by jkozol** [comment]
@larskarlitski thanks for pointing this out. Yes it was.
