### ISSUE TITLE
podman is broken on RHEL 8.4

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1237]
This causes the koji test to fail, see the upstream PR to fix it: https://github.com/containers/podman/pull/9383

We don't need to do any actions on our side, I'm opening this issue just to track it.

```
Starting containers
/etc/cni/net.d/org.osbuild.koji.conflist
Trying to pull quay.io/osbuild/postgres:v1...
Getting image source signatures
Copying blob sha256:c393806625cde0c68d6881aaeb6a8305d841ad1ec4e6152fe5dde27a6c7b4af8
Copying blob sha256:5eee78b95230e292517369656c57174ab474a5816040c1c9b97857e2b1d151ef
Copying blob sha256:9307f3bcca3a3c96fa4f21cc851f49f877096fc2626817d148d1c8cbc70bcb25
Copying blob sha256:c0f2174cad0ecea8b84d0f6fb84fdb82b77623253a01f65f0854bcb26be6c24a
Copying blob sha256:7ff5918c11c3ab1f2763192c7c033f5dfe60b30d369a8aa483d65326974b637a
Copying blob sha256:4c0d98bf9879488e0407f897d9dd4bf758555a78e39675e72b5124ccf12c2580
Copying blob sha256:1011823211fa960c4dae9c5929e2b284c9617492e99ffbf7f95d91c709606401
Copying blob sha256:dd6b4e21c9936b9d3a480bcc26a0b6e7a4fb71f11e70c63f4da7953d0c8dbc92
Copying config sha256:8c6053d81a45b455a79e7abbc5b4d8410735f060634d345f70b0530b1d50b2b6
Writing manifest to image destinatio
Storing signatures
Error: error streaming container content for copy up into volume 43c27231c2d86fe198a879982a1652acda757eeb66e074f246dc4d3bb02e745b: copier: get: globs [/postgresql/data] matched nothing (0 filtered out): no such file or directory
```

**Comment by ondrejbudai** [comment]
I temporarily pinned the `RHEL-8.4.0-20210217.n.0` snapshot. FTR, this is done here: https://osbuildci.cloud.paas.psi.redhat.com/configfiles/editConfig?id=rhel84-nightly-psi-cloud-init

I will remove the pin when this issue is fixed.

**Comment by atodorov** [comment]
FTR -> https://bugzilla.redhat.com/show_bug.cgi?id=1930134

**Comment by atodorov** [comment]
> I temporarily pinned the `RHEL-8.4.0-20210217.n.0` snapshot. FTR, this is done here: https://osbuildci.cloud.paas.psi.redhat.com/configfiles/editConfig?id=rhel84-nightly-psi-cloud-init
> 
> I will remove the pin when this issue is fixed.

FTR this doesn't work because `schutzbot/prepare-rhel-nightly.sh` adds another set of dnf repositories which are newer. We also need to pin podman version!

**Comment by ondrejbudai** [comment]
This is now fixed, pinning was removed.
