### ISSUE TITLE
Return clear error message when out of disk space

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#1270]
If the image builder machine does not have enough disk space, the compose command will fail, and in the log it only reports "non-zero exit status 233", suggest to return clear error message to tell user the fail reason is out of disk space.

Env:
RHEL8.4
osbuild-composer-28-1.el8.x86_64

Reproduce steps:
1. Run command: composer-cli compose start ostree rhel-edge-commit
2. The command will fail soon, check log:

Output:
[/usr/lib/tmpfiles.d/httpd.conf:1] Unknown group 'apache'.
[/usr/lib/tmpfiles.d/httpd.conf:2] Unknown user 'apache'.
[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
[/usr/lib/tmpfiles.d/radvd.conf:1] Unknown user 'radvd'.
[/usr/lib/tmpfiles.d/rpcbind.conf:2] Unknown user 'rpc'.
[/usr/lib/tmpfiles.d/setroubleshoot.conf:1] Unknown user 'setroubleshoot'.
Failed to create file /sys/fs/selinux/checkreqprot: Read-only file system
Preparing packages...
  installing package selinux-policy-targeted-3.14.3-65.el8.noarch needs 62MB on the / filesystem
  installing package libsecret-0.18.6-1.el8.x86_64 needs 63MB on the / filesystem
  installing package pinentry-1.1.0-2.el8.x86_64 needs 63MB on the / filesystem
  installing package grub2-tools-extra-1:2.02-97.el8.x86_64 needs 70MB on the / filesystem
  installing package rpm-plugin-systemd-inhibit-4.14.3-13.el8.x86_64 needs 70MB on the / filesystem
  installing package tpm2-tss-2.3.2-3.el8.x86_64 needs 71MB on the / filesystem
  installing package ima-evm-utils-1.3.2-12.el8.x86_64 needs 72MB on the / filesystem
  installing package libusbx-1.0.23-4.el8.x86_64 needs 72MB on the / filesystem
  installing package gnupg2-smime-2.2.20-2.el8.x86_64 needs 73MB on the / filesystem
  installing package gnupg2-2.2.20-2.el8.x86_64 needs 83MB on the / filesystem
  installing package gpgme-1.13.1-7.el8.x86_64 needs 84MB on the / filesystem
  installing package librepo-1.12.0-3.el8.x86_64 needs 85MB on the / filesystem
  installing package ostree-libs-2020.7-3.el8.x86_64 needs 86MB on the / filesystem
  installing package libdnf-0.55.0-6.el8.x86_64 needs 88MB on the / filesystem
  installing package python3-libdnf-0.55.0-6.el8.x86_64 needs 93MB on the / filesystem
  installing package python3-hawkey-0.55.0-6.el8.x86_64 needs 93MB on the / filesystem
  installing package ostree-2020.7-3.el8.x86_64 needs 94MB on the / filesystem
  installing package rpm-ostree-libs-2020.7-3.el8.x86_64 needs 97MB on the / filesystem
  installing package python3-gpg-1.13.1-7.el8.x86_64 needs 98MB on the / filesystem
  installing package rpm-build-libs-4.14.3-13.el8.x86_64 needs 99MB on the / filesystem
  installing package python3-rpm-4.14.3-13.el8.x86_64 needs 100MB on the / filesystem
  installing package python3-libcomps-0.1.11-5.el8.x86_64 needs 100MB on the / filesystem
  installing package python3-dnf-4.4.2-10.el8.noarch needs 103MB on the / filesystem
  installing package python3-setuptools-39.2.0-6.el8.noarch needs 103MB on the / filesystem
  installing package python3-pip-9.0.3-19.el8.noarch needs 103MB on the / filesystem
  installing package python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64 needs 104MB on the / filesystem
  installing package python3-six-1.11.0-8.el8.noarch needs 104MB on the / filesystem
  installing package python3-iniparse-0.4-31.el8.noarch needs 104MB on the / filesystem
  installing package dnf-4.4.2-10.el8.noarch needs 107MB on the / filesystem
  installing package rpm-ostree-2020.7-3.el8.x86_64 needs 110MB on the / filesystem
  installing package grub2-pc-1:2.02-97.el8.x86_64 needs 110MB on the / filesystem
  installing package qemu-img-15:4.2.0-44.module+el8.4.0+9776+c5744f20.x86_64 needs 116MB on the / filesystem
  installing package xfsprogs-5.0.0-8.el8.x86_64 needs 121MB on the / filesystem
  installing package e2fsprogs-1.45.6-1.el8.x86_64 needs 126MB on the / filesystem
  installing package tar-2:1.30-5.el8.x86_64 needs 129MB on the / filesystem
  installing package dosfstools-4.1-6.el8.x86_64 needs 129MB on the / filesystem
imported gpg key
imported gpg key
creating a fake machine id
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.rpm", line 307, in <module>
    r = main(args["tree"], args["inputs"], args["options"])
  File "/run/osbuild/bin/org.osbuild.rpm", line 280, in main
    ], cwd=pkgpath, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rpm', '--verbose', '--root', '/run/osbuild/tree', '--define', '_pkgverify_level none', '--install', '/tmp/manifest.pbvxf92d']' returned non-zero exit status 233.

**Comment by msehnout** [comment]
This would have to be detected in osbuild first and then forwarded to osbuild-composer but it definitely makes sense from user point of view.

**Comment by yih-redhat** [comment]
Seems this issue will be fixed in PR https://github.com/osbuild/osbuild-composer/pull/1281.
I will check it after PR merged.

**Comment by msehnout** [comment]
Unfortunately it will not be fixed :-(. We still miss the mechanism for reporting out-of-disk space error from osbuild.

**Comment by yih-redhat** [comment]
Hi @msehnout , can you please explain a bit more about why it wont be fixed? As you mentioned, osbuild can report out-of-disk error, but seems this mechanism has changed?

**Comment by msehnout** [comment]
Hi, osbuild can report errors (as in any error), but it cannot detect that it failed because of out-of-disk error. So this still needs to be implemented in osbuild first.

**Comment by teg** [comment]
We definitely want to improve on the error reporting by osbuild, and this would be the first one to address I think. However, as @msehnout says, it PR #1281 does not fix this issue.
