### ISSUE TITLE
schutzbot: need a way to manage disk usage

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#1328]
We've got limited space which fills up quickly and causes all sorts of issues where Jenkins gets stuck.  We've got rapid development which fills up the disk space before Jenkins has the ability to clean up itself.

Ideas:
- run periodically
- keep the last 3 or 5 builds only
- remove oldest jobs

**Comment by jrusz** [comment]
Since we moved to Gitlab CI, this is no longer relevant, closing.
