### ISSUE TITLE
tests: some integration tests are skipped for RHEL9

### ISSUE THREAD

**Issue by jmikovic** [osbuild/osbuild-composer#1333]
`aws.sh`, `api.sh` integration are skipped completely and `koji-compose.py` is limited when running tests with `DISTRO_CODE` rhel_90 due to missing support for image types other than qcow2 for RHEL 9.0.

These tests should be enabled after the support for necessary image types is added.

relevant PR: https://github.com/osbuild/osbuild-composer/pull/1282

**Comment by atodorov** [comment]
FTR search for snippets like `if [[ $DISTRO_CODE == rhel_90 ]]; then`
