### ISSUE TITLE
bootiso: change location of kickstart file

### ISSUE THREAD

**Issue by gicmo** [osbuild/osbuild-composer#1363]
Due to a peculiarity of anaconda, various commands in `interactive-kickstart.ks` do not work (e.g. `text` or `autopart`), see [rhbz#1949902](https://bugzilla.redhat.com/show_bug.cgi?id=1949902).
The solution is to create the kickstart in a different place and then add a kernel command line option to point anaconda to that new location. For example, move the kickstart stage into the pipeline that creates the bootiso tree and have `"path": "edge.ks"` together with `"kernel_opts": "inst.ks=hd:LABEL=RHEL-8-4-X86_64:/edge.ks",` for the `bootiso.mono` stage in the same pipeline.

**Comment by achilleas-k** [comment]
I'll fix this alongside the installer image type I'm working on now.

**Comment by teg** [comment]
Does it make sense to do this in a way that is compatible with mkksiso?

**Comment by gicmo** [comment]
> Does it make sense to do this in a way that is compatible with mkksiso?

Not sure I understand completely, you mean doing in the same way as `mkksiso` does or so that we don't break `mkksios`?

**Comment by teg** [comment]
> > Does it make sense to do this in a way that is compatible with mkksiso?
> 
> Not sure I understand completely, you mean doing in the same way as `mkksiso` does or so that we don't break `mkksios`?

Certainly don't break `mkksiso` (it currently works), but I meant to do it in the same way so that `mkksiso` would essentially overwrite the default file we embed. Not sure if that is the right way to go, just thinking about how we can limit the number of kickstart locations we are dealing with...

**Comment by gicmo** [comment]
> > > Does it make sense to do this in a way that is compatible with mkksiso?
> > 
> > 
> > Not sure I understand completely, you mean doing in the same way as `mkksiso` does or so that we don't break `mkksios`?
> 
> Certainly don't break `mkksiso` (it currently works), but I meant to do it in the same way so that `mkksiso` would essentially overwrite the default file we embed. Not sure if that is the right way to go, just thinking about how we can limit the number of kickstart locations we are dealing with...

`mkksiso` takes the name of the kickstart file and embeds it with that name on the root of the iso, so there is not really a default file. In my tests, I also did put it at the root of the ISO very much like `mkksiso` and we also then specify the file at the kernel command line, so I guess we are already doing what you had in mind.

**Comment by achilleas-k** [comment]
Commit https://github.com/achilleas-k/osbuild-composer/commit/579a0765fa6e4c56296aa1aaaf5d0893c442cfa3 puts it in the location @gicmo describes.  The kickstart file is named `osbuild.ks` to make its origin obvious.
