### ISSUE TITLE
systemctl start osbuild-composer.service failed at centos8

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1383]
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit osbuild-worker@1.service has entered the 'failed' state with result 'exit-code'.
4月 30 09:17:10 arm-kojid systemd[1]: Failed to start OSBuild Composer Worker (1).
-- Subject: osbuild-worker@1.service 单元已失败
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- osbuild-worker@1.service 单元已失败

**Comment by ondrejbudai** [comment]
Hello, can you write more details about this issue? When did it happen? What were you doing? Is the distribution CentOS Stream 8 or CentOS Linux 8?

**Comment by zhangdexin** [comment]
After I yum install, It happened. And CentOS Stream 8 and CentOS Linux 8 all for this.
And I run "dnf update", and it work.
So I think composer to centos8 rpms version sometthing wrong
