### ISSUE TITLE
Question: Replacement of single "core" packages?

### ISSUE THREAD

**Issue by Funky185540** [osbuild/osbuild-composer#1385]
Hello,

I'm currently looking into setting up a Fedora Remix using the osbuild tools. The Remix is supposed to target Linux-based mobile phones (PinePhone, Librem 5).
Due to the state of support for mobile devices in Linux there is a [COPR](https://copr.fedorainfracloud.org/coprs/njha/mobile/) repository that hosts some packages needed to run on the phone to make it usable. One of these packages is the Linux kernel, because not all patches for the PinePhone have been upstreamed yet.

I saw in the [docs](https://github.com/osbuild/guides) in section 1.5 that it is possible to add custom repositories (like the COPR), but it says that I can only replace packages when I replace the whole repo, i.e. I mirror all packages myself. This currently isn't an option for us.

That's why I would like to know: Is it possible, or will it ever be possible, to add custom 3rd party repositories and to replace select packages of the base image with equal packages from this custom repository?

Thank you!

Andreas

**Comment by msehnout** [comment]
Any update on this issue? As Tom suggested it should only be a matter of adding a source and having a kernel RPM which takes precedence, e.g. using higher epoch, version or release number. If that is the case, I believe this issue can be closed.

**Comment by Funky185540** [comment]
Sorry for not responding!

osbuild kind of slipped from my todo as I got another suggestion how to "solve" my particular issue that seems more "lightweight". In any case, thanks for helping me!
