### ISSUE TITLE
org.osbuild.curl: curl: error downloading failed

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1389]
osbuild-worker[1550]: RuntimeError: org.osbuild.curl: curl: error downloading {'url': 'http://mirrors.neusoft.edu.cn/centos/8-stream/AppStream/x86_64/os/Packages/libxcb-1.13.1-1.el8.x86_64.rpm'}: error code 28

when I  build on x86_64
Is my config something wrong?
And I check env the libxcb is installed.

**Comment by msehnout** [comment]
Error code 28 in `curl` means operation timeout. You can retry the image build.

The timeout itself can have many different causes ranging from slow internet connection to rate limiting on the server. It is hard to tell, but there is very little to be done on the osbuild-composer side.
