### ISSUE TITLE
ostree-based artifacts are not supported on CentOS Stream

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1392]
[build a RHEL for Edge Installer](https://www.osbuild.org/guides/user-guide/edge-container+installer.html) and 
[build ostree image](https://www.osbuild.org/guides/user-guide/building-ostree-images.html)

In My env, centos8 stream x86 and aarch64
`$ sudo composer-cli compose`
`ami`
`openstack`
`qcow2`
`tar`

It has not rhel-edge-container and fedora-iot-commit image types, How I config?

the version are:
`$ rpm -qa | grep osbuild`
`osbuild-27.2-1.el8.noarch`
`osbuild-ostree-27.2-1.el8.noarch`
`osbuild-composer-core-28.4-1.el8.0.1.aarch64`
`osbuild-selinux-27.2-1.el8.noarch`
`osbuild-composer-worker-28.4-1.el8.0.1.aarch64`
`osbuild-composer-28.4-1.el8.0.1.aarch64`
`python3-osbuild-27.2-1.el8.noarch`

**Comment by ondrejbudai** [comment]
Hi, building ostree-based artifacts isn't currently supported on CentOS Stream. We do plan to add very soon though. If you want to try it, you can use Fedora or the free RHEL Developer Subscription (you may want to use 8.4 Beta, it has better support for building ostree-based artifacts).

**Comment by zhangdexin** [comment]
Oh, thanks. Have some roadmap for support  CentOS Stream?

**Comment by ondrejbudai** [comment]
I'm not able to come up with any estimates but we're already working on the groundwork for ostree support on CS, see https://github.com/osbuild/osbuild-composer/pull/1391 and https://github.com/osbuild/osbuild-composer/pull/1351
