### ISSUE TITLE
composer remote worker guide?

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1404]
Currently, I deploy composer remote worker, and i ref [this](https://github.com/osbuild/osbuild-composer/commit/820d23fd9d216a93cde3b9964197506867896407). I could not find composer side listen 8700, have some detail guide?
Thanks

**Comment by msehnout** [comment]
No, as I said in https://github.com/osbuild/guides/issues/35, this is not documented yet.

Closed as a duplicate of: https://github.com/osbuild/guides/issues/35
