### ISSUE TITLE
replace repo has python error?

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1420]
I replace my repo, the detail in [this](https://github.com/osbuild/osbuild-composer/issues/1417) mentioned, and my core group compare with centos8 core group, not have these pkg:
```dnf, sssd-common, sssd-kcm, authselect, dnf-plugins-core, lshw, prefixdevname, tboot```
When start compose, It has this error:

```
Output:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site.py", line 556, in <module>
    main()
  File "/usr/lib64/python2.7/site.py", line 538, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib64/python2.7/site.py", line 266, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib64/python2.7/site.py", line 241, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib64/python2.7/site.py", line 231, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib64/python2.7/sysconfig.py", line 516, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib64/python2.7/sysconfig.py", line 473, in get_config_vars
    _CONFIG_VARS['userbase'] = _getuserbase()
  File "/usr/lib64/python2.7/sysconfig.py", line 187, in _getuserbase
    return env_base if env_base else joinuser("~", ".local")
  File "/usr/lib64/python2.7/sysconfig.py", line 173, in joinuser
    return os.path.expanduser(os.path.join(*args))
  File "/usr/lib64/python2.7/posixpath.py", line 269, in expanduser
    userhome = pwd.getpwuid(os.getuid()).pw_dir
KeyError: 'getpwuid(): uid not found: `0'`
```

have some advice??
Thanks

**Comment by msehnout** [comment]
Your system uses `python2.7` which is far too old to be supported upstream. Please try this using a fresh and latest CentOS 8 Stream installation to verify that this is not a configuration issue on your host machine (for example if you used `update-alternatives` to configure Python, this might be the issue)

**Comment by zhangdexin** [comment]
In the manifest file, It has python2 and python3. Because some rpm depend python2, so the issue is for the situation?
But the info of output that look  getpwuid() error?
So i am confuse, please help me explain that?
Thanks

**Comment by msehnout** [comment]
I can see the getpwuid error, but you seem to have highly customized setup: we don't expect or support running osbuild with Python2 and we also don't support groups with the same name yet different content. Unless you can provide full reproducer or get the same error using a default CentOS and osbuild-composer, I'm afraid we, as the upstream developers, cannot help you.

**Comment by zhangdexin** [comment]
Thank you for reply. I try find out.  Thanks again

**Comment by msehnout** [comment]
OSBuild is not supposed to run with Python 2. I'm closing this issue now, but feel free to reopen if you hit the issue with Python 3 on latest CentOS Stream.
