### ISSUE TITLE
Composes should contain frozen blueprint

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#143]
Currently, we just copy the blueprint to the new compose. This means they can contain wildcard package versions.

However, Lorax does a different thing: Takes all the extra packages and groups, depsolves them and replaces the wildcard versions with specific ones. This process is known in lorax's codebase as blueprint freezing.

This has visible outcomes in some APIs like `/compose/info` or `/compose/metadata`. Generally it's a good feature for reproducibility of composes.

**Comment by teg** [comment]
This was closed by #214
