### ISSUE TITLE
jobs get stuck in running state

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#1432]
**Describe the bug**
When the worker crashes/is restarted or simply hangs, a job is never failed but stays "running" forever.

**To Reproduce**
 * Start a compose
 * Before the job has completed, restart the worker using `systemctl restart osbuild-worker\@1`

**Expected behavior**
The job is marked as `failed`, or possibly retried.

**Additional context**
I imagine we want some watchdog logic, where if the worker has not reported back within a certain timeframe we fail the job. This means needing to have a watchdog process/thread in composer, so far we did not have any long-running tasks like that in composer.

Automatically restarting a job, we could reasonably leave to upper layers, or at least get back to later.

**Comment by ondrejbudai** [comment]
Additional context: I think the end goal for composer is to run multiple stateless replicas of it in k8s. The watchdog logic must be able to run in such environment.

**Comment by msehnout** [comment]
This could benefit from the job queue implemented above a DB, no? Because we could create the watchdog as a separate service (both in systemd  and openshift terms).

Also when combined with depsolv workers, there is very little work left for the composer. In the cloud API case, it would only provide access control and interface to the DB (unless I forgot something :-) ). In the Weldr API case it would keep the sources and blueprints. Otherwise, it would only serve as an interface to the DB.

**Comment by msehnout** [comment]
> I imagine we want some watchdog logic, where if the worker has not reported back within a certain timeframe we fail the job.

Do you mean a timeout for the whole build process or a periodic message from the worker to the composer?

**Comment by teg** [comment]
> > I imagine we want some watchdog logic, where if the worker has not reported back within a certain timeframe we fail the job.
> 
> Do you mean a timeout for the whole build process or a periodic message from the worker to the composer?

The latter. The worker already calls back to check for cancellation, so composer just needs to remember that.

**Comment by teg** [comment]
> This could benefit from the job queue implemented above a DB, no? Because we could create the watchdog as a separate service (both in systemd  and openshift terms).
> 
> Also when combined with depsolv workers, there is very little work left for the composer. In the cloud API case, it would only provide access control and interface to the DB (unless I forgot something :-) ). In the Weldr API case it would keep the sources and blueprints. Otherwise, it would only serve as an interface to the DB.

Yeah, this would be the ideal state!

**Comment by Gundersanne** [comment]
This was implemented in https://github.com/osbuild/osbuild-composer/pull/1523 using the cancel check as a heartbeat/refresh. I picked 2 minutes as a timeout. Not as a separate service however, the worker server just checks every 30 seconds, could change that in future?

**Comment by Gundersanne** [comment]
I'll close this for now then, but feel free to reopen of course.
