### ISSUE TITLE
Add a way to add new RHEL channel as source for a build

### ISSUE THREAD

**Issue by pypingou** [osbuild/osbuild-composer#1445]
**Describe the bug**
Currently only the baseos and appstream channels are available for RHEL images.
Adding a new channel using ``composer-cli sources add ...`` does not work as it gets a 403 error from the CDN, even if the system is properly subscribed and can pull just fine other packages from the CDN

**Environment**
 * OS version: RHEL 8.4
 * osbuild-composer version: osbuild-composer-28.4-1.el8.x86_64

**To Reproduce**

* Try adding a new source to image-builder that enables the OCP channel or the Code Ready Builder channel
* Run ``composer-cli compose depsolve <blueprint_name>``
* See it fail because of a 403 returned by the CDN

**Expected behavior**
Being able to add new channel via the ``sources new`` command.

**Additional context**
The issue can be circumvent by editing ``/usr/share/osbuild-composer/repositories/rhel-8.json`` manually.
It seems the issue is that the current format/UI doesn't support specifying ``rhsm=true`` when adding a new source.

**Comment by msehnout** [comment]
Thanks for filling in this issue! You are absolutely correct that the sources cannot define RHSM, which is something we should fix: https://github.com/osbuild/osbuild-composer/blob/9a4b5763e9da6701d67d12b8c048d07a70b668de/internal/store/store.go#L45
