### ISSUE TITLE
Ability to specify image size on creation

### ISSUE THREAD

**Issue by jgiardino** [osbuild/osbuild-composer#145]
Currently, Image Builder generates images that are of fixed size. This is almost never the size that people need, because they want to, for example, install additional software or run software that has larger storage requirements (such as Image Builder itself). In practice, this means people always have to manually resize the generated image to the size they require.

To make this easier, let’s allow specifying the size when creating the image.

Acceptance criteria:
1. Image size can be set via the compose API (new `size` key) and in the front end 
    - ideas for UI are captured in [this document](https://docs.google.com/document/d/1evl0KVF-awupKAmX9pstW9Mo41zZ8rH8Y_pJ4q3yT64/edit?usp=sharing)
    - source html/css for the mockups shown are included in [codesandbox](https://codesandbox.io/s/image-size-range-input-vk5df)
2. The image list in the front end shows the image size as well
3. Images continue fulfilling alignment requirements (Azure wants 1MB, for example: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic)

Nice to have:
1. Image size can be set from `composer-cli` (maybe with `--size`?) as well.
2. Research suitable defaults and min / max values for all output formats. 

The issue for the UI is https://github.com/weldr/cockpit-composer/issues/840

**Comment by jgiardino** [comment]
For AC#3, my expectation is that these limitations are handled by the API and not in the UI. Please correct me if I'm wrong on that. For example, if the API is given a value that cannot be used, then the API would handle rounding up or down to the nearest value that can be used. 

Also, the level of information we provide in the UI would be dependent on how the API handles these types of things. Since string freeze is coming up mid-Dec, we need to know how difference cases would be handled so that we can get the text strings in on time.

**Comment by teg** [comment]
@jkozol did you not already implement this?

**Comment by jkozol** [comment]
This has been implemented by #184 and #215.
