### ISSUE TITLE
ostree tests never finish

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1453]
Even though an ostree test "finishes successfully", it never actually finishes. After 12 hours, it's killed by the runner and a failure is reported.

My guess is that we leave somewhere a process in the background. Sadly, that's something that our new CI on GitLab really doesn't like and can't handle (this is an ssh limitation).

Example:
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1321521694

**Comment by ondrejbudai** [comment]
I think this PR caused it: https://github.com/osbuild/osbuild-composer/pull/1443

**Comment by ondrejbudai** [comment]
In #1443, the testing pipeline wasn't run. In GitLab CI, it's marked as canceled: https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/314894013/builds

I guess we didn't notice that GitLab is missing in the checks and just merged it.

@atodorov @jrusz Please, explicitly check before merging PRs that GitLab CI ran. We need to pay extra attention when dealing with tests/CI setup. If you ever see this weird behavior of GitLab CI again, please report/investigate it.

**Comment by teg** [comment]
@ondrejbudai is it possible to make tests mandatory so we block merging until they report back?

**Comment by ondrejbudai** [comment]
it's on my todo list to look into this. :)

**Comment by ondrejbudai** [comment]
Fixed by  #1456
