### ISSUE TITLE
EL8 `aarch64` tests sometimes hang

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1463]
This was worked around by https://github.com/osbuild/osbuild/pull/657 and it's also reported downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1969848

This issue will be solved when a new version of osbuild is released and gets into downstream, or Schutzfile.

**Comment by atodorov** [comment]
> This issue will be solved when a new version of osbuild is released and gets into downstream, or Schutzfile.

Shutzfile was recently updated, does bc76f437a051c96657af4db72124d40dceabf8e6 solve the problem or not ?

**Comment by ondrejbudai** [comment]
Just happened here, not sure which osbuild commit is used, will look into it later: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1416282164

**Comment by ondrejbudai** [comment]
This is fixed for a long time.
