### ISSUE TITLE
The image type 'rhel-edge-installer' doesn't work for medium/big images

### ISSUE THREAD

**Issue by juanje** [osbuild/osbuild-composer#1469]
**Describe the bug**
The image type `rhel-edge-installer` fails when the resulting image is too big (bigger than 4Gb).

I created a blueprint to install GNOME and one graphical app (Neptune). The `osbuild-composer` was able to build the images `rhel-edge-commit` and `rhel-edge-container`, but it failed when I tried to create the `rhel-edge-installer`.
It fails at the stage `bootiso-tree:0-org.osbuild.bootiso.mono` with errors of `No space left on device`.

The `ostree` repository's size is 1.4 Gb. 

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 ```
 # cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.4 (Ootpa)

```
 * osbuild-composer version (`rpm -qi osbuild-composer)`
```
# rpm -qi osbuild-composer
Name        : osbuild-composer
Version     : 28.4
Release     : 1.el8
Architecture: x86_64
Install Date: Thu 10 Jun 2021 07:45:36 PM EDT
Group       : Unspecified
Size        : 17237
License     : ASL 2.0
Signature   : RSA/SHA256, Fri 09 Apr 2021 08:04:36 AM EDT, Key ID 199e2f91fd431d51
Source RPM  : osbuild-composer-28.4-1.el8.src.rpm
Build Date  : Fri 09 Apr 2021 05:03:32 AM EDT
Build Host  : x86-vm-55.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://github.com/osbuild/osbuild-composer
Summary     : An image building service based on osbuild
Description :

An image building service based on osbuild
It is inspired by lorax-composer and exposes the same API.
As such, it is a drop-in replacement.
```

**To Reproduce**
* Create a fresh system (VM or baremetal), with plenty of memory and disk, and the `osbuild-composer` installed.
* Create a blueprint that install GNOME and some graphical app and push it to `osbuild-composer`.
* Try to create a `rhel-edge-installer` image.

Also you can use the script for testing that I was using: https://github.com/juanje/rhel-edge/blob/neptune_app/ostree-ng.sh

It need to be run in a RHEL 8.4 system with the proper subscription set.

**Expected behavior**
To finish the creation of the `rhel-edge-installer`.

**Additional context**
This issue is been discussed with @gicmo and it seems to be related to a fixed size limit (4 Gb) for the `rootfs`:
https://github.com/osbuild/osbuild-composer/blob/v30/internal/distro/rhel84/distro_v2.go#L732

**Comment by nullr0ute** [comment]
Is there a spec limitation to the size of a .iso?

**Comment by juanje** [comment]
@nullr0ute According to the conversation I had with @gicmo, it has an arbitrary limit in the code. There was no actual reason to put that limit other than it sounds reasonable and big enough for most cases.

**Comment by gicmo** [comment]
There is a maximum limit, which I think is around 8TB. But, the actual solution to this issue here is to *not* have the commit embedded in the squashfs, but have it on the root of the iso, very much like what will happen for the Fedora CoreOS Installer that Antonio is working on. Then the commit can be as big as the iso allows (apparently quite big).
