### ISSUE TITLE
[GITLAB CI] Don't mask region in CI logs

### ISSUE THREAD

**Issue by thozza** [osbuild/osbuild-composer#1472]
The job log from Gitlab CI has the AWS region masked out, which makes it harder to reproduce some issues from CI and simply copy&paste values from the log. Examples are:
```
Running on ip-10-30-18-34.us-east-1.aws.[MASKED]...
```
or
```
baseurl=http://osbuild-composer-repos.s3-website.[MASKED].amazonaws.com/gitlab/osbuild-composer/fedora-33/x86_64/5340d19a4319288fecff10d344062b12905d3006
```
and so on...

In general I would suggest not to mask anything that is not considered a secret or potentially a sensitive information (like email address).

**Comment by ondrejbudai** [comment]
If something is not a secret, we should probably define it somewhere in code. My suggestions is `.gitlab-ci.yml` or just the test scripts (maybe with the option to overwrite it).

**Comment by atodorov** [comment]
You can also go to Settings -> CI/CD -> Variables and uncheck the  checkbox which causes GitLab to mask the values in the logs.

**Comment by jrusz** [comment]
I found this to be a pain as well, I just unmasked several region variables and also some containing the word "compsoer". I hope it's going to get better now.
