### ISSUE TITLE
[CI] List all installed RPMs on the system running the test case

### ISSUE THREAD

**Issue by thozza** [osbuild/osbuild-composer#1474]
Job logs in Gitlab CI list only NVRs of packages which were explicitly installed as part of the job, but there is no information about packages which were already installed on the image used for CI run.

I would like to suggest, that we run `rpm -qa` as part of each job and log the output. This should be done ideally after all setup steps were finished and before the particular test case is executed. Having this kind of information will make it easier to debug potential CI failures and properly reproduce the environment.

**Comment by jrusz** [comment]
fixed in https://github.com/osbuild/osbuild-composer/pull/2403
