### ISSUE TITLE
Fedora images: need to remove cloud-init package and upgrade WALinuxAgent in Fedora 33

### ISSUE THREAD

**Issue by yuxisun1217** [osbuild/osbuild-composer#1479]
**Describe the bug**
The WALinuxAgent package, which is the provisioning agent of Azure, doesn't support Fedora. It makes the VM provisioning failed.
```
2021-06-18T09:55:22.482275Z WARNING Daemon Daemon Unable to load distro implementation for fedora. Using default distro implementation instead.
```
I think we need to either do not test fedora image on Azure, or skip VM boot up testing on Azure for fedora images.

**Comment by atodorov** [comment]
All previous indications are that Fedora VMs used to work in Azure. We need information which Fedora version is affected and if there are any possible recent changes that may have caused this. So far the indications are that this should not be happening which means it is a newly introduced bug.

**Comment by yuxisun1217** [comment]
Just checked the log and yes the Fedora can boot up on Azure. The failed reason is that the WALinuxAgent version is too low, which hits this issue: https://github.com/Azure/WALinuxAgent/issues/2080
We need to update the WALinuxAgent package in the repo to WALinuxAgent-2.2.52-1.fc33.noarch.rpm.

**Comment by yuxisun1217** [comment]
Just opened a bug here: https://bugzilla.redhat.com/show_bug.cgi?id=1974262

**Comment by atodorov** [comment]
I don't think cloud-init is going to be removed. We've had an explicit request to add support for it in the past. Closing, can track the upgrade of the walinuxagent package separately. Do not reuse issues for different topics.

**Comment by yuxisun1217** [comment]
Opened a ticket https://issues.redhat.com/browse/COMPOSER-997 to track the WALinuxAgent issue.

**Comment by ondrejbudai** [comment]
This error from the log really concerns me:

```
+ az image delete --resource-group [MASKED] --name osbuild-composer-api-test-e755ac9f-c949-4fa6-9c18-f647811250c3
ERROR: (OperationNotAllowed) Operation 'Image Delete' is not allowed since the Virtual Machines 'vm-5ab0d54a-8bdc-49a9-926c-d09e77a5330d' are being provisioned using the Image 'osbuild-composer-api-test-e755ac9f-c949-4fa6-9c18-f647811250c3'.
```

Isn't this the reason why we've recently seen a spike of leftover VMs in Azure?

**Comment by ondrejbudai** [comment]
Also, note that the rpmrepo snapshot that we're using for Fedora 33 contains `WALinuxAgent-2.2.48.1`. If we want a newer one, we need to update the snapshot in `test/data/repositories`.

**Comment by yuxisun1217** [comment]
> This error from the log really concerns me:
> 
> ```
> + az image delete --resource-group [MASKED] --name osbuild-composer-api-test-e755ac9f-c949-4fa6-9c18-f647811250c3
> ERROR: (OperationNotAllowed) Operation 'Image Delete' is not allowed since the Virtual Machines 'vm-5ab0d54a-8bdc-49a9-926c-d09e77a5330d' are being provisioned using the Image 'osbuild-composer-api-test-e755ac9f-c949-4fa6-9c18-f647811250c3'.
> ```
> 
> Isn't this the reason why we've recently seen a spike of leftover VMs in Azure?

Ah yes! So I think I should move the "image delete" after the "vm delete" so that the broken VM will be deleted first.
