### ISSUE TITLE
How to give directions for live iso image?

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1494]
I want to get live iso, and I find rhel84 distro_v2.go  bootISO type, But i run get error 
```
boot ISO image type %q requires specifying a URL from which to retrieve the OSTree commit
```
So I want to kown how to give directions to run this？
Can you give some example?
```
composer-cli compose start base-bash rhel-edge-installer xxxx
```
thanks

**Comment by ondrejbudai** [comment]
If you want a live ISO for standard RHEL, we cannot build these yet. `rhel-edge-installer` creates an ISO for installing RHEL for Edge, see our docs: https://www.osbuild.org/guides/user-guide/edge-container+installer.html

**Comment by ondrejbudai** [comment]
Btw, discussions are a much better place for these kind of questions: https://github.com/osbuild/osbuild-composer/discussions/categories/q-a

I'm closing this issue for now, if you need more information, please open a new thread in the discussion section I linked above.

**Comment by zhangdexin** [comment]
thanks very much
