### ISSUE TITLE
[QE]Remove Fedora 33 ostree test due to BZ#1975660

### ISSUE THREAD

**Issue by yuxisun1217** [osbuild/osbuild-composer#1496]
Because of #1487 we need to use a new Fedora 33 repo for testing, but BZ#1975660 is a blocker issue of rpm-ostree. So I'd like to skip ostree testing in Fedora 33 branch until this BZ is fixed. (https://coreos.slack.com/archives/C0235DZB0DT/p1624522970260900?thread_ts=1624519325.259200&cid=C0235DZB0DT)
@atodorov Could you please share your opinion? Thanks!

**Comment by ondrejbudai** [comment]
#1498 was merged.
