### ISSUE TITLE
[CI] terraform fails to get aws provider fairly often

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#1502]
Me and @yuxisun1217 have noticed that terraform is failing to get providers. It's most prominent when provisioning aws runner but I've also noticed this with azure and openstack. I've created https://github.com/hashicorp/terraform/issues/29035 to hopefully get some answers. Opening this ticket to track that, it might be possible that it's just Gitlab failing to connect to the terraform registry... Also there is an upcomming maintenance for terraform registry, so that might help.
```
Scheduled Maintenance | Terraform Public Registry Jun 26, 01:00-01:30 UTC
Our team will be performing routine maintenance during this time. Some provider or module publishes may fail during this 30 minute window. If you experience this, wait until the maintenance ends and then resync your module/provider from the registry UI. We'll post updates as necessary during the maintenance. Thank you!
```
source: https://status.hashicorp.com/

Examples of failure to get provider:
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1376395988
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1376090828
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1375156997
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1375143812

**Comment by ondrejbudai** [comment]
I found

> The best place to ask about registry issues though would be to email terraform-registry@hashicorp.com.

here:

https://github.com/hashicorp/terraform/issues/27533

**Comment by jrusz** [comment]
Oh cool, thanks, I'll write an email there then because this is causing the CI to be half unusable currently...

**Comment by jrusz** [comment]
It seems it was just a temporary problem as we're not seeing these failures anymore and I got a response to my email that they're not seeing any problems on their end.
