### ISSUE TITLE
composer-cli fails on blueprint push

### ISSUE THREAD

**Issue by rlengland** [osbuild/osbuild-composer#1505]
When I try  _composer-cli_ it fails when pushing a new blueprint:  

> $ sudo composer-cli  blueprints push vim_bash_machine.toml   
ERROR: BlueprintsError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand: Near line 19 (last key parsed ''): Key '' was already created and cannot be used as an array.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 * 
$ cat /etc/os-release
NAME=Fedora
VERSION="34 (Thirty Four)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Thirty Four)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

$ cat /etc/redhat-release
Fedora release 34 (Thirty Four)

 * osbuild-composer version (`rpm -qi osbuild-composer)`
 * 
$ rpm -qi osbuild-composer
Name        : osbuild-composer
Version     : 30
Release     : 1.fc34
Architecture: x86_64
Install Date: Fri Jun 25 09:27:58 2021
Group       : Unspecified
Size        : 17297
License     : ASL 2.0
Signature   : RSA/SHA256, Tue Jun 15 04:50:23 2021, Key ID 1161ae6945719a39
Source RPM  : osbuild-composer-30-1.fc34.src.rpm
Build Date  : Tue Jun 15 04:31:20 2021
Build Host  : buildhw-x86-16.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/osbuild/osbuild-composer
Bug URL     : https://bugz.fedoraproject.org/osbuild-composer
Summary     : An image building service based on osbuild
Description :

A service for building customized OS artifacts, such as VM images and OSTree
commits, that uses osbuild under the hood. Besides building images for local
usage, it can also upload images directly to cloud.

It is compatible with composer-cli and cockpit-composer clients.

**To Reproduce**
 * *for example starting osbuild-composer.service or running composer-cli command, don't forget to include all configuration files you created*
 
Command used:
sudo composer-cli  blueprints push vim_bash_machine.toml   

Contents of vim_bash_machine.toml follow:

name = "vim_bash_image"
description = "vim image blueprint"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "bash-completion"
version = "*"

[[packages]]
name = "vim-X11"
version = "*"

[[packages]]
name = "vim-enhanced"
version = "*"

[[groups]]
name = "testgroup"

[[customizations.user]]
name = "root"
description = "root"
password = "$6$ZkdAX1t8QwEAc/GH$Oi3NY3fyTH87ALiPfCzZTwpCoKv7P3bCWnoD9JnI8f5gV9I3A0bq6mZrKrv6isuYatmRQ.SVq3Vq27v3X2yu."
home = "/home/root/"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]
uid = 0
gid = 0

[[customizations.group]]
name = "root"
gid = 0

**Expected behavior**
expected confirmation that the blueprint had been added

**Additional context**
The cockpit image builder  interface for osbuild-composer works fine

**Comment by ondrejbudai** [comment]
I think your blueprint is not a valid toml. You define groups twice. Once in `groups = []` and the second time in `[[groups]]`. If you remove `groups = []`, everything should work as expected. You can use the TOML linter to validate your blueprints: https://www.toml-lint.com/

Does this solve your issue?

**Comment by rlengland** [comment]
It does solve the issue. Operator error. Sorry for the wasted bandwidth

**Comment by ondrejbudai** [comment]
No worries, I'm glad it works for you now. :)
