### ISSUE TITLE
[QE] Add an external variable to specify the guest OS version

### ISSUE THREAD

**Issue by yuxisun1217** [osbuild/osbuild-composer#1508]
Currently in api.sh the guest OS version is not align with the base OS. Due to the [discussion](https://github.com/osbuild/osbuild-composer/pull/1473#discussion_r658804953) we'd like to add an external variable to specify the guest OS version, so that we can do some judgement prior to the guest VM boot up.

**Comment by atodorov** [comment]
We've decided that we're not going to use the proposed workaround so this issue is no longer needed.
