### ISSUE TITLE
CI: RHSM registration failing with 400 bad request

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#1519]
Happened in two RPM jobs for #1516.  Restarting fixed it.  Link to one occurrence below:

https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1393044190#L368

**Comment by ondrejbudai** [comment]
This is still happening. I think we should implement retry logic. I cannot think of anything better unfortunately.

**Comment by teg** [comment]
Relevant bit:
```
Registering to: subscription.rhsm.redhat.com:443/subscription

HTTP error (400 - Bad Request): Problem creating unit ConsumerDTO [uuid: null, name: ip-172-31-69-170.ec2.internal, owner id: null]

This system has no repositories available through subscriptions.
```

**Comment by teg** [comment]
Could this be what is going on for us too: https://bugzilla.redhat.com/show_bug.cgi?id=1815172#c10 ?

**Comment by jabia99** [comment]
Solved (probably) on this PR: https://github.com/osbuild/osbuild-composer/pull/1657

**Comment by teg** [comment]
Thanks @jabia99 !

**Comment by jrusz** [comment]
Unfortunately that did not help, see https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1530074570 for example and some other jobs in the pipeline failing in the same way. I guess we'll have to try implementing the retry logic.

**Comment by jabia99** [comment]
Next try to fix this issue on https://github.com/osbuild/osbuild-composer/pull/1671.

I'll close this if we don't get this error again in a few weeks or so

**Comment by jabia99** [comment]
Okay, I think nobody got the error in the last few weeks, so I'll close this issue.
