### ISSUE TITLE
build image in podman?

### ISSUE THREAD

**Issue by yellowhat** [osbuild/osbuild-composer#1542]
Hi,
from my understanding `osbuild-composer` can only build image based on the same running OS (Fedora images from Fedora OS, ...).
Is it possible to build images inside a podman container to avoid this limitation?
I have tried to install `osbuild-composer` in a `fedora:34` container but I cannot start the `osbuild-composer.socket` as `systemd` is not started.

Thanks

**Comment by teg** [comment]
See PR#1427, that might be what you are looking for.

Check out the docker compose file in the repo for how to run things in containers, but that's not really supported, so the above PR might be what you are looking for.

**Comment by ondrejbudai** [comment]
Hello!

Thanks for your interest in this project. As Tom said, this is something that's currently being worked on, stay tuned for future releases.

If you have any more questions about this project, feel free to open a thread in our discussions: https://github.com/osbuild/osbuild-composer/discussions/categories/q-a I believe that discussions are a better place for questions. :)

I'm closing this as I believe that this question is answered. Feel free to reopen or start a new thread in discussions.

**Comment by yellowhat** [comment]
Thanks for the reply.
PR#1427 looks very interesting.
Can you point me in the direction of the docker compose file. I only manage to find a reference to it in `NEWS.md`.

Thanks

**Comment by ondrejbudai** [comment]
Sure, https://github.com/osbuild/osbuild-composer/blob/main/distribution/docker-compose.yml :)
