### ISSUE TITLE
Azure tests leave resources behind

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1543]
This results in eg this error:

```
Error: creating/updating Public Ip Address: (Name "ip-centos_8-x86_64-PR-1427-1413856081" / Resource Group "[MASKED]"): network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="PublicIPCountLimitReached" Message="Cannot create more than 20 public IP addresses for this subscription in this region." Details=[]
```

See these jobs:
- https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1413856081
- https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1413856081

Or this error:
```
ERROR: {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'vm_deploy_fo0LyTecbwC1koqxosxEQE8W9z4Sal7V' is not valid according to the validation procedure. The tracking id is '510ba27c-42ed-4622-aa28-c5eea06fcd68'. See inner errors for details.","details":[{"code":"ResourceCountExceedsLimitDueToTemplate","message":"Subscription [MASKED] has a quota of 20 for resources of type PublicIpAddress with sku SkuNotSpecified. Subscription currently has 20 resources and the template contains 1 new resources of the this type which exceeds the quota. Please contact support to increase the quota for resource type PublicIpAddress","details":[]}]}}
```

See this job:
- https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1413856117

See CSV export of all stray resources: [Azureresources.csv](https://github.com/osbuild/osbuild-composer/files/6798949/Azureresources.csv)

**Comment by jrusz** [comment]
This should be resolved by https://github.com/osbuild/osbuild-composer/pull/1552 ... It runs cloud-cleaner according to schedule set in gitlab which is currently set to run in the morning and clean anything created by the azure tests that's older than 3 hours (timeout for ci jobs)
