### ISSUE TITLE
Command usage printed from setfiles in image-info on RHEL 8 hosts

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#1547]
While generating test manifests, I get the following output at the end of the run:
```
usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file pathname...
usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file -f filename
usage:  setfiles -s [-diIDlmnpqvFW] spec_file
usage:  setfiles -c policyfile spec_file
```

I suspect it's from the image-info call below.  The call we make doesn't seem to match the last usage line that uses the `-c` flag.

https://github.com/osbuild/osbuild-composer/blob/0b962c9185a6f137e772a61f6aa7a10c990f08f7/tools/image-info#L936-L949

but the `check_output()` call would be raising `CalledProcessError` if that were the case.

**Comment by achilleas-k** [comment]
Known issue: [rhbz#1973754](https://bugzilla.redhat.com/show_bug.cgi?id=1973754)

**Comment by thozza** [comment]
This is a known issue with `setfiles` on RHEL-8. It does not allow one to use the `-c` option as `image-info` uses it. This works just fine with the latest upstream or in Fedora. Workaround would be to generate the image test cases (even the ones for RHEL) on Fedora 34 system or newer.

The issue had been workarounded in tests via https://github.com/osbuild/osbuild-composer/pull/1485
