### ISSUE TITLE
[QE] Is composer only support host distro?

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1560]
**Describe**
Cur I want to build a image not my host distro, but I See the code:
```
...
hostDistroName, _, _, err := distro.GetHostDistroName()
if err != nil {
return nil, fmt.Errorf("host distro is not supported")
}
archName := common.CurrentArch()

hostDistro := dr.GetDistro(hostDistroName)
hostArch, err := hostDistro.GetArch(archName)
if err != nil {
return nil, fmt.Errorf("Host distro does not support host architecture: %v", err)
}

...
}
```
in cmd/osbuild-composer/composer.go/(*Composer).InitWeldr

Is cmposer only support same as host distro and host arch?
If I want build  image is centos8, but my host is centos7, fedora or rh, It canot work?
If I want use remote work the arch is aarch64 communicate with compsoer that x86_64, It canot work?

So whether or not same solution for this?
Thanks very much

**Comment by ondrejbudai** [comment]
The latest `main` supports distro cross-building in the weldr API.

Composer cannot be run on CentOS 7, nor it can build its images.

Cross-architecture image building is supported but not in the weldr API, you have to use cloud or koji APIs.

Please, use Github discussions for questions about this project: https://github.com/osbuild/osbuild-composer/discussions/categories/q-a

**Comment by zhangdexin** [comment]
Oh yeah, for centos7, it is a example, I'm a bit silly, hahaha, ignore it.
For distro cross-building
I am in main branch, th code is:
```
	hostDistroName, _, _, err := distro.GetHostDistroName()
	if err != nil {
		return nil, fmt.Errorf("host distro is not supported")
	}
	archName := common.CurrentArch()

	hostDistro := dr.GetDistro(hostDistroName)
	hostArch, err := hostDistro.GetArch(archName)
	if err != nil {
		return nil, fmt.Errorf("Host distro does not support host architecture: %v", err)
	}
```
```distro.GetHostDistroName()``` do cat /etc/os-release content, is host distroname, ```dr.GetDistro(hostDistroName)``` do get distro with host distroname, So? I am sorry.

For discussions, I am sorry, next times I certainly do Q&A in it.

Thank you for reply

**Comment by ondrejbudai** [comment]
Sorry, I don't understand your question. Can you describe to me what you are trying to achieve with osbuild-composer? Thanks!

**Comment by zhangdexin** [comment]
I am sorry, I didn't describe it clearly.
I want to build a image not my host distro, eg. My host is centos8, I want build rh qcow2 in the weldr API.
You said "The latest main supports distro cross-building in the weldr API", but I cant find out.
The previous describe is list the code.

Thank you for reply very much.
