### ISSUE TITLE
CI: Make jobs interruptible 

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#1570]
I believe that there was an effort in the past to make newer CI runs cancel the old ones and it didn't work for some reason. I think I found the reason:  https://docs.gitlab.com/ee/ci/yaml/#interruptible 
It says that by default jobs are not interruptible and we have to set `interruptible: true` to specify if the job can be canceled. I think this should be done after we introduce a scheduled cloud-cleaner or just enable it now for jobs that don't interact with clouds. It will definitely help making the CI run more fluid. Opening this ticket to track this effort and any comments on this.

**Comment by ondrejbudai** [comment]
I think this is now done as much as possible, am I right, @jrusz?

**Comment by jrusz** [comment]
Yeah, it should be set for all jobs https://github.com/osbuild/osbuild-composer/blob/main/.gitlab-ci.yml#L17 but is kinda flaky, I blame the job limits and stuff. Will check it again once we migrate the Gitlab project.
