### ISSUE TITLE
Add the ability to use temporary security credentials for AWS

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#1580]
Currently we use Access keys for AWS everywhere. This is better than user/pass because they can be revoked. However in managed environments users might not have access to generate these, as they do give permanent access to an account.

AWS has support for temporary access tokens: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html. Alongside the access key, it's secret, users need to supply a session token.

If a session token is supplied, composer should use it to access AWS resources.

**Comment by teg** [comment]
Would this be even more convenient: "Using an IAM role to grant permissions to applications running on Amazon EC2 instances - AWS Identity and Access Management" https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html ?

**Comment by ondrejbudai** [comment]
Yeah, this would also be nice to implement. I think that both options have their uses.
