### ISSUE TITLE
CI: timeout while waiting for plugin to start, and terraform errors

### ISSUE THREAD

**Issue by jabia99** [osbuild/osbuild-composer#1598]
I get different results everytime I run the pipeline. One common error is timeout while waiting for plugin to start, just a few moments after the jobs start. some examples:
https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/343796306   - This pipeline ran with just OStree failing (due to an error in the code)
https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/344045264   - In this pipeline I get a lot of these errors, some related to the timeout while waiting for plugin to start. But I also get errors related to terraform.

### Specific errors examples
- **Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.** https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1457975987
- **Error: timeout while waiting for plugin to start**   
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1457975967

**Comment by ondrejbudai** [comment]
We have a beefer runner now and this issue seems to be gone.
