### ISSUE TITLE
cloudapi: Replace `panic`s with 500s

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#1606]
There's still several places where the handlers will panic instead of returning an InternalServerError. Calling a handler shouldn't crash composer.

**Comment by ondrejbudai** [comment]
Note that panic in http handler doesn't actually crash composer. The http server should recover the panicked goroutine and return 500.

**Comment by Gundersanne** [comment]
Oh I didn't know that :)
