### ISSUE TITLE
rhel 9: tests need to be adjusted to work with the new weldr-client

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1630]
In RHEL 9 (and Fedora 34) weldr-client is now shipped instead of composer-cli. It provides the same command (`/usr/bin/composer-cli`) but the output of commands run with `--json` argument is different (see https://github.com/osbuild/weldr-client/issues/9 for example).

The test suite needs to be adjusted to be able to work with the new client. Both base tests and integration tests that use the weldr API are affected, see:

- base test: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1477814546
- aws integration test: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1477814555

**Comment by jrusz** [comment]
Integration tests `aws.sh` and `azure.sh` update merged https://github.com/osbuild/osbuild-composer/pull/1675

More tests that use `composer-cli --json` will need to be updated like all ostree tests, libvirt.sh, filesystem.sh, vmware.sh and regressions tests (if we want to run them on RHEL-9)

**Comment by jrusz** [comment]
Updating `filesystem.sh` in https://github.com/osbuild/osbuild-composer/pull/1745

**Comment by jrusz** [comment]
`ostree.sh` will be updated in https://github.com/osbuild/osbuild-composer/pull/1791
`vmware.sh` was updated in https://github.com/osbuild/osbuild-composer/pull/1749
regression tests were updated in https://github.com/osbuild/osbuild-composer/pull/1748
