### ISSUE TITLE
rhel 9: vmdk and vhd images are not buildable

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1632]
This is a "bug" in qemu-img, see: https://bugzilla.redhat.com/show_bug.cgi?id=1989841

This causes all gcp and azure tests to fail, see:
- https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1477814562
- https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1477814567

**Comment by thozza** [comment]
The "bug" seems to be already VERIFIED and should be fixed in `qemu-kvm-6.0.0-12.el9`

**Comment by ondrejbudai** [comment]
We probably want to generate vhd and vmdk test manifests before we close this issue.

**Comment by thozza** [comment]
Closed via https://github.com/osbuild/osbuild-composer/pull/1707/commits/69c4a7924dc84981b59f8e1d29665478c0f0e442
