### ISSUE TITLE
rhel 9: libvirtd cannot be started in tests

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1635]
Affects the libvirt test and also all ostree tests.

```
🚀 Starting libvirt daemon
Job for libvirtd.service failed because the control process exited with error code.
See "systemctl status libvirtd.service" and "journalctl -xeu libvirtd.service" for details.
```

https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1477814561

**Comment by diaasami** [comment]
Any pointers where to look?

**Comment by ondrejbudai** [comment]
In F34+ and RHEL9, we ship [weldr-client](https://github.com/osbuild/weldr-client/) instead of [composer-cli](https://github.com/weldr/lorax/blob/f33-branch/src/composer/cli/__init__.py). They both provide `/usr/bin/composer-cli` but the json output it slightly different. As we use this output in out test suite, we need to adjust the test suite to support both formats. This PR does something similar for base tests: https://github.com/osbuild/weldr-client/
