### ISSUE TITLE
rhel 9: Regression tests are broken

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1636]
Are we even supposed to be running them on RHEL 9?

See https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1477814548

**Comment by jrusz** [comment]
We decided that we want to run the tests on RHEL-9 as well, assigning to myself.

**Comment by jrusz** [comment]
Fixed in https://github.com/osbuild/osbuild-composer/pull/1748
