### ISSUE TITLE
edge-simplified-installer does not work with default installation device /dev/sda

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#1660]
This bug is to record the test result for https://github.com/osbuild/osbuild-composer/pull/1654, which is still in progress and not ready for merge yet.

**Describe the bug**
I built an edge-simplified-installer image, with default installation device value /dev/sda, but failed to install it with virt-install, error message is no such file or directory of /dev/sda

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
[root@85iso2 workspace]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 Beta (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5 Beta"

 * osbuild-composer version (`rpm -qi osbuild-composer)`
[root@85iso2 workspace]# rpm -qi osbuild-composer
Name        : osbuild-composer
Version     : 31
Release     : 1.20210824gite247229.el8
Architecture: x86_64
Install Date: Mon 23 Aug 2021 10:45:22 PM EDT
Group       : Unspecified
Size        : 17297
License     : ASL 2.0
Signature   : (none)
Source RPM  : osbuild-composer-31-1.20210824gite247229.el8.src.rpm
Build Date  : Mon 23 Aug 2021 10:42:09 PM EDT
Build Host  : 85iso2
Relocations : (not relocatable)
URL         : https://github.com/osbuild/osbuild-composer
Summary     : An image building service based on osbuild
Description :

A service for building customized OS artifacts, such as VM images and OSTree
commits, that uses osbuild under the hood. Besides building images for local
usage, it can also upload images directly to cloud.

It is compatible with composer-cli and cockpit-composer clients.

**To Reproduce**
1. Build an container image and start it in podman. (just as same as before, won't go to details here)
[root@85iso2 workspace]# composer-cli blueprints show container 
name = "container"
description = "A base rhel-edge container image"
version = "0.0.1"
modules = []
groups = []
distro = ""

[[packages]]
name = "python36"
version = "*"

[customizations]
[customizations.kernel]
name = "kernel-rt"
append = ""

[[customizations.user]]
name = "admin"
description = "Administrator account"
password = "$6$GRmb7S0p8vsYmXzH$o0E020S.9JQGaHkszoog4ha4AQVs3sk8q0DvLjSMxoxHBKnB2FBXGQ/OkwZQfW/76ktHd0NX5nls2LPxPuUdl."
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC61wMCjOSHwbVb4VfVyl5sn497qW4PsdQ7Ty7aD6wDNZ/QjjULkDV/yW5WjDlDQ7UqFH0Sr7vywjqDizUAqK7zM5FsUKsUXWHWwg/ehKg8j9xKcMv11AkFoUoujtfAujnKODkk58XSA9whPr7qcw3vPrmog680pnMSzf9LC7J6kXfs6lkoKfBh9VnlxusCrw2yg0qI1fHAZBLPx7mW6+me71QZsS6sVz8v8KXyrXsKTdnF50FjzHcK9HXDBtSJS5wA3fkcRYymJe0o6WMWNdgSRVpoSiWaHHmFgdMUJaYoCfhXzyl7LtNb3Q+Sveg+tJK7JaRXBLMUllOlJ6ll5Hod root@localhost"
home = "/home/admin/"
groups = ["wheel"]

2. Create a blueprint for edge-simplified-installer. I didn't specify the installation_device here, because it will use the default value  /dev/sda if no installation_device specified. Please see https://github.com/gicmo/osbuild-composer/blob/rhel85/edge-simplified-installer/internal/blueprint/customizations.go#L221

[root@85iso2 workspace]# composer-cli blueprints show installer
name = "installer"
description = "A rhel-edge simplified-installer image"
version = "0.0.1"
packages = []
modules = []
groups = []
distro = ""

3. Build edge-simplified-installer image, 
composer-cli compose start-ostree installer edge-simplified-installer --ref "$OSTREE_REF" --url "${STAGE_REPO_URL}/"

4. Download this image and try to install it with virt-install
sudo virt-install --name="edge-uefi" --disk path="${LIBVIRT_IMAGE_PATH}",format=qcow2 --ram 3072 --vcpus 2 --network network=integration,mac=34:49:22:B0:83:31 --os-type linux --os-variant ${OS_VARIANT} --cdrom "/var/lib/libvirt/images/${ISO_FILENAME}" --boot uefi,loader_ro=yes,loader_type=pflash,nvram_template=/usr/share/edk2/ovmf/OVMF_VARS.fd,loader_secure=no --nographics --wait=-1 --noreboot

5. I see error messages in the installation console, it said no such file or directory of /dev/sda.
[FAILED] Failed to mount /run/media/iso.
See 'systemctl status run-media-iso.mount' for details.
         Starting CoreOS Installer...
         Stopping Device-Mapper Multipath Device Controller...
[  OK  ] Started Reload Configuration from the Real Root.
[  OK  ] Reached target Initrd File Systems.
[  OK  ] Stopped Device-Mapper Multipath Device Controller.
[    6.016677] coreos-installer-service[812]: coreos-installer install /dev/sda --image-file /run/media/iso/disk.img.xz --insecure
[    6.025566] coreos-installer-service[812]: Error: parsing arguments
[    6.025638] coreos-installer-service[812]: Caused by:
[    6.029226] coreos-installer-service[812]:     0: checking whether /dev/sda is an IBM DASD disk
[    6.029263] coreos-installer-service[812]:     1: getting absolute path to /dev/sda
[    6.029280] coreos-installer-service[812]:     2: No such file or directory (os error 2)
[FAILED] Failed to start CoreOS Installer.
See 'systemctl status coreos-installer.service' for details.

6. To see the full log of virt-install and osbuild-worker, please see http://pastebin.test.redhat.com/988863

**Expected behavior**
Should be able to install edge-simplified-installer image to device

**Additional context**

**Comment by gicmo** [comment]
I think it is fine that it does not work by default since we cannot actually know the target device, although maybe we should make it work with the default libvirt device. Is it `/dev/vda`?

**Comment by teg** [comment]
> I think it is fine that it does not work by default since we cannot actually know the target device, although maybe we should make it work with the default libvirt device. Is it `/dev/vda`?

Should we just make the field mandatory?

**Comment by runcom** [comment]
> Should we just make the field mandatory?

this might be the right thing to do - we're not going to guess the device for sure so being mandatory sounds about right
