### ISSUE TITLE
edge-simplified-installer does not support blueprint customizations

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#1661]
This bug is to record the test result for https://github.com/osbuild/osbuild-composer/pull/1654, which is still in progress and not ready for merge yet.

**Describe the bug**
Specify installation-device in blueprint, and then build edge-simplified-installer image, it reports error "boot ISO image type "edge-simplified-installer" does not support blueprint customizations"

**Environment**
As same as https://github.com/osbuild/osbuild-composer/issues/1660

**To Reproduce**
1. create a blueprint, specify installation-device
[root@85iso2 workspace]# composer-cli blueprints show installerdevvda 
name = "installerdevvda"
description = "A rhel-edge simplified-installer image"
version = "0.0.1"
packages = []
modules = []
groups = []
distro = ""

[customizations]
installation_device = "/dev/vda"

2. build edge-simplified-installer but failed.
[root@85iso2 workspace]# composer-cli compose start-ostree installerdevvda edge-simplified-installer --ref "$OSTREE_REF" --url "${STAGE_REPO_URL}/"
2021-08-24 00:26:32,402: failed to create osbuild manifest: boot ISO image type "edge-simplified-installer" does not support blueprint customizations

**Expected behavior**
User should be able to specify the installation device and build edge-simplified-installer image

**Additional context**

**Comment by gicmo** [comment]
This should be fixed in the latest version of  #1654

**Comment by yih-redhat** [comment]
Verified in latest version of #1654 , fixed.
Closing this bug.
