### ISSUE TITLE
[Edge] greenboot journal log in edge-simplified-installer and edge-raw-image is different from edge-installer

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#1701]
**Describe the bug**
Currently the greenboot journal log in edge-simplified-installer and edge-raw-image is different from edge-installer. Need to track down this.

For edge-installer:
              - "'Script \\'00_required_scripts_start.sh\\' SUCCESS' in result_greenboot_log.stdout"
              - "'Script \\'00_wanted_scripts_start.sh\\' SUCCESS' in result_greenboot_log.stdout"
              - "'greenboot Health Checks Runner' in result_greenboot_log.stdout"
              - "'Reached target Boot Completion Check' in result_greenboot_log.stdout"
              - "'Mark boot as successful in grubenv' in result_greenboot_log.stdout"
              - "'Boot Status is GREEN - Health Check SUCCESS' in result_greenboot_log.stdout"
              - "'greenboot MotD Generator' in result_greenboot_log.stdout"

For edge-simplified-installer and edge-raw-image:
              - "'Script \\'00_required_scripts_start.sh\\' SUCCESS' in result_greenboot_log.stdout"
              - "'Script \\'00_wanted_scripts_start.sh\\' SUCCESS' in result_greenboot_log.stdout"
              - "'Boot Status is GREEN - Health Check SUCCESS' in result_greenboot_log.stdout"            
            
This does not impact the greenboot functions, actually greenboot works as expected on all edge images. Just need to figure out why, filing this issue to track the work.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 * osbuild-composer version (`rpm -qi osbuild-composer)`

**To Reproduce**
 * *for example starting osbuild-composer.service or running composer-cli command, don't forget to include all configuration files you created*

**Expected behavior**

**Additional context**

**Comment by gicmo** [comment]
I think the reason could be the different kernel flags used when we deploy the ostree: https://github.com/osbuild/osbuild-composer/blob/63fe1c4c8300633c2cf63176e069f0d9858cbaf4/internal/distro/rhel85/pipelines.go#L1104-L1105

Maybe @runcom or @nullr0ute could confirm that those are correct? (I used those in some osbuild manifests to debug boot issues).
