### ISSUE TITLE
ci/tests: ostree tests take a long time and slow down the whole CI

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#1721]
I've started to notice that the last job that finished in a pipeline is almost always New OSTree job as it seems to be able to easily run for 90 minutes before finished.. Now new ostree tests stared appearing like the Raw OSTree and that also seems to take at least an hour. I've been wondering how to speed this up since it's causing a lot of CI errors lately because we're limited at how many pipelines can run at the same time. Would a more powerful machine in Openstack speed it up? Also increasing the runner limits would probably help as well... Any thoughts anyone?

**Comment by teg** [comment]
Could we split these cases into separate scripts and run them in parallel? @henrywang @yih-redhat @achilleas-k ?

**Comment by achilleas-k** [comment]
I think there's not that much we can do in the scripts, at least not the way they work now.  The edge installer tests for instance need the two-stage build process: edge-container and then an installer.  The installer build alone is rather long.  We might be able to deduplicate the commit/container build job and share it between installer tests.  I think we can get away with having the same edge-commit for all..?

The `New OSTree` job is the longest because it runs three builds:
- edge-container
- edge-installer
- second edge-container for upgrade test

There's also the time required to run the installer for each of these.

**Comment by henrywang** [comment]
We have to build `edge-container` twice:
1. for `edge-installer`
2. for upgrade

Here's a example of `ostree-ng.sh` takes time:
Almost start from [srp 31 16:33:36](https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1550683725#L2623)
End at [2021/08/31 17:55:21](https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1550683725#L7554)
Is 1 hour and 22 minutes acceptable?

**Comment by jrusz** [comment]
I did a little experimenting and tried to run the `ostree-ng.sh` test on a more powerful machine in Openstack and it seems to help with the time the test takes:
```
60m58.078s on ci.nested.virt.m1.large
118m43.803s on ci.nested.virt.m1.medium
101m18.215s on ci.nested.virt.m1.medium
```

I ran it on the medium twice because the first time it seemed too long, it doesn't take that long in the CI I believe... I would propose to try changing the flavors and increase the max runners again, I'm not sure what's the situation now with https://github.com/osbuild/osbuild-composer/pull/1732 getting merged though.

**Comment by ondrejbudai** [comment]
#1732 removed the need for maxRunners in `gitlab-ci-terraform`.

**Comment by teg** [comment]
That's a big difference! @ondrejbudai do we have the option of upgrading our machines (for this) from `medium` to `large`?

**Comment by ondrejbudai** [comment]
Yeah, we just need to decide whether we want to run everything on the bigger machines, or just the ng ostree test. Note that this flavor eats double the quota so we should be careful.

**Comment by teg** [comment]
If it is not too much work, I would enable this only on the `ostree-ng` tests, as these are giving us the biggest problems now. Would it be worthwhile increasing our quotas, or is that not really possible (yet)?

**Comment by jrusz** [comment]
IMO what we could do is create a new runner definition in gitlab-ci-terraform repository by just copying the openstack/rhel-8.5 definition and just changing the flavor to the larger machine and reflecting that in the name of the runner and then just update the terraform sha and gitlab-ci.yml file here... I'm happy to that if you agree with this, I would consider moving `ostree-simplified-installer.sh` as well though as that seems to be the second longest running test.

Some of the latest `ostree-ng` runs:
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1569429890
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1569455276

Some of the latest `ostree-simlified-installer' runs:
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1569429898
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1569455279

**Comment by ondrejbudai** [comment]
Sounds like a plan!

**Comment by jrusz** [comment]
I think it helped:
`ostree-ng`
current: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1572101335 ~89 minutes
new: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1571727312 ~61 minutes

`ostree-simplified-installer` (got updated recently and takes longer than before) 
current: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1572101342 ~88 minutes
new: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1571727314 ~ 64 minutes

PR with change: https://github.com/osbuild/osbuild-composer/pull/1751

**Comment by ondrejbudai** [comment]
Merged, thanks for the research!
