### ISSUE TITLE
cloudapi: Verify that ComposeImage returns 201

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#1734]
Check status code in the api integration test explicitly as well. It should be 201.

**Comment by anujkmaurya** [comment]
Can I work on it? Can you point me to the integration test directory?

**Comment by Gundersanne** [comment]
Normally sure, but it seems this issue is stale, and actually got fixed in https://github.com/osbuild/osbuild-composer/pull/1883 :) Closing it.

**Comment by Gundersanne** [comment]
And all the integration tests are under test/cases/*. In this case it was the api.sh tests.
