### ISSUE TITLE
RHEL-9 ostree.sh test - Failed to start Create System Users

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#1763]
**Describe the bug**
During the boot the service fails. I was able to log in via root account and found this in the journal:
```
rs[615]: /etc/gshadow: Group "adm" already exists.
rs[615]: Failed to write files: File exists
stemd-sysusers.service: Main process exited, code=exited, status=1/FAILURE
stemd-sysusers.service: Failed with result 'exit-code'.
iled to start Create System Users.
```
because of this failure more services fail because they don't have the necessary users or groups created.

**Environment**
 * rhel-guest-image-9.0-20210818.2.x86_86
 * osbuild-composer-33-1.20210908gitb8ad702.el9.x86_64
 * Used osbuild-composer from this: http://osbuild-composer-repos.s3.amazonaws.com/osbuild-composer/rhel-9.0/x86_64/b8ad702ee7ea3f79ad64b8d6b8b56983335cc2c9/

**To Reproduce**
Just run the test on the RHEL-9 machine with slight modifications for `weldr-client` where the `--json` response is different.

**Expected behavior**
Machine boots without problems and test passes

**Comment by gicmo** [comment]
This is because the `nss-altfiles` package is missing and thus the user database in `/usr/lib` is not available:

From @henrywang's recent test setup:
```
[admin@vm etc]$ rpm -qi nss-altfiles
package nss-altfiles is not installed
```
