### ISSUE TITLE
dnf-json: Always expire metadata 

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#1772]
https://github.com/osbuild/osbuild-composer/blob/main/dnf-json#L42-L47 

If no `metadata_expire` is configured, we never expire the metadata. In case it isn't configured, always expire to make sure any changes are picked up, the rpmmd cache could get very old otherwise.

**Comment by teg** [comment]
@bcl mentioned that this might slow things down, we should verify the effect in practice.

**Comment by Gundersanne** [comment]
The default is 20s, got addressed in https://github.com/osbuild/osbuild-composer/pull/1867
