### ISSUE TITLE
Copy reworked package sets from RHEL 8.5 to RHEL 9.0

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#1779]
The way package sets are "calculated" and cascade from _image type_ to _architecture_ to _distro_ changed in RHEL 8.5 (see #1667 and specifically https://github.com/osbuild/osbuild-composer/pull/1667/commits/acf9df81250205596a69d9e72dd4681b596b48c4).
This also fixed the package sets more generally.

We should copy the package set handling to RHEL 9.0 as well, with the fixes that were made.  We should also pay attention to any existing fixes and necessary changes made to packages in RHEL 9.0 already and reconcile those.

**Comment by teg** [comment]
Agreed, though this is for RHEL9-GA, not RHEL9-Beta, right?

**Comment by achilleas-k** [comment]
Right now we have issues with the package sets for the edge-installer (#1744).  We can work around not having the full package set merge logic reworked by just adding/fixing the package sets and do it later.

I guess the priority should be not having regressions in image types in 9-beta compared to 8.5?  The internals we can change later.

**Comment by ondrejbudai** [comment]
Tracked also in COMPOSER-1138

**Comment by achilleas-k** [comment]
Done in #1949
