### ISSUE TITLE
Weldr status always reports "devel" build 

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#1788]
## The issue
https://github.com/osbuild/osbuild-composer/blob/ca2dc71eea44d104d0943bad024e81cb229ee210/internal/weldr/api.go#L564

The return value is hardcoded so it reports "devel" regardless the build environment. This looks odd when we are shipping "devel" builds in Fedora and RHEL.

## Proposed solution
Modify spec file to detect the build environment and report "prod" if it was build in Koji or Brew.

**Comment by bcl** [comment]
> Modify spec file to detect the build environment and report "prod" if it was build in Koji or Brew.

This was actually meant to be used to report the build version, not just devel/prod. devel was a placeholder for running from git. In lorax-composer it was overridden by the build which wrote the spec's version-release to a file that was included at runtime so this should just be changed to return the value discussed in #1674

**Comment by msehnout** [comment]
> > Modify spec file to detect the build environment and report "prod" if it was build in Koji or Brew.
> 
> This was actually meant to be used to report the build version, not just devel/prod. devel was a placeholder for running from git. In lorax-composer it was overridden by the build which wrote the spec's version-release to a file that was included at runtime so this should just be changed to return the value discussed in #1674

Ah nice, that would actually make things much simpler. WDYT @thozza @teg @ondrejbudai  ?

**Comment by ondrejbudai** [comment]
SGTM!

**Comment by thozza** [comment]
I fully agree.

**Comment by msehnout** [comment]
Perfect, in that case we don't need to care about the devel/prod hacks.
