### ISSUE TITLE
RHEL-8.4 test manifests use non-existing repos

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#1793]
It appears we're going to have to update also RHEL-8.4 test manifests https://gitlab.com/osbuild/ci/osbuild/-/jobs/1597589962

Also since it's GA and registered I'm wondering, maybe it should be using cdn repos?

**Comment by jrusz** [comment]
Apparenlty `sed -i` is not enough as a workaround so the manifests will indeed have to be regenerated, considering that previous `rhel-8` runners used *r8.3* snapshot I assume we need some sort of *r8.4* snapshot which currently doesn't seem to exist. @ondrejbudai can you help me with what needs to be done here? I image we needs this, correct me if I'm wrong:

1. Create the rpmrepo snapshot with released content for RHEL-8.4
2. Regenerate all 8.4 test manifests and merge them
3. Make necessary updates in osbuild repo

Could you please help me with this or give me some guidance so that I can do it?

**Comment by ondrejbudai** [comment]
Yep, all of these steps are needed, everything should be documented here: https://github.com/osbuild/rpmrepo @thozza should also be able to help.
