### ISSUE TITLE
Remove RuntimeDirectory from osbuild-composer.service

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#18]
This line
https://github.com/osbuild/osbuild-composer/blob/859bc0ad2ed8814fa7ca42c79f93e4b22a09d87f/distribution/osbuild-composer.service#L9

can be safely removed if `/run/osbuild-composer` and `/run/weldr` contain only the sockets from `osbuild-composer.socket`

Is it the case @larskarlitski, @teg ?

**Comment by larskarlitski** [comment]
Discussed this in chat. `RuntimeDirectory` can be removed for now.
