### ISSUE TITLE
Duplicate Filemount Error

### ISSUE THREAD

**Issue by kingsleyzissou** [osbuild/osbuild-composer#1813]
When trying to add custom mountpoints to a filesystem in osbuild composer, if two mountpoint have the same suffix,
osbuild throws a duplicate filemount error. For example, setting `/tmp` and `/var/tmp` results in the following:

```sh
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]: Traceback (most recent call last):
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:   File "/usr/bin/osbuild", line 11, in >
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:     load_entry_point('osbuild==35', 'co)
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:   File "/usr/lib/python3.6/site-packagei
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:     manifest = fmt.load(desc, index)
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:   File "/usr/lib/python3.6/site-packaged
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:     load_pipeline(desc, index, manifest)
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:   File "/usr/lib/python3.6/site-packagee
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:     load_stage(desc, index, pl, manifes)
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:   File "/usr/lib/python3.6/site-packagee
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:     load_mount(mount, index, stage)
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:   File "/usr/lib/python3.6/site-packaget
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]:     raise ValueError(f"Duplicated mount)
Sep 20 13:46:53 rhel85-rhel85-vm osbuild-worker[2297]: ValueError: Duplicated mount 'tmp'
```

**Comment by kingsleyzissou** [comment]
The issue is that we are setting the fstab name to the path's suffix, so there would be an error with `/tmp` and `/var/tmp`. This is being set in the `stage_options` of the distro definitions for `rhel85` & `rhel90`:
https://github.com/osbuild/osbuild-composer/blob/cc54c4deeed24f459341ae3e18a56924e510ace1/internal/distro/rhel85/stage_options.go#L429

**Comment by thozza** [comment]
@kingsleyzissou is this issue still relevant? I'm asking because it has label "waiting for 8.6", but that is probably not the case any more 🙂

**Comment by kingsleyzissou** [comment]
@thozza I should remove the label :), but I don't think it has been fixed yet. I can have a look at that today maybe

**Comment by thozza** [comment]
@kingsleyzissou thanks for the info. Nevertheless, there is no need to prioritize this because of my comment... 😉

**Comment by gicmo** [comment]
We have to redo some of this anyway so maybe dont prioritise it just yet.

**Comment by kingsleyzissou** [comment]
No worries, I saw https://github.com/osbuild/osbuild-composer/pull/2141 hadn't landed yet and I thought that should come first.

**Comment by gicmo** [comment]
Should now be fixed via 2141
