### ISSUE TITLE
cloudapi/v2: Make aws buckets configurable

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#1855]
blocked on #1841 

---

A single bucket should do for now, as cross-region snapshot import is possible.

**Comment by teg** [comment]
Just a note: even though the credentials should live in the worker, the bucket configuration should probably live in composer for when we split the uploading and registering into separate jobs.

**Comment by Gundersanne** [comment]
Agreed. #1841 just sets the buckets to image-builder.service.region and expects it to be there.

**Comment by Gundersanne** [comment]
So you can import-snapshot just fine cross-region, this means really that all this should be is a bucket name.
