### ISSUE TITLE
guest image configs converted from kickstart to osbuild format

### ISSUE THREAD

**Issue by jgiardino** [osbuild/osbuild-composer#190]
In order to support the creation of a guest image, we need the details of the guest image defined in a format that can be consumed by osbuild. These details are currently defined in a kickstart (links to existing kickstart files are provided in this [google doc](https://docs.google.com/document/d/1naKxHgXjpGNvmT1Iw8mVEGd0B6UiOZeEmVO7jjMVddU/edit#bookmark=id.4zacegvam3p8)).

**Comment by major** [comment]
Tied to internal issue COMPOSER-479.

**Comment by ondrejbudai** [comment]
Implemented!
