### ISSUE TITLE
Remote Workers

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#194]
Allow workers to run remotely. I.e., on separate hosts from composer itself.

Acceptance criteria:

- [ ] In composer, add support for the jobqueue socket to be a TCP socket rather than UDS
- [ ] In the worker, add support for configuring the composer hostname to connect to rather than UDS
- [ ] Add support for workers to authenticate themselves to composer using SSL Client Certificates, make this mandatory for the TCP socket

Optional:
- [ ] Split the worker into an rpm subpackage of composer so they can be installed independently.

**Comment by major** [comment]
When this work is done, please add a note to *COMPOSER-495* in JIRA so we can get osbuild-composer running in a container. :smile:

**Comment by major** [comment]
@ondrejbudai @teg If there are any docs or quick start instructions for this feature, I'll be happy to update the deployment playbooks and test it out. :)

**Comment by teg** [comment]
This was fixed by PR #198

**Comment by teg** [comment]
@major see https://github.com/osbuild/osbuild-composer/commit/820d23fd9d216a93cde3b9964197506867896407 for an intro. We may want to put this somewhere more permanent.
