### ISSUE TITLE
Image type names should reflect the intended usage, not file format

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#200]
This issue was derived from #193 

For example here:
https://github.com/osbuild/osbuild-composer/blob/master/internal/distro/fedora30/distro.go#L220
we refer to the image type as "vhd" even though it is crafted specifically for Azure cloud.

We should rename these to better reflect what they represent, but there might be an issue with backwards compatibility with lorax-composer ( @ondrejbudai )

**Comment by teg** [comment]
We went away from this, and will keep current names as they are. We may introduce new ones in the future. And we may clarify what is meant by the existing ones. But no need to change the strings in the API.
