### ISSUE TITLE
awsupload: Investigate retry mechanism for s3

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#2034]
We've seen some s3 500 errors in the service when uploading artifacts; an official mitigation according to aws https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/ is a retry mechanism.

**Comment by Gundersanne** [comment]
Log sample:
```
WARNING: Upload failed: /1795502318/repo/objects/bd/a92b6b24017579286d42873977ebac27ed0adb5489a837806b17d6516b9a13.filez (500 (InternalError): We encountered an internal error. Please try again.)
```

**Comment by achilleas-k** [comment]
I think this is an osbuild issue.  The `org.osbuild.ostree` source should do retries on the `ostree pull` command.
