### ISSUE TITLE
CI: provisioning of aws runners ends with error "capacity-not-available"

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#2056]
Getting errors about spot instances being unavailable even though we have set to wait for fulfillment in our terraform settings https://github.com/osbuild/gitlab-ci-terraform/blob/main/aws/_base/main.tf#L19  

```
Error: Error while waiting for spot request ({
│   CreateTime: 2021-11-23 14:13:24 +0000 UTC,
│   InstanceInterruptionBehavior: "terminate",
│   LaunchSpecification: {
│     BlockDeviceMappings: [{
│         DeviceName: "/dev/sda1",
│         Ebs: {
│           DeleteOnTermination: true,
│           VolumeSize: 40
│         }
│       }],
│     EbsOptimized: false,
│     IamInstanceProfile: {
│       Name: ""
│     },
│     ImageId: "ami-01efb339f953fdf36",
│     InstanceType: "c5.large",
│     KeyName: "gitlab-runner",
│     Monitoring: {
│       Enabled: false
│     },
│     NetworkInterfaces: [{
│         DeviceIndex: 0,
│         SubnetId: "subnet-0c016a02"
│       }],
│     Placement: {
│       AvailabilityZone: "us-east-1f",
│       GroupName: ""
│     },
│     SecurityGroups: [{
│         GroupName: "default"
│       }]
│   },
│   ProductDescription: "Linux/UNIX",
│   SpotInstanceRequestId: "sir-12hyb2zk",
│   SpotPrice: "0.085000",
│   State: "open",
│   Status: {
│     Code: "pending-evaluation",
│     Message: "Your Spot request has been submitted for review, and is pending evaluation.",
│     UpdateTime: 2021-11-23 14:13:24 +0000 UTC
│   },
│   Tags: [{
│       Key: "Name",
│       Value: "fedora-33-x86_64"
│     }],
│   Type: "one-time"
│ }) to resolve: unexpected state 'capacity-not-available', wanted target 'fulfilled'. last error: %!s(<nil>)
│ 
│   with module.aws.aws_spot_instance_request.runner,
│   on ../_base/main.tf line 15, in resource "aws_spot_instance_request" "runner":
│   15: resource "aws_spot_instance_request" "runner" {
```
example job: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1811485538

It happened in the past but got resolved by itself so I didn't open an issue but now it happens again and fairly often, 5 failed jobs in rpmbuild stage at this time and CI is under very little load. Is this related to the region? Can we use more regions to request the runners to work around this? 

I also don't understand why won't terraform just wait for the resource to get allocated, in their documentation it says that it will wait for 10 minutes by default for the request to get fulfilled.

**Comment by ondrejbudai** [comment]
I think we should switch to spot fleets because they allow users to specify more instance types. If AWS is temporarily out of a certain instance type, we could just use a different one.

For start, we can use the following types: `c5.large`, `c5d.large`, `c5a.large`, `c5ad.large`.

If we need more, we can also try `m5`, `m6i` and `c6i`.

**Comment by jrusz** [comment]
Runners were converted to use spot fleets some time ago in https://github.com/osbuild/gitlab-ci-terraform/pull/63
