### ISSUE TITLE
distros: merge blueprint & os package set before depsolving instead of after?

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#2125]
Certain packages (for instance [osbuild.spec](https://github.com/osbuild/osbuild/blob/main/osbuild.spec#L39)) include conditional requires. During depsolving dnf will look for a certain package which might be part of the os package set, but not the blueprint one, and depsolving will fail.

To reproduce on rhel85 & above (any distro which splits the depsolving of blueprint and os), create a blueprint with "osbuild", but not with any package that unconditionally requires "selinux-policy-targeted" (which is then part of the os package set but not the blueprint one).

To fix include "selinux-policy-targeted" in the blueprint.

**Comment by Gundersanne** [comment]
An option is to circumvent the "installing a package which is in the ospkgs excludes" problem: merge the packgesets in ImageTypes.PackageSets(), and remove any package in the blueprint pkgs from the ospkgs.Excludes.

**Comment by teg** [comment]
We discussed disabling weak dependencies and combining the two depsolves into one again. Then we could drop the excludes, I think.

**Comment by achilleas-k** [comment]
Is disabling weak deps an option?  I thought we couldn't do that.  If that's straightforward, I think it solves all our problems.

**Comment by teg** [comment]
We should be able to disable weak dependencies and then add back in some packages to compensate. I think this should be a fairly high priority bug to fix.

**Comment by Gundersanne** [comment]
If we disable weak deps, I think we also need to abandon dnf groups. But if we do those two, we can drop excludes.

**Comment by teg** [comment]
> If we disable weak deps, I think we also need to abandon dnf groups. But if we do those two, we can drop excludes.

I'm not familiar enough: why?

**Comment by Gundersanne** [comment]
> > If we disable weak deps, I think we also need to abandon dnf groups. But if we do those two, we can drop excludes.
> 
> I'm not familiar enough: why?

The core group includes things like wifi firmware, we can't have those in ec2 images for instance. So now we explicitly exclude these. If however we abandon the core group entirely and just install what we actually need from the group, we don't need the excludes.

**Comment by thozza** [comment]
I really think that we should not consider disabling weak dependencies when dep-solving, because this behavior would be different than what is the default when installing package on RHEL using `dnf`.

**Comment by Gundersanne** [comment]
> I really think that we should not consider disabling weak dependencies when dep-solving, because this behavior would be different than what is the default when installing package on RHEL using `dnf`.
> 
> I think that the solution that we should aim for is to dep-solve blueprint packages as if they were installed on top of the os package set. Dep-solving them as if they were installed on an empty system can lead to various types of unexpected behavior.

Sadly this is pretty much impossible using the dnf python api, as we can't manipulate the "sack" in that way https://dnf.readthedocs.io/en/latest/api_sack.html :/ The only way I could think of to do that currently is

> So one way would be 2 depsolves, always combined. From the first depsolve get the dependency tree (somehow) for the blueprint packages, remove any of the packages in that tree from the Excludes and depsolve properly.

**Comment by teg** [comment]
I liked the idea from @thozza of reusing the state of the first depsolve for the second one (in some way). However, unless we can get that to work (I could not), then I think we need to pursue another solution, and I think the next best thing is disabling weak dependencies.

If we could follow what we would get by doing two calls to `dnf install`, that would be very intuitive, but I think it is not the end of the world if we don't. As long as our alternative behaviour is as intuitive as possible (and the base images with empty blueprints are the same). I think removing packages from the request to try to get the right exclude behaviour is very counterintuitive (and might not even work, I think).

If we say "weak dependencies are opt-in and all packages are installed as part of one transaction", that is pretty straight-forward to understand I think. Importantly, the current behaviour is known to be broken, so we really need to pick a solution...

**Comment by thozza** [comment]
I tested depsolving two transactions in a row and I think that we can get out if it exactly what we want…

A simple script showcasing what happens - https://gist.github.com/thozza/951cf9d955535eed6e5d1a9cb78d8761

We can depsolve the base packages with excludes and then just add e.g. `ipa-client` to the install spec and depsolve again. The previously excluded packages don’t get pulled in and we get installable package set including the base package set and the additional BP packages on top of it.

**Comment by thozza** [comment]
Fixed via #2568
