### ISSUE TITLE
Support specifying OSTree Parent and URL

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#2131]
## Current state

There are three OSTree parameters that can be specified during a compose request:
- **URL**: The location of an ostree repository
- **Ref**: The reference to use for the new or the existing commit
- **Parent**: The commit ID or ref for the parent commit

The **Ref** is always optional.  When not specified, it defaults to the standard ostree ref for the distro version, e.g., `rhel/8/x86_64/edge`.
When the **URL** is specified, it is used to determine the **parent** commit ID, by resolving `$URL/refs/heads/$Ref`.
The **parent** commit ID is then used to build the new commit as a child commit.

Currently, if both the **URL** and the **parent** are specified, it is considered an error.  The reasoning was that users could either specify the **parent** commit ID directly or the **URL** from which to fetch it, so specifying both didn't make sense.
This is all done in the following part of the code:
https://github.com/osbuild/osbuild-composer/blob/10f34de88b472893360f222253368c234d2de5a1/internal/cloudapi/v2/v2.go#L208-L226

The code above is for the Cloud API, but the Weldr API follows the same logic.

---

## New requirements

Several changes have made it necessary to fetch the **parent** commit during a build.  One change is the need to determine the group IDs for the existing commit to avoid changing GIDs in the upgrade.  It's also become necessary to be able to specify a different reference for the existing OS/repository and the new commit (for example, when upgrading from RHEL 8 to RHEL 9).

The new rules for ostree parameters should (probably) be as follows:
- **Ref** only: defines the **Ref** of the commit to be created.  No parent will be used or fetched and a new commit will be created without a parent.
- **URL** only: works the same as **URL** + **Ref** (see next item).  The **Ref** takes the default value for the distro version.
- **URL** + **Ref**: pulls the parent commit as `$URL/refs/heads/$Ref` and creates a new upgrade commit with the same **Ref**.
- **URL** + **Parent**: pulls the parent commit as `$URL/refs/heads/$Parent` and creates a new upgrade commit with the default distro version **Ref**.
- **URL** + **Ref** + **Parent**: pulls the parent commit as `$URL/refs/heads/$Parent` and creates the new commit as **Ref**, which might be different from the parent ref (e.g., for distro upgrades).
- **Parent** without **URL**: this is an error since there's nothing we can do with the parent ref if there's no URL to query.

---

## Edge installers

Things are a little different with installers.  The purpose of an installer is to pull the commit specified by `$URL/refs/heads/$Ref` and embed it in the artifact.  For `edge-installer`, `edge-raw-image`, and `edge-simplified-installer`, we should **require** both **URL** and **Ref**, but either ignore **Parent** or produce an error when it's supplied.

**Comment by gicmo** [comment]
One note: the use case number 5, that is, "URL + Ref + Parent: pulls the parent commit as $URL/refs/heads/$Parent and creates the new commit as *Ref*, which might be different from the parent ref (e.g., for distro upgrades)." is currently blocking us from supporting rebases, i.e. where the parent is `rhel/8/...` and the ref is `rhel/9/...` since currently the parent is derived from *URL* and *Ref* (by resolving the latter) and specifying it is an error (as pointed out. But this is precisely needed for the rebase case.

**Comment by mrguitar** [comment]
Brilliant work on this. I think this is a perfect outcome and keeping it out of the blueprint has a lot of advantages. Amazing. Thanks!

**Comment by achilleas-k** [comment]
Done in #2201.
