### ISSUE TITLE
Reference koji ID in status response in RCM API

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#217]
https://github.com/osbuild/osbuild-composer/blob/b81dc53442cec36df89b0c2ba933b115591e07ee/internal/rcm/api.go#L181

When compose is ready, it would be nice if we could return koji id or link to koji task to make the RCM API user friendly.

**Comment by teg** [comment]
The RCM API will be replaced by the Koji API, where this will be done instead.
