### ISSUE TITLE
RHEL 9.0: use `C.UTF-8` for images that only have `glibc-minimal-langpack`

### ISSUE THREAD

**Issue by gicmo** [osbuild/osbuild-composer#2206]
We currently set `en_US.UTF-8` for all images:
https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/distro.go#L60

According to the glib team, if `glibc-minimal-langpack` is installed, only `C.UTF-8` is available.

The following images should be affected:
  * [qcow2](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L400)
  * [edge commit](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L693)
 * [bare metal](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L824)
 * [edge simplified installer](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L1119)

Images that install `langpacks-en`:
 * [vhd](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L460)
 * [vmdk](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L509)
 * [openstack](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L546)
 * [ec2](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L597)
 * [anacond](https://github.com/osbuild/osbuild-composer/blob/1c2c97c90023edb699b4f98d39ba5a275df1fcf2/internal/distro/rhel90/package_sets.go#L939)

I took this info from the package sets. Maybe need to verify it by looking at the fully dep-solved package list.

Downstream bug: [rhbz#2000878](https://bugzilla.redhat.com/show_bug.cgi?id=2000878)

**Comment by teg** [comment]
Should we not aim for uniformity and just go `C.UTF-8` everywhere?

**Comment by gicmo** [comment]
> Should we not aim for uniformity and just go `C.UTF-8` everywhere?

That was my first intuition as well, but it is quite late to change the default. But I am torn.

**Comment by gicmo** [comment]
If we do set `C.UTF-8` everywhere we should probably also remove `langpacks-en` from the images.

**Comment by gicmo** [comment]
One other note: if a users sets a locale in the customisation, do we install the corresponding langpack? Or is that up to the user?

**Comment by teg** [comment]
We should. But I don't recall if that's still a TODO.

**Comment by thozza** [comment]
Affected image types:
```bash
$ grep  -L "langpack-en" test/data/manifests/rhel_90-x86_64*
test/data/manifests/rhel_90-x86_64-edge_commit-boot.json
test/data/manifests/rhel_90-x86_64-edge_commit_rt-boot.json
test/data/manifests/rhel_90-x86_64-edge_container-boot.json
test/data/manifests/rhel_90-x86_64-image_installer-boot.json
test/data/manifests/rhel_90-x86_64-qcow2-boot.json
test/data/manifests/rhel_90-x86_64-qcow2_customize-boot.json
test/data/manifests/rhel_90-x86_64-tar-boot.json
```
