### ISSUE TITLE
Koji client should use retries

### ISSUE THREAD

**Issue by tkopecek** [osbuild/osbuild-composer#2335]
**Describe the bug**
As connections are flaky it makes sense to retry xmlrpc calls in case of network error. ``internal/upload/koji/koji.go`` use simple ``http.RoundTripper`` transport instead of something with retry/backoff policy (according to my reading, correct me if I'm wrong). 

**Expected behavior**
Even temporary unavailability of koji server shouldn't fail the import or similar tasks.

**Additional context**
There are tens of thousands of connections (just chunked upload of results will cause tons of calls) so even a very small fraction of failing calls will fail the final task as it can't be completed. Retries are suggested way to handle network issues or temporary server unavailability for koji clients.

**Comment by teg** [comment]
TCP should do the retries for us, and we have increased the timeout / number of retries to try to be more resilient. This *should* have a similar effect to what you are proposing.

Do we yet know the root cause of the issues? Is it a flaky network connection or is brew simply under too much load?

**Comment by tkopecek** [comment]
No, TCP-level will not fix e.g. interrupted http connection. For last years flaky network was the most frequent issue. Current issues are probably also on network level (server can't send responses fast enough due to some glitch in VM/HV networking, but that is more a wild guess now). Part would be also the load - anyway, also in this case delaying request to be tried later would help a lot.

Koji itself doesn't retry calls in all cases (e.g. unknown SSL certificate) but on all potential connection errors. See logic behind https://pagure.io/koji/blob/master/f/koji/__init__.py#_2790. ``callnum`` session parameter then ensures that non-reentrant methods are not rexecuted in case connection was cut in the middle (code was finished and just response wasn't able to get through the network back to the client). With this code we don't know about the problems with our builders as they are all covered by this. 80% of detected problems are with the composer.

**Comment by teg** [comment]
I see, thanks for the explanation. What do you think @diaasami? At a first glance this looks like something we could use: https://pkg.go.dev/github.com/hashicorp/go-retryablehttp

Would be great if we were able to measure our retries so we know how bad this is and how close we are to failure. Were you able to get any insightful data on the TCP retransmissions Diaa?

Sorry if I led us down the wrong path on this.

**Comment by diaasami** [comment]
Thanks Tom for links, I hope this helps, I have an initial implementation and it should be deployed soon.
