### ISSUE TITLE
RFE: make dnf-json cache garbage collection size rather than time based

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#2446]
Currently `dnf-json` cleans up caches that are older than 24 hours. This is a good approximation, but we risk deleting useful caches too soon as well as not deleting large caches soon enough, depending on the usage patterns.

Suggestion:
After each depsolve, delete the least recently used cache entries until the total disk usage of the caches fall below a certain threshold.

Implementation suggestion:
 - Maintain a least recently used list containing the total space usage of each cache entry and its location.
 - In `update_used()`, `touch()` the directory entry on disk and update the LRU (time and size).
 - In `clean_unused()` delete the least recently used entries until the total usage falls below a configured threshold.
 - In `CacheState.load()` instantiate the LRU by iterating the cache entries in the cache dir (if it exists), read the `mtime` from the dirent and sum up the file sizes.
 - Drop `CacheState.store()`.

**Comment by teg** [comment]
@lavocatt @achilleas-k @gicmo @Gundersanne @ondrejbudai (and I'm sure others), any thoughts on this? I was having a look at `dnf-json` to better understand its performance and thinking ahead for supporting both Fedora and 3rd party repos where the behaviour might be quite different from what we saw so far.

**Comment by achilleas-k** [comment]
I think this makes sense, especially for on-prem situations where a user might not be building things that frequently.
