### ISSUE TITLE
osbuild-composer does not work on RHEL 9.2

### ISSUE THREAD

**Issue by henrywang** [osbuild/osbuild-composer#2523]
**Describe the bug**
osbuild-composer-46.2-1.el9_0.x86_64 does not work on RHEL 9.1.
```
Apr 06 23:56:57 rhel-9-1-220407 osbuild-composer[21246]: time="2022-04-06T23:56:57-04:00" level=info msg="Loaded 12 distros" func=main.NewComposer file="/builddir/build/BUILD/osbuild-composer-46.2/_build/src/github.com/osbuild/osbuild-composer/cmd/osbuild-composer/composer.go:66"
Apr 06 23:56:57 rhel-9-1-220407 osbuild-composer[21246]: 2022/04/06 23:56:57 Failed to load subscriptions. osbuild-composer will fail to build images if the configured repositories require them: no matching key and certificate pair
Apr 06 23:56:57 rhel-9-1-220407 osbuild-composer[21246]: time="2022-04-06T23:56:57-04:00" level=fatal msg="Error initializing weldr API: host distro is not supported" func=main.main file="/builddir/build/BUILD/osbuild-composer-46.2/_build/src/github.com/osbuild/osbuild-composer/cmd/osbuild-composer/main.go:89"
```
RHEL 9.1 distro does not defined its distro in rhel90 distro like what RHEL 8.7 is defined in https://github.com/osbuild/osbuild-composer/blob/aaee939f9b3544e208a3e8fa79324b68c91c2d8a/internal/distro/rhel86/distro.go#L637

No this issue was found on RHEL 8.7.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): Red Hat Enterprise Linux release 9.1 Beta (Plow)
 * osbuild-composer version (`rpm -qi osbuild-composer)`: osbuild-composer-46.2-1.el9_0.x86_64

**Comment by ondrejbudai** [comment]
Fixed! :) (Will fail on 9.2 though.)
