### ISSUE TITLE
Add the ability to run the integration test suite locally

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#255]
Follow-up to #234 (@msehnout's Vagrantfile) and #249 (@ondrejbudai's Vagrantfile and friends)

I discussed #249 with @teg and there are the outcomes:

The CI is the primary "tester" of osbuild/composer.

In an ideal world you might want to drop the local testing because then you don't need to maintain two environments. However, this is not possible - we need to run the integration tests in a VM, therefore it needs to be hosted in AWS or similar service. For that reason, secrets are involved. This makes running tests in forks impossible, which in turn makes any experimenting with our projects really hard. To sum it up, we need a way to run the integration test suite locally.

For the local environment we want to reuse the CI setup as much as possible. The goal is basically to run the same scripts on different targets. The setup of our CI is going to look more or less like this:

1) Fetch sources and build RPMs
2) Install the RPMs and run tests

Currently, the first step on the CI downloads the specfile, fetches sources from it and builds the RPM. On a local machine, that's roughly the same as our current setup in `make rpm`. However, the CI does it in a pristine container. We should do the same in the local setup to ensure the pristine environment (developers love to install weird stuff on their machines).

The second step on the CI (not yet implemented but we have a plan) firstly spins up a fresh VM on AWS, installs the RPMs there and run the tests. We should do the exact same thing in the local environment. Instead of AWS we should use qemu. I personally think that Vagrant is a great tool which is great for development and quick PoCs. However, it manages its inner state in a bit opaque way. This makes it not very suitable for integration tests which we would like to run in as defined environment as possible.

### VM/container versioning
Quoting @teg:
> I think we need to first set up and pin a well-known base VM (up-to-date Fedora Cloud 31 without any extra packages installed). We should take snapshots of this to run our tests in, knowing that every time we run the test-suite the base image is bit-for-bit the same and the only thing that changed is our test RPMs. From time to time we can update the base VM, but that should then be done explicitly and the last known-good tests re-run to verify the changing image does not break them.

This is something we currently don't know how to do it (both in the CI/locally). @major might help us. We should make sure we are using the same well-known base in the CI/locally.

### Development environment
It would be nice to have some. We think we can reuse the bits and pieces from the local integration tests setup but we are currently not sure how to exactly.

**Comment by msehnout** [comment]
I think we should get something as soon as possible. It is much better to run tests at least in development VM than not to run them at all. We will also have a proper CI setup soon so these tests will be the "single source of truth" and now we only need the development setup. WDYT?

**Comment by msehnout** [comment]
We can also make it a separate repo. I've used it like that for months.

**Comment by ondrejbudai** [comment]
> I think we should get something as soon as possible.

I agree but I also think we should wait for the CI runner. It shouldn't take long and we won't need to rewrite the local stuff when it comes.

**Comment by larskarlitski** [comment]
> Currently, the first step on the CI downloads the specfile, fetches sources from it and builds the RPM. On a local machine, that's roughly the same as our current setup in `make rpm`. However, the CI does it in a pristine container. We should do the same in the local setup to ensure the pristine environment (developers love to install weird stuff on their machines).

`make rpm` doesn't do the same thing as CI right now, because it doesn't prepend the `%global commit` macro to the spec file.

How do we choose which operating system this "pristine container" will contain? I agree with the problem of running on the host being unpredictable, but at least it makes rpms for that host.

> Instead of AWS we should use qemu.

Were you thinking about something like @teg's https://github.com/teg/test-vm?

**Comment by atodorov** [comment]
@ondrejbudai is this issue still relevant ?

**Comment by atodorov** [comment]
@ondrejbudai I believe this has been resolved with the latest changes from @teg and @larskarlitski in 
https://github.com/osbuild/osbuild-composer/pull/1021 and https://github.com/osbuild/osbuild-composer/pull/1020.

Can we close this issue now or is there something else that needs to be done ?

**Comment by ondrejbudai** [comment]
Yep, awesome!
