### ISSUE TITLE
osbuild-composer: "ostree: GetDistro - unknown distribution: fedora-37" on fedora rawhide

### ISSUE THREAD

**Issue by henrywang** [osbuild/osbuild-composer#2703]
**Describe the bug**
Can't build iot images on Fedora 37. When do blueprint `depsolve`, `ERROR: BlueprintsError: ostree: GetDistro - unknown distribution: fedora-37` appears.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): fedora 37 (rawhide)
 * osbuild-composer version (`rpm -qi osbuild-composer)`: osbuild-composer-53-1.fc37.x86_64

**To Reproduce**
 * Deploy a fedora 37(rawhide) vm on PSI openstack.
 * Run https://github.com/osbuild/osbuild-composer/blob/main/test/cases/ostree.sh

**Expected behavior**
 Run `ostree.sh` without error.

**Comment by ondrejbudai** [comment]
This should be fixed for a looooong time. :)
