### ISSUE TITLE
customizations.user stores password in plain text

### ISSUE THREAD

**Issue by parmstro** [osbuild/osbuild-composer#2713]
**Describe the bug**
When customizing a build and passing a user, the blueprint customizations.user section stores the password in plain text. It also stores groups = ["wheel"] for creating privileged users. The value should be encrypted.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): 
Red Hat Enterprise Linux release 9.0 (Plow)

 * osbuild-composer version (`rpm -qi osbuild-composer)`
rpm -qi osbuild-composer
Name        : osbuild-composer
Version     : 46.3
Release     : 1.el9_0
Architecture: aarch64
Install Date: Mon 30 May 2022 06:55:36 PM
Group       : Unspecified
Size        : 17645
License     : ASL 2.0
Signature   : RSA/SHA256, Sat 30 Apr 2022 11:33:10 AM, Key ID 199e2f91fd431d51
Source RPM  : osbuild-composer-46.3-1.el9_0.src.rpm
Build Date  : Thu 28 Apr 2022 02:25:01 PM
Build Host  : aarch64-002.build.eng.bos.redhat.com
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://github.com/osbuild/osbuild-composer
Summary     : An image building service based on osbuild

**To Reproduce**
Create a new blueprint 'testblueprint' using Image Builder app in cockpit
Customize blueprint adding user information 
- include a password supersecret
- select role as administrator
Select packages etc...

from the command prompt run:

sudo  composer-cli blueprints show testblueprint | grep -A5 'customizations.user'
[[customizations.user]]
name = "prodadmin"
description = "Prod Administrator"
password = "supersecret"
key = "ssh-rsa AAAA...6GQ5 dev.example.com"
groups = ["wheel"]

**Expected behavior**

password is encrypted

**Additional context**
This can expose credentials to remote systems easily of access is compromised to build system.

**Comment by teg** [comment]
We should probably move the password encryption from the manifest generation to where we deserialize the blueprints from the weldr api. In general we may want to make the internal representation of blueprints more powerful rather than just deserialized toml

**Comment by bcl** [comment]
Note that you don't have to store the password in the clear. It supports encrypted hashes:

https://www.osbuild.org/guides/blueprint-reference/blueprint-reference.html#additional-user

**Comment by parmstro** [comment]
Excellent, then this becomes something that perhaps cockpit-composer addresses e.g. encrypt password by default or provide for a selection. Also, it may also warrant a warning message in the cli output that the password for the user was stored in the clear. As for this Issue, we can close it as 'NOTABUG'

**Comment by teg** [comment]
I took the liberty of reopening. While it isn't critical, as @bcl pointed out, I still think we should improve it (if someone finds the time).

**Comment by parmstro** [comment]
@teg Thanks for that. I thought that maybe we might raise a separate issue for the enhancement request.

**Comment by ondrejbudai** [comment]
I'm in favor of deprecating pushing blueprints with an unencrypted password. It would mean adding support for hashing password in `cockpit-composer` though, otherwise we will break UX there. cc @jkozol

**Comment by teg** [comment]
Is there a convenient cli tool for doing this when using weldr cli?

**Comment by ondrejbudai** [comment]
Right, that would work as well.

**Comment by bcl** [comment]
This was fixed by  #2834
