### ISSUE TITLE
Make /internal/client compatible with RCM API

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#277]
We have RCM API as an alternative to the Weldr API, it'd be nice if we could reuse some of the testing code. But it will need few tweaks, for example here:
https://github.com/osbuild/osbuild-composer/blob/571932db37c8a58d9f0a50ba0aeb5935420f1b38/internal/client/client.go#L31

**Comment by teg** [comment]
The RCM API is beind replace by a new Koji API, and that already has a client in the proposed PR.
