### ISSUE TITLE
Create an integration test for RCM API

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#285]
Even thought the RCM API is not yet complete (see #192 for the status), we should introduce tests that will make sure the REST API does not break.

Acceptance criteria:
 - [x] Introduce new executable in `/cmd` that will run the tests
 - [x] Cover all endpoints and all expected use cases (create a compose, get compose status)
 - [ ] Plug-in the executable to our existing CI infrastructure

**Comment by bcl** [comment]
I think this should build on top of the new client library and follow the same output format as the osbuild-weldr-tests (or change them) so that results are consistent across all the integration test binaries.

eg. Add a rcm.go file to internal/client for rcm specific client functions.

**Comment by msehnout** [comment]
Sure, I wanted to keep it as simple as possible for the start, but I think it should be much simpler once we merge PR #295.

**Comment by msehnout** [comment]
We don't yet have a common way to execute test binaries in the CI, let's postpone that task until we agree on a common approach.
