### ISSUE TITLE
Clarify and automate test case generation

### ISSUE THREAD

**Issue by jkozol** [osbuild/osbuild-composer#291]
**Problem**
Our test/cases can verify the validity of a pipeline and image created from a specified blueprint, distro, and boot method. Currently, they are manually written. This is suboptimal since each additional distro or boot method will require several additional tests and with the move from dnf to rpm the cases will be tedious to manually write.

**Solution**
A python script will be able to generate test cases for each new distro and boot method. This script can be called by a developer with certain parameters and it will output json test cases. This will require clarifying which test cases are needed. Testing each combination of distro, output type, boot method, and blueprint customization will create too many test cases. Instead, the combinations that need to be tested should be clarified so as to reduce unnecessary test cases. For the script, it will need to generate pipelines and the resulting image's info. 

**Achievables**
- [x] Add a flag to `osbuild-pipeline` so it can output the results of rpmmd instead of the pipeline manifest
- [x] Update `distro/distro_test.go` to accept both package checksums and package specs
- [x] Create python script that accepts a `boot` and a `compose-request` key as input and uses `osbuild-pipeline` and `image-info` to generate test cases
- [x] Generate tests for combinations of boot methods and image types on x86_64

**Comment by teg** [comment]
This was implemnted! Thanks @jkozol.
