### ISSUE TITLE
Parallel build of AMIs fails after merging of #2718

### ISSUE THREAD

**Issue by diaasami** [osbuild/osbuild-composer#2961]
The jenkins job building worker AMIs fails in the last step while registering the AMIs with the error `ResourceNotReady: exceeded wait attempts`

Edit: adding more details:
Increasing the limits as mentioned on https://www.packer.io/plugins/builders/amazon#resourcenotready-error (up to 1 hour) has not resolved the issue.

**Comment by ondrejbudai** [comment]
Do we know what's the current limit? Anyway, we should increase it, import times in AWS can be wild.

**Comment by diaasami** [comment]
> Depending on the size of the volumes, it can take several minutes for the AMI-creation process to complete (sometimes up to 24 hours). You might find it more efficient to create snapshots of your volumes before creating your AMI. This way, only small, incremental snapshots need to be created when the AMI is created, and the process completes more quickly (the total time for snapshot creation remains the same)

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html

**Comment by diaasami** [comment]
In my local experiments, if the script reaches the packer part, one of the AMIs is always created within the current ~10ish limit, and the other fails, I have increased the wait until 1 hour (making the whole script take 1h 46m) but it still failed.

**Comment by diaasami** [comment]
After a lot of experimentation, things seem to work fine if I don't use packer parallel builds, and each build takes 15 minutes or less.
