### ISSUE TITLE
Use new azure-sdk-for-go module

### ISSUE THREAD

**Issue by bcl** [osbuild/osbuild-composer#2977]
`github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-09-01/network` used in `internal/boot/azuretest/azure.go` is deprecated. The guide for updating to the new module is here: https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md

**Comment by dustymabe** [comment]
It's worth noting that the auth library used:

https://github.com/osbuild/osbuild-composer/blob/be48279af8885d7c2c85c075313c491fc132125e/internal/upload/azure/azure.go#L11

is going [out of support at the end of March](https://github.com/Azure/go-autorest/blob/9038e4a609b1899f0eb382d03c3e823b70537125/README.md?plain=1#L1).

I just updated our COSA Azure libraries in https://github.com/coreos/coreos-assembler/pull/3349

**Comment by ondrejbudai** [comment]
Done in https://github.com/osbuild/osbuild-composer/pull/3853
