### ISSUE TITLE
Finish the rewrite of image tests to Go

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#299]
We want to have the image tests (currently in `test/run`) to be a part of our integration test suite. As our integration test suite is written in Go, it makes sense to have the image tests implemented also in Go.

Currently, the image info tests can be successfully run. To finish the rewrite it's needed to implement also the boot tests.

**Comment by atodorov** [comment]
@ondrejbudai for the boot tests do you mean "all output types" or only the ones which can be booted locally with qemu ? 

From what I can see `test/run` depends on image info to figure out what boot mechanism to use. How does this relate to cloud images (Amazon, Azure, others in future) ? My guess is that we want to upload & boot them on the respective cloud platform but did you mean for this to happen with the rewrite or as separate stand alone tests ?

**Comment by ondrejbudai** [comment]
We're currently testing to boot the images locally using `qemu` or `systemd-nspawn`. The following table has all the data:

| Image            | Testing method |
|------------------|----------------|
| vmdk             | qemu           |
| partitioned-disk | nspawn         |
| tar              | nspawn         |
| ext4-filesystem  | nspawn         |
| qcow2            | qemu           |
| ami              | qemu           |
| openstack        | qemu           |
| vhd              | qemu           |

Booting images in their respective cloud is a great next step but it's out of scope of this issue.

**Comment by ondrejbudai** [comment]
Done in #306
