### ISSUE TITLE
Osbuild-composer job fail inside container

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#300]
I tried running `osbuild-composer` inside a privileged container with all capabilities and the job fails without further explanation.

This is the Dockerfile I use:
```
FROM docker.io/library/fedora:31

RUN dnf install -y osbuild-composer osbuild composer-cli cockpit-composer && \
    systemctl enable osbuild-composer.socket

EXPOSE 9090

CMD [ "/sbin/init" ]
```
To build it, I go to the directory with the Dockerfile and run `podman build -t osbuild .`

This is how I run the container then:
```
podman run --name osbuild --rm --privileged --cap-add=ALL -it -v /dev:/dev -v /lib/modules:/lib/modules osbuild
```
and then I exec into it using `podman exec -it osbuild /bin/bash`

Inside I start osbuild-compsoer `systemctl start osbuild-composer.socket` create a simple blueprint using an example from weldr.io
```
name = "base"
description = "A base system with bash"
version = "0.0.1"

[[packages]]
name = "bash"
version = "*"
```
I upload the BP and run `composer-cli compose start base ext4-filesystem`

When looking at the journal this is what I see:
```
Mar 09 15:12:04 b38bdc772def osbuild-worker[62]: Running job 86446c72-f62a-46ef-8bb4-e565c530e677
Mar 09 15:12:04 b38bdc772def systemd[1]: Started Container osbuild-buildroot-r5jpdn5n.
Mar 09 15:13:12 b38bdc772def systemd[1]: osbuild-buildroot-r5jpdn5n.scope: Succeeded.
Mar 09 15:13:12 b38bdc772def systemd[1]: osbuild-buildroot-r5jpdn5n.scope: Consumed 38.156s CPU time.
Mar 09 15:13:15 b38bdc772def systemd[1]: Started Container osbuild-buildroot-o320dxud.
Mar 09 15:14:36 b38bdc772def systemd[1]: osbuild-buildroot-o320dxud.scope: Succeeded.
Mar 09 15:14:36 b38bdc772def systemd[1]: osbuild-buildroot-o320dxud.scope: Consumed 1min 607ms CPU time.
Mar 09 15:14:36 b38bdc772def systemd[1]: Started Container osbuild-buildroot-5bcr1u.
Mar 09 15:14:37 b38bdc772def systemd[1]: osbuild-buildroot-5bcr1u.scope: Succeeded.
Mar 09 15:14:37 b38bdc772def systemd[1]: Started Container osbuild-buildroot-pvjyaj6t.
Mar 09 15:14:37 b38bdc772def systemd[1]: osbuild-buildroot-pvjyaj6t.scope: Succeeded.
Mar 09 15:14:38 b38bdc772def systemd[1]: Started Container osbuild-buildroot-89f82iyp.
Mar 09 15:14:38 b38bdc772def systemd[1]: osbuild-buildroot-89f82iyp.scope: Succeeded.
Mar 09 15:14:38 b38bdc772def systemd[1]: Started Container osbuild-buildroot-3ipqvpxt.
Mar 09 15:14:39 b38bdc772def systemd[1]: osbuild-buildroot-3ipqvpxt.scope: Succeeded.
Mar 09 15:14:40 b38bdc772def osbuild-worker[62]: 2020/03/09 15:14:40   Job failed: exit status 1
Mar 09 15:14:40 b38bdc772def osbuild-worker[62]: Waiting for a new job...
```
If I compare that to a log where it's running on a VM it fails just before the end:
The log from a VM:
```
Mar 09 12:33:53 localhost.localdomain osbuild-worker[8812]: Waiting for a new job...                                                                                                                                                                                            
Mar 09 12:35:53 localhost.localdomain osbuild-worker[8812]: Running job 9d8255f4-cb4f-4ac5-b551-d12ce6177e7f                                                                                                                                                                    
Mar 09 12:35:53 localhost.localdomain systemd[1]: Started Container osbuild-buildroot-0v4fbd2p.                                                                                                                                                                                 
Mar 09 12:36:57 localhost.localdomain systemd[1]: osbuild-buildroot-0v4fbd2p.scope: Succeeded.                                                                                                                                                                                  
Mar 09 12:36:57 localhost.localdomain systemd[1]: osbuild-buildroot-0v4fbd2p.scope: Consumed 36.318s CPU time.                                                                                                                                                                  
Mar 09 12:37:00 localhost.localdomain systemd[1]: Started Container osbuild-buildroot-0v8ie3m6.                                                                                                                                                                                 
Mar 09 12:38:15 localhost.localdomain systemd[1]: osbuild-buildroot-0v8ie3m6.scope: Succeeded.                                                                                                                                                                                  
Mar 09 12:38:15 localhost.localdomain systemd[1]: osbuild-buildroot-0v8ie3m6.scope: Consumed 55.880s CPU time.                                                                                                                                                                  
Mar 09 12:38:15 localhost.localdomain systemd[1]: Started Container osbuild-buildroot-5ntg37sh.                                                                                                                                                                                 
Mar 09 12:38:16 localhost.localdomain systemd[1]: osbuild-buildroot-5ntg37sh.scope: Succeeded.                                                                                                                                                                                  
Mar 09 12:38:16 localhost.localdomain systemd[1]: Started Container osbuild-buildroot-wagyo1py.                                                                                                                                                                                 
Mar 09 12:38:16 localhost.localdomain systemd[1]: osbuild-buildroot-wagyo1py.scope: Succeeded.                                                                                                                                                                                  
Mar 09 12:38:16 localhost.localdomain systemd[1]: Started Container osbuild-buildroot-uay2lrzl.                                                                                                                                                                                 
Mar 09 12:38:17 localhost.localdomain systemd[1]: osbuild-buildroot-uay2lrzl.scope: Succeeded.                                                                                                                                                                                  
Mar 09 12:38:17 localhost.localdomain systemd[1]: Started Container osbuild-buildroot-1zcrd9e9.                                                                                                                                                                                 
Mar 09 12:38:24 localhost.localdomain systemd[1]: osbuild-buildroot-1zcrd9e9.scope: Succeeded.                                                                                                                                                                                  
Mar 09 12:38:24 localhost.localdomain systemd[1]: osbuild-buildroot-1zcrd9e9.scope: Consumed 6.948s CPU time.                                                                                                                                                                   
Mar 09 12:38:27 localhost.localdomain systemd[1]: Started Container osbuild-buildroot-ldlganyd.                                                                                                                                                                                 
Mar 09 12:38:27 localhost.localdomain kernel: EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)                                                                                                                                                          
Mar 09 12:38:31 localhost.localdomain systemd[1]: osbuild-buildroot-ldlganyd.scope: Succeeded.                                                                                                                                                                                  
Mar 09 12:38:31 localhost.localdomain systemd[1]: osbuild-buildroot-ldlganyd.scope: Consumed 2.965s CPU time.                                                                                                                                                                   
Mar 09 12:38:43 localhost.localdomain osbuild-worker[8812]: Waiting for a new job...
```
Looking at `/var/lib/osbuild-composer/outputs/$UUID/0/result.json` I see this at the end:
```
      "name": "org.osbuild.selinux",
      "options": {
        "file_contexts": "etc/selinux/targeted/contexts/files/file_contexts"
      },
      "success": false,
      "output": "[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping\nAll rules containing unresolvable specifiers will be skipped.\nsetfiles: Could not set context for /run/osbuild/tree:  Operation not supported\nTraceback (most recent call last):\n  File \"/run/osbuild/lib/stages/org.osbuild.selinux\", line 43, in <module>\n    r = main(args[\"tree\"], args[\"options\"])\n  File \"/run/osbuild/lib/stages/org.osbuild.selinux\", line 39, in main\n    subprocess.run([\"setfiles\", \"-F\", \"-r\", f\"{tree}\", f\"{file_contexts}\", f\"{tree}\"], check=True)\n  File \"/usr/lib64/python3.7/subprocess.py\", line 487, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['setfiles', '-F', '-r', '/run/osbuild/tree', '/run/osbuild/tree/etc/selinux/targeted/contexts/files/file_contexts', '/run/osbuild/tree']' returned non-zero exit status 255.\n"
    }
  ],
  "assembler": null,
  "success": false
}
```
I can see a selinux fail, but I don't know what that means. Can anyone tell me what seems to be the problem or where else to look?

**Comment by larskarlitski** [comment]
> `podman run --name osbuild --rm --privileged --cap-add=ALL -it -v /dev:/dev -v /lib/modules:/lib/modules osbuild`

Note that giving a container access to `/dev` defeats the point of using containers, because it now has access to all of the host's hardware. It is fine to use during development, but I wouldn't want to suggest in any way that this is an acceptable way to run it in production. (This is only for `osbuild-worker`. `osbuild-composer` can be run inside a container.)

Sorry, I don't know what could be causing the selinux error you're seeing :(

**Comment by jrusz** [comment]
> Note that giving a container access to /dev defeats the point of using containers, because it now has access to all of the host's hardware. It is fine to use during development, but I wouldn't want to suggest in any way that this is an acceptable way to run it in production. 

I agree, my ultimate goal was to limit the access the container has to the host system as much as possible and see if I could get to an acceptable state. This is just a test to see if it's even possible to run the `osbuild-worker` inside container in any way :)

**Comment by teg** [comment]
As @ondrejbudai mentioned, this is most likely caused by missing xattr support in overlayfs, which is used in the containers. You may make this work by mounting /var/tmp and possibly other filesystem from the host to give non-overlayfs-backed filesystems for us to use. This is a useful exercise in order to find out exactly what is required by osbuild-worker, but most likely it will not be all that useful to test it in this way, as it will be significantly different from the setup we'd use in production.

**Comment by jrusz** [comment]
> As @ondrejbudai mentioned, this is most likely caused by missing xattr support in overlayfs, which is used in the containers.
Yes that helped, thank you @ondrejbudai . I got a finished build when I create a `/var/tmp/shared_tmp` and mount it. The final command looks like this:
```
podman run --name osbuild --rm --privileged --cap-add=ALL -it -v /dev:/dev -v /lib/modules:/lib/modules -v  /var/tmp/shared_tmp:/var/tmp osbuild
```

I will now try to remove as many of the privileges as possible.

**Comment by ondrejbudai** [comment]
It's cool to see that osbuild actually can be run in a container. However, I would like to stress what was needed to achieve it:

- privileged container
- all capabilities
- shared `/dev`
- extra-mounted `/var/tmp` to overcome limitations of podman and overlayfs (I don't know the exact reason why xattrs don't work in this setup)

This has two big implications:
- The container has full access to the host machine and therefore **it's not safe** as one might expect.
- The setup is really weird and does not reflect how we recommend to use the software (bare metal/VM without any kind of containerization). Therefore, it might have unexpected issues.

#### My recommendation
Do not run `osbuild` in a container. The software was not designed to be able to run inside a container and it might break in unexpected ways.

However, it should be totally possible to run `osbuild-composer` in a container. Keep in mind that you must disable the local worker in this setup and run a remote one on a VM/bare metal.

#### Closing remarks
I would like to thank you, @jrusz, for your contribution to the container debate. It's surely very beneficial and interesting to see what is required to get `osbuild` running in a container.

Let's have this issue open for now for anyone who wants to contribute to the discussion.

**Comment by teg** [comment]
@jrusz @ondrejbudai thanks for working through this! I agree with Ondrej's conclusion, but nevertheless, this is very useful to know!

**Comment by msehnout** [comment]
Thanks for this effort! 

If we could get a list of specific features we need from the kernel, overlayfs, podman etc. that would be really great because we would have a starting point for a discussion with upstream communities of these projects. Or rather a starting point for our own investigation before we contact others.

So far I can see:
 * support for xattr in podman containers
 * loopback devices independent of the whole `/dev`

But I'd nice to investigate which capabilities are needed.

**Comment by teg** [comment]
FTR, in our discussions with the kernel developers it became clear that independent/namespaced `/dev` would be quite a major undertaking (even just the loopback part), and there was not full buyin from all the relevant maintainers that this is something we want at all. So we shouldn't hold our breaths for that.

**Comment by jrusz** [comment]
I have some update. I got it working without privileged container running this:
```
podman run --name osbuild --rm -it --device=/dev/loop0:/dev/loop0 --device=/dev/loop-control:/dev/loop-control --device=/root/fakedev/tun:/dev/net/tun -v /root/tmp:/var/tmp --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --cap-add=AUDIT_CONTROL osbuild
```
I created the `/dev/net/tun` using mknod on the host device. I tried the same for `loop-control` and `loop0` but that didn't work right away for some reason. Also I need `setenforce 0` on the host machine and it's being run as root user. 

I think that it will have to be run under root user because `osbuild-worker` is running as root anyway, but I believe we can limit what the container can and can't do quite a bit.

**Comment by teg** [comment]
Thanks for the update!

What's your plan going forward? As mentioned earlier, I think this is interesting information to have, but for actual testing I don't think it makes sense to use containers, even if they work (too different from real system).

We don't have a good story yet though, but we should work on making it easier to test in VMs.

**Comment by jrusz** [comment]
> for actual testing I don't think it makes sense to use containers, even if they work (too different from real system).

So even if it runs in a container that has access limited to the loop devices in `/dev` and some acceptable privileges you still think it won't be of any use? I thought that the current issue is that the container was privileged and it was not safe to run.

My plan was to limit this as much as possible and then ask on podman mailing list what problems can it cause on the host system, if any and then ask you here if it could be used for testing as a faster alternative to VMs. But if you believe it's too different from running in a VM then I guess there's no point in continuing in this effort.

**Comment by teg** [comment]
There are some quite fundamental issues with this, so I would not recommend going down this route. 

The problem is that we are allocating loop devices dynamically, from a shared namespace. If you have no other users of the loopback namespace when you run your test, then we will end up using /dev/loop0, so your setup will work. However, if someone else is already using /dev/loop0, we will end up with /dev/loop1 (or something else), so you need to pass the right one in to the container. 

The only way to make this reliable if you can somehow guarantee that nobody else on the system will be using loopback devices while your tests are running, and that you only ever run one test at once. The reason is that even if you pass in /dev/loop0 and nobody is using it at the time, you are not able to reserve it, so somebody else might come and grab it before you get to the point in the tests where we try to actually use it (and we would then fail).

It might be fine to make such assumptions on your local machine just to try things out quickly, but we should have a more reliably recommended way of running our tests.

**Comment by ondrejbudai** [comment]
I guess it's fine to use a container for developing automated tests. If there are some issues with them in the container, it will be caught by the CI, which will run the tests on a proper VM. However, I think the official repository shouldn't mention this option because it isn't the recommended nor supported way of running osbuild due to all the issues mentioned here.

For doing anything else in the container apart from developing automated tests: If an error occurs, there's always a question: Is it caused by a bug or is it caused by the environment for which osbuild was not designed? Personally, I would very much dislike the uncertainty.

I appreciate all your work, it gave us very interesting results which may be very useful for us at some point (honestly, why the hell do you need root to build an image? Fundamentally, it's just copying of bits to the right places...). However, for now, we cannot recommend/support running osbuild in a container because of all the limitations. :slightly_frowning_face:

**Comment by jrusz** [comment]
I guess there's not much else to say here, I understand that osbuild is intended to be used in a VM and not in container and that this is not the way to go even if it kinda works.
