### ISSUE TITLE
Weldr API can't load cross-distro composes from store

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#3060]
When loading `state.json` into the store on start, the host distro object is used to retrieve image types and load them for the database.

https://github.com/osbuild/osbuild-composer/blob/6ae8904f5ab047406ff7228bdd66df4e426a304e/internal/store/json.go#L370

This means that cross-distro builds either:
1. Can't be loaded if the image type name doesn't exist in the host distro (e.g., loading `edge-commit` on Fedora).
2. Will load the wrong image type if the name exists in the host distro.

The second can cause errors if the image type parameters differ between the same image type across distro.  For example, if the filename for `qcow2` differs between Fedora and CentOS/RHEL, then `composer-cli compose image ...` command will fail to find the artefact of a successful build.

**Comment by ondrejbudai** [comment]
@bcl can you have a look when you have time?
