### ISSUE TITLE
Create `/run/ostree-booted` for ostree composes

### ISSUE THREAD

**Issue by travier** [osbuild/osbuild-composer#3087]
For https://bugzilla.redhat.com/show_bug.cgi?id=2082845, we'll need osbuild to create `/run/ostree-booted` during image builds to let RPM packages know that they are installed as part of an (rpm-)ostree build.

See https://github.com/coreos/rpm-ostree/pull/1750

**Comment by teg** [comment]
Thanks @gicmo for already hooking this up, and tracking it here. We should of course make sure we stay compatible.

I agree with your sentiment @cgwalters, would be great if ostree vs non-ostree would be something that was transparent to almost everything else. If there is something we can do to drive towards that goal long-term I'm all for it.

**Comment by thozza** [comment]
This was done as part of https://github.com/osbuild/osbuild-composer/pull/2914
