### ISSUE TITLE
RFC: Do we want to use asserts or not

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#309]
Now that #301 has been merged I want to raise the question should we start using asserts in the test binaries or not? 

In Go there isn't an asserts package coming directly with the language/bundled with the testing framework. However github.com/stretchr/testify/assert is widely used. The practice of using asserts in Go is left to be decided on a case by case basis.

ATM we've got something like this:

```
       _, c, err := rpmMetadata.FetchMetadata([]rpmmd.RepoConfig{repoCfg}, "platform:f31")
        if err != nil {
                t.Fatalf("Failed to fetch checksum: %v", err)
        }
        if c["repo"] == "" {
                t.Errorf("The checksum is empty")
        }
```

which can also be written like this:

```
       _, c, err := rpmMetadata.FetchMetadata([]rpmmd.RepoConfig{repoCfg}, "platform:f31")
       
       assert.Nil(t, err, "Failed to fetch checksum")
       assert.NotEqual(t, "", c["repo"], "The checksum is empty")
```

Benefits of using asserts:
-  shorter syntax and a bit more readable IMO
- virtually every other language/test framework uses them so that makes the test suite more familiar to people experienced in other technologies (incl. myself)
- Feels like a good practice anyway

Downsides:
- will require patching the existing test suite, e.g. time but this is something QE can work on (will also give us more hands-on experience anyway)
- other folks may not like this style of writing

I can't think of very strong pros or cons for either approach but the current one just doesn't feel right to me. My overall argument is that the asserts module is out there and widely used so why aren't we making use of it ?

**Comment by teg** [comment]
A priori, this seems reasonable to me, though I have no strong opinion in either direction. Let's hear if others have any objections.

**Comment by larskarlitski** [comment]
I don't have a strong opinion either. The only downside I see is that because not everything can be expressed by a function from the `assert` package, we'll inevitable have two styles in some places.

> shorter syntax and a bit more readable IMO

Yeah, it really does read much better. Are `assert`s equivalent to `log.Error()` or `log.Fatal()`?

> other folks may not like this style of writing

Right, let's wait for some more opinions.

**Comment by bcl** [comment]
Initially I didn't see the point in switching. But then I looked at the docs:

https://godoc.org/github.com/stretchr/testify/assert

It has a pretty impressive array of assertions, including the ability to add formatted strings (I like printing %#v to see what actually was being compares) so I think this would be a good idea.

**Comment by atodorov** [comment]
> Are asserts equivalent to log.Error() or log.Fatal()?

@larskarlitski from what I can see from the code asserts will return `t.Fail` or bool and the logging part is handled by the testing package. So `assert == t.Fail` I think.

**Comment by larskarlitski** [comment]
> @larskarlitski from what I can see from the code asserts will return `t.Fail` or bool and the logging part is handled by the testing package. So `assert == t.Fail` I think.

Sounds reasonable. Thanks!

**Comment by atodorov** [comment]
@ondrejbudai, @msehnout what is your opinion on $subject

**Comment by ondrejbudai** [comment]
Firstly, I would like to stress the `require` package.
- `assert == t.Fail`
- `require == t.FailNow`

I think I'm slightly for the switch, imho it makes the tests easier to read.

**Comment by teg** [comment]
Sounds like we all agree that this makes sense (@msehnout is out today). Let's move things over when it makes sense, note that lots of the tests are actively being worked on now, so let's coordinate a bit before refactoring to avoid too many merge conflicts.

**Comment by bcl** [comment]
Ok, I didn't understand what @ondrejbudai meant in his comment. But I do now.
If you want to fail immediately, not doing any more of the asserts use the require package instead of the assert package: https://pkg.go.dev/github.com/stretchr/testify/require?tab=doc

Otherwise you'll end up with panic's and nil pointer memory problems like I did :)

**Comment by msehnout** [comment]
> @ondrejbudai, @msehnout what is your opinion on $subject

I think it sounds reasonable to me. If we could have a document describing how to use it in the tests so that we don't end up mixing the old and the new approach, that would be great.

**Comment by ondrejbudai** [comment]
We agreed on using asserts, all the integration tests were migrated. #322 added docs how to use them. Is it ok to close this issue @atodorov ?

**Comment by atodorov** [comment]
Yes, we can close this. 

It would be nice if we used the issue number in commit log messages so GitHub can handle this for us.
