### ISSUE TITLE
Rewrite osbuild-image-tests.go to use the testing module syntax

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#310]
See #301 for example & discussion.  Also see #309 for possible future changes which require the use of the new syntax. 

Benefits in short: 
- automatic test discovery, running & reporting
- machine readable test output with possibility to feed that to additional tools
- common syntax (available in most resources about testing in Go)
- will make some code unnecessary (main function, run function, etc)

**Comment by teg** [comment]
@ondrejbudai, any objections?

**Comment by atodorov** [comment]
CC @jikortus, @jrusz

**Comment by ondrejbudai** [comment]
I will do it as part of #299

**Comment by ondrejbudai** [comment]
I decided to do it as an independent PR, starting right now.

**Comment by teg** [comment]
This was implemented in #335.
