### ISSUE TITLE
specifying a parent commit when doing `compose start-ostree` fails to start compose

### ISSUE THREAD

**Issue by miabbott** [osbuild/osbuild-composer#3107]
**Describe the bug**

When trying to compose an `edge-installer` artifact via `composer-cli compose start-ostree`, specifying a parent commit causes the compose operation to fail.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):

```
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.1 (Plow)
[root@localhost ~]# # cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.1 (Plow)
```

 * osbuild-composer version (`rpm -qi osbuild-composer)`

```
[root@localhost ~]# rpm -qi osbuild-composer
Name        : osbuild-composer
Version     : 62.1
Release     : 1.el9
Architecture: x86_64
Install Date: Tue Oct 18 13:22:04 2022
Group       : Unspecified
Size        : 17612
License     : ASL 2.0
Signature   : RSA/SHA256, Fri Sep 16 11:40:17 2022, Key ID 199e2f91fd431d51
Source RPM  : osbuild-composer-62.1-1.el9.src.rpm
Build Date  : Fri Sep 16 10:08:50 2022
Build Host  : x86-64-01.build.eng.rdu2.redhat.com
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://github.com/osbuild/osbuild-composer
Summary     : An image building service based on osbuild
Description :

A service for building customized OS artifacts, such as VM images and OSTree
commits, that uses osbuild under the hood. Besides building images for local
usage, it can also upload images directly to cloud.

It is compatible with composer-cli and cockpit-composer clients.
```

**To Reproduce**

1. Create an empty blueprint and compose an ostree commit artifact
2. Serve the ostree commit via HTTP
3. Create an empty bluepint and try to compose an `edge-installer` image while specifying a parent commit:

`# composer-cli compose start-ostree myblueprint edge-installer --url http://localhost:8080/repo --ref rhel/9/x86_64/edge --parent 1d3fbdd0f6f73247a04b757af45b3e3d47687820a7734aca4a4756ffc608a835
ERROR: OSTreeOptionsError: ostree repository "http://localhost:8080/repo/refs/heads/1d3fbdd0f6f73247a04b757af45b3e3d47687820a7734aca4a4756ffc608a835" returned status: 404 File not found
`

**Expected behavior**

Compose is started for `edge-installer` image.

**Additional context**

The logs from the HTTP server shows that the `osbuild-composer` is trying to fetch parent commit from the wrong location in the ostree repo.

```
Oct 31 14:38:36 localhost.localdomain osbuild-composer[806]: 2022/10/31 14:38:36 POST /api/v1/compose
Oct 31 14:38:36 localhost.localdomain serene_blackburn[2934]: 10.88.0.1 - - [31/Oct/2022 18:38:36] code 404, message File not found
Oct 31 14:38:36 localhost.localdomain serene_blackburn[2934]: 10.88.0.1 - - [31/Oct/2022 18:38:36] "GET /repo/refs/heads/1d3fbdd0f6f73247a04b757af45b3e3d47687820a7734aca4a4756ffc608a835 HTTP/1.1" 404 -
```

Omitting the parent commit will allow the compose to proceed.

```
[root@localhost ~]# composer-cli compose start-ostree first-time-user edge-installer --url http://localhost:8080/repo --ref rhel/9/x86_64/edge 
Compose e44a8660-5660-4819-958d-9137e7f762e8 added to the queue
[root@localhost ~]# composer-cli compose start-ostree first-time-user edge-installer --url http://localhost:8080/repo 
Compose f5dd80b3-a6ac-4ead-9092-8573c970567a added to the queue
```

**Comment by achilleas-k** [comment]
The purpose of the `edge-installer` is to deploy a pre-built commit.  Specifying a parent doesn't really make sense in this context.  The commit is already built and served by the container and the build process will pull it, embed it into an iso, and prepare the iso to deploy it.

The purpose of the `--parent` flag is to specify a parent commit when building a new one.  The idea is that the new commit is built as a child of the parent commit and takes certain things into account when composing the new commit (specifically user and group IDs now, but more things may be considered in the future).

We do have an issue here though in that we're not very clear in communicating how the ostree parameters (`ref`, `url`, and `parent`) interact with each different image type.

**Comment by jritter** [comment]
Hi,

I just bumped into the same issue. In my scenario, I would like to update and existing RHEL 9 deployment. I tried without specifying the --parent flag, but when doing so the group configuration for the SSH host key changes after booting into the updated deployment, which prevents the startup of the SSH daemon.

Is there a workaround to build from command line?

**Comment by achilleas-k** [comment]
Yes, in this case the `--parent` flag should be specified when building the `edge-commit` or `edge-container` for the update.
The original issue here was that `--parent` doesn't make sense when building an installer.

Are you having trouble specifying a parent commit when building a commit/container?

**Comment by jritter** [comment]
Yes, I'm trying to build an update for an existing rhel-edge-commit.

```
$ composer-cli compose start-ostree <blueprint> rhel-edge-commit --parent 3d3eab2c0b29ddb12aee6c38f3aadd823ca09e5e95cd9a590bc4a901c2b162b3 --ref rhel/9/x86_64/edge --url http://<hostname>/akb/repo
ERROR: OSTreeOptionsError: ostree repository "http://<hostname>/akb/repo/refs/heads/3d3eab2c0b29ddb12aee6c38f3aadd823ca09e5e95cd9a590bc4a901c2b162b3" returned status: 404 Not Found
$ cat /var/www/html/akb/compose.json
{"ref":"rhel/9/x86_64/edge","ostree-n-metadata-total":22275,"ostree-n-metadata-written":9326,"ostree-n-content-total":76688,"ostree-n-content-written":57423,"ostree-n-cache-hits":0,"ostree-content-bytes-written":1577501773,"ostree-commit":"3d3eab2c0b29ddb12aee6c38f3aadd823ca09e5e95cd9a590bc4a901c2b162b3","ostree-content-checksum":"3a215956bf26608e7d060d0e71a0982f9e52cdec570d3e17af77aec1a0529ae8","ostree-version":"9.0","ostree-timestamp":"2022-10-07T09:21:49Z","rpm-ostree-inputhash":"600967e72bdd65fb415d30a3ac0b2f37f9e67cf99ae690fb999839124dc17722"}
$ find /var/www/html/akb/repo/refs/heads/
/var/www/html/akb/repo/refs/heads/
/var/www/html/akb/repo/refs/heads/rhel
/var/www/html/akb/repo/refs/heads/rhel/9
/var/www/html/akb/repo/refs/heads/rhel/9/x86_64
/var/www/html/akb/repo/refs/heads/rhel/9/x86_64/edge
$ cat /var/www/html/akb/repo/refs/heads/rhel/9/x86_64/edge
3d3eab2c0b29ddb12aee6c38f3aadd823ca09e5e95cd9a590bc4a901c2b162b3
```

I just extracted the original build to a apache webserver and served it from there, which works fine in general. But updating has been an issue.

When removing the --parent flag, the build starts, but it breaks the system after upgrading.

**Comment by achilleas-k** [comment]
Oh, I see.
I think there's a bug here, or at least a change in behaviour.

This should work:
```
$ composer-cli compose start-ostree <blueprint> rhel-edge-commit --parent rhel/9/x86_64/edge --ref rhel/9/x86_64/edge --url http://<hostname>/akb/repo
```

With this, composer will resolve the commit at `http://<hostname>/akb/repo/refs/heads/rhel/9/x86_64/edge` and use it as a parent.

**Comment by jritter** [comment]
Worked like a charm! Thanks a lot!

**Comment by achilleas-k** [comment]
I'll keep the issue open because a lot of this needs to be clarified/documented and maybe made more flexible.

**Comment by miabbott** [comment]
I ran into this again recently and wanted to document that you can omit the `--parent` option when doing `composer-cli compose start-ostree --ref <ref> --url <url> <blueprint>...` and the compose will use the HEAD commit from the ostree repo.  (This worked for `edge-commit` and `iot-commit`; probably `edge-container` and `iot-container` too)

Given that an ostree repo can have multiple commits and multiple refs, I'd like to see the `--parent` option be able to take a commit checksum that will serve as the starting point for the new commit that is generated.

**Comment by achilleas-k** [comment]
> Given that an ostree repo can have multiple commits and multiple refs, I'd like to see the `--parent` option be able to take a commit checksum that will serve as the starting point for the new commit that is generated.

I think this makes sense.  I'll write up a feature.

**Comment by achilleas-k** [comment]
Test has been added in osbuild-composer CI for on-prem / weldr.  I've also confirmed it works through the Cloud API.

Calling this done and solved.
