### ISSUE TITLE
Rewrite osbuild-rcm-tests to use the testing module syntax

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#311]
See #301 for example & discussion.  Also see #309 for possible future changes which require the use of the new syntax. 

Benefits in short: 
- automatic test discovery, running & reporting
- machine readable test output with possibility to feed that to additional tools
- common syntax (available in most resources about testing in Go)
- will make some code unnecessary (main function, run function, etc)

**Comment by teg** [comment]
@msehnout, any objections?

**Comment by atodorov** [comment]
CC @jikortus, @jrusz

**Comment by msehnout** [comment]
> @msehnout, any objections?

No, let's use whatever we use elsewhere

**Comment by jrusz** [comment]
WIP PR can be found here https://github.com/osbuild/osbuild-composer/pull/331

**Comment by larskarlitski** [comment]
> WIP PR can be found here #331

For your interest: if you include `Fixes #311` in a commit message or the initial comment on the PR, GitHub includes a link to it here automatically and closes the issue when the PR is merged.

**Comment by jrusz** [comment]
> For your interest: if you include `Fixes #311` in a commit message or the initial comment on the PR, GitHub includes a link to it here automatically and closes the issue when the PR is merged.

Ah, that's useful, thanks :)
