### ISSUE TITLE
`composer-cli blueprint diff` doesn't print any changes

### ISSUE THREAD

**Issue by miabbott** [osbuild/osbuild-composer#3110]
**Describe the bug**

When using `composer-cli blueprint diff` to print changes between two blueprint commits, there are no changes printed out.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):

```
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.1 (Plow)
```

 * osbuild-composer version (`rpm -qi osbuild-composer)`

```
[root@localhost ~]# rpm -qi osbuild-composer
Name        : osbuild-composer
Version     : 62.1
Release     : 1.el9
Architecture: x86_64
Install Date: Tue Oct 18 13:22:04 2022
Group       : Unspecified
Size        : 17612
License     : ASL 2.0
Signature   : RSA/SHA256, Fri Sep 16 11:40:17 2022, Key ID 199e2f91fd431d51
Source RPM  : osbuild-composer-62.1-1.el9.src.rpm
Build Date  : Fri Sep 16 10:08:50 2022
Build Host  : x86-64-01.build.eng.rdu2.redhat.com
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://github.com/osbuild/osbuild-composer
Summary     : An image building service based on osbuild
Description :

A service for building customized OS artifacts, such as VM images and OSTree
commits, that uses osbuild under the hood. Besides building images for local
usage, it can also upload images directly to cloud.

It is compatible with composer-cli and cockpit-composer clients.
```

**To Reproduce**

1.  Create a blueprint with the following content:

```toml
name = "first-time-user"
description = ""
version = "0.0.2"
modules = []
groups = []
distro = ""

[[packages]]
name = "strace"
version = "*"

[customizations]
```

2. `composer-cli blueprints push blueprint.toml`
3. Edit the TOML file to change the version string and add `nginx` package

```toml
name = "first-time-user"
description = ""
version = "0.0.3"
modules = []
groups = []
distro = ""

[[packages]]
name = "strace"
version = "*"

[[packages]]
name = "ngnix"
version = "*"

[customizations]
```

4. `composer-cli blueprints push blueprint.toml`
5. List the commits with `composer-cli blueprints changes first-time-user`

```
[root@localhost ~]# composer-cli blueprints changes first-time-user
first-time-user
    2022-11-01T09:58:56Z  5a1d3c2986b49e56cf8d91f918e9cf3d9e27986f
    Recipe first-time-user, version 0.0.3 saved.

    2022-11-01T09:57:55Z  835e5ca1d3b54fa36dc2e618168ca28d903327ef
    Recipe first-time-user, version 0.0.2 saved.
```

6. Run the diff command `composer-cli blueprints diff first-time-user 5a1d3c2986b49e56cf8d91f918e9cf3d9e27986f 835e5ca1d3b54fa36dc2e618168ca28d903327ef`

```
[root@localhost ~]# composer-cli blueprints diff first-time-user 5a1d3c2986b49e56cf8d91f918e9cf3d9e27986f 835e5ca1d3b54fa36dc2e618168ca28d903327ef
Ran the blueprints diff: [first-time-user 5a1d3c2986b49e56cf8d91f918e9cf3d9e27986f 835e5ca1d3b54fa36dc2e618168ca28d903327ef] command
```

**Expected behavior**

The command should show the diff between the two commits.  For example:

```diff
3c3
< version = "0.0.3"
---
> version = "0.0.2"
10,13d9
< version = "*"
< 
< [[packages]]
< name = "ngnix"
```

**Additional context**

I can see the API server getting requests for the changes when the diff command is run:

```
Nov 01 10:04:12 localhost.localdomain osbuild-composer[806]: 2022/11/01 10:04:12 GET /api/v1/blueprints/changes/first-time-user
Nov 01 10:04:12 localhost.localdomain osbuild-composer[806]: 2022/11/01 10:04:12 GET /api/v1/blueprints/changes/first-time-user
```

But nothing comes of it.

**Comment by ondrejbudai** [comment]
@bcl, can you please have a look when you have time?

**Comment by bcl** [comment]
Yeah, diff was not implemented in osbuild-composer. And for a while there we didn't even have the old blueprints saved, so there was no point in adding it.

In lorax-composer I wrote a bunch of code to generate a json 'diff' assuming the web ui would use it, but that never happened and it was fairly difficult to maintain so I'm not that sorry to see it go.

I think what I'd like to do is:
 * Add the ability to run `composer-cli blueprint show first-time-user COMMIT` so that it can be retrieved.
 * Implement diff in the front-end instead of the API using the two versions. For composer-cli I can pass it to a standard diff utility, for the web-ui I'm sure someone has written a diff module in javascript :)
  * Return a suitable error from the /diff/ api route

**Comment by miabbott** [comment]
I like the idea of managing blueprints via commit IDs, so improving/streamlining the tooling around this would be helpful.

The MVP of having something like `composer-cli blueprint show first-time-user COMMIT` would be enough to get the user to be able to diff two commits manually (i.e. `diff <(composer-cli blueprint show first-time-user COMMIT_A) <(composer-cli blueprint show first-time-user COMMIT_B)`

**Comment by bcl** [comment]
This is now working, you need osbuild-composer v72 and weldr-client v35.9
