### ISSUE TITLE
Rewrite osbuild-tests to use the testing module syntax 

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#312]
See #301 for example & discussion.  Also see #309 for possible future changes which require the use of the new syntax. 

Benefits in short: 
- automatic test discovery, running & reporting
- machine readable test output with possibility to feed that to additional tools
- common syntax (available in most resources about testing in Go)
- will make some code unnecessary (main function, run function, etc)

**Comment by teg** [comment]
Sounds good to me!

**Comment by atodorov** [comment]
@teg great. @jikortus, @jrusz and myself can work on this. We'll coordinate between ourselves and ping you if we have questions.

**Comment by teg** [comment]
Perfect! Thanks!
