### ISSUE TITLE
Rewrite osbuild-wedlr-tests to use the testing module syntax 

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#313]
See #301 for example & discussion.  Also see #309 for possible future changes which require the use of the new syntax. 

Benefits in short: 
- automatic test discovery, running & reporting
- machine readable test output with possibility to feed that to additional tools
- common syntax (available in most resources about testing in Go)
- will make some code unnecessary (e.g. main, run functions, etc)

NOTE: some functions in the internal/weldrcheck module look more like testing functions.

**Comment by teg** [comment]
@bcl does this sound good to you?

**Comment by bcl** [comment]
Yeah, I think so. I believe all my concerns have been answered in the other discussion threads. I'll handle this in a future PR, I'm currently in the middle of adding new tests and fixing some bugs.

**Comment by atodorov** [comment]
@bcl feel free to leave this to @jikortus, @jrusz and myself. We definitely need the exercise.

**Comment by bcl** [comment]
I'll take care of this one, this code is what I'm working on at the moment.

**Comment by bcl** [comment]
pr #314 takes care of this for blueprints.
