### ISSUE TITLE
Fedora IoT iso only shows "Network" and "Installation Destination" spokes in anaconda

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3141]
**Describe the bug**
When building an 'iot-installer' iso for Fedora IoT, the resulting image only shows the  "Network" and "Installation Destination" spokes in anaconda with a message displayed  "Kickstart insufficient" under the storage spoke. 

**Environment**
 Fedora Koji

**To Reproduce**

Create an iso:
koji osbuild-image Fedora-IoT 38 fedora-38 f38-candidate x86_64 --repo='https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/compose/Everything/$arch/os/' --ostree-url='http://kojipkgs.fedoraproject.org/compose/iot/repo/' --ostree-ref='fedora/rawhide/$arch/iot' --image-type iot-installer --release 20221116.10 --skip-tag

Boot the resulting iso in a VM. 

**Expected behavior**
All anaconda spokes offered during installation. 

**Additional context**
Screenshot attached.

**Comment by paulwhalen** [comment]
![Screenshot from 2022-11-16 15-42-54](https://user-images.githubusercontent.com/3709767/202292776-1978c91c-7018-4736-8086-ba5930a8db53.png)

**Comment by achilleas-k** [comment]
Hi Paul.  You're right, we should enable all the spokes/modules that are enabled in the existing ISO.  I'll look at the iso from  https://getfedora.org/en/iot/download/ and try to replicate it.

**Comment by paulwhalen** [comment]
![osbuild-installation-summary](https://user-images.githubusercontent.com/3709767/210447640-c40c2e67-d48c-4172-b9de-3507ce60323b.png)

**Comment by supakeen** [comment]
Current main of osbuild-composer has the kickstart modules enabled. @paulwhalen can you confirm that `iot-installer` now has everything it needs? :)

**Comment by paulwhalen** [comment]
@supakeen looks great! Thanks for working on this. (apologies for the delay in responding)
![Screenshot from 2023-02-28 10-12-31](https://user-images.githubusercontent.com/3709767/221896057-3a543f6f-2185-41c7-8e48-27419d09cf8f.png)

**Comment by supakeen** [comment]
Perfect, then I'll cose this since it's been merged :)
