### ISSUE TITLE
RFC: Testing for repositories

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#315]
From lorax-composer we have a test_repos.sh file which performs the following scenario: 

1) Start composer with --no-system-repos, that is 0 repositories defined; then start a new compose and expect it to fail. We make sure the failure says "Problem depsolving"

2) Manually define a repo in `/var/lib/lorax/composer/repos.d/`, start composer again (--no-system-repos again), start a compose and wait for it to complete successfully.

I can see osbuild-composer comes with a predefined set of repositories based on the OS type (Fedora/RHEL).  There are also `composer-cli sources` commands which do not appear covered by tests. 

I also tried `composer-cli sources delete fedora` (the default repo) and that didn't crash but also didn't delete the source.

As of now it feels like reproducing the old scenarios verbatim doesn't make sense. It's probably better to add sanity tests for the `sources` command and probably API tests for add/delete behavior. 

Questions: 
* Is there a way to provide additional repos configuration/exclude stock repos for osbuild-composer, other then `composer-cli sources` command ? For example a directory that we're reading from.
* What is the intended behavior for `sources delete` and default sources ? Do we want to allow users to delete absolutely all sources coming from the backend and substitute with their own? I can see how this would be a desirable feature (e.g. do not connect to anything upstream).
* What would be the place where we want this implemented. For the sanity portion I think `osbuild-tests` is the place. Not sure if we want to split this out into a separate binary.

**Comment by teg** [comment]
- It is currently possible to override the built-in repositories, but dropping files in `/etc/osbuild-composer/repositories.d/`. However, I think we should possibly reconsider this behaviour and I don't think it is something worth testing. The intended use-case is to be able to override the stock repositories for the purposes of testing against beta releases where the repositories are net yet in their designated location. As I said, I'm unsure if this is the path forward, so I would not make this the highest priority to test.
 - We should follow the behaviour of the weldr API. That is, if running lorax-composer in the normal mode (without `--no-system-repos`) means that the system repositories cannot be deleted, then we should behave the same way. If, on the other hand, `lorax-composer` allows any repository to be deleted, we should consider doing the same (would require some rework, but we could discuss that in a dedicated issue).
 - I think we the behaviour should be tested as part of `osbuild-test-weldr` (i.e., checking the behavior of deleting of system repos etc). `osbuild-test` could contain a test-case that just checks that the `sources delete` command works at all, but I would not go into verifying the behavior.

@bcl do you have any more thoughts on this?

**Comment by bcl** [comment]
Correct, system repositories are immutable, only the ones added by the sources API can be deleted. I'm planning on adding tests for sources as I expand `osbuild-test-weldr` coverage to the other API routes.

**Comment by jikortus** [comment]
@ted, @bcl Not sure if it the ability to remove (all) repositories is anyhow related to cross-version builds and wouldn't like to digress to some off-topic discussion, but what are the plans to support cross-version builds in terms of repos handling?

**Comment by teg** [comment]
@jikortus I think that's a different and much bigger discussion. We currently do maintain the system repos per version, so it shouldn't be a big problem technically, but we need to decide on how we want to expose this to the user, especially combined with custom sources.
