### ISSUE TITLE
RFC: testing of cloud images: Azure

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#316]
I'm not sure if this will be covered by #299 or will be extra. Opening this issue for tracking purposes.

What lorax-composer test suite does is:
* build an image
* upload to cloud vendor
* boot a VM in the cloud
* ssh to the VM to make sure it is running (checks a few basic things only)
* cleanup after itself

**Comment by teg** [comment]
This makes perfect sense. The idea is to extend the work done in #299 to cover these cases, using our current upload functionality to perform the uploads. So no work is scheduled yet, but this is the natural next step.

**Comment by ondrejbudai** [comment]
I can do this, we already discussed that with @teg, I just haven't had the time to do it yet. :slightly_smiling_face:

**Comment by teg** [comment]
@ondrejbudai is starting work on this in #337.

**Comment by ondrejbudai** [comment]
I will investigate this in the upcoming cycle.

**Comment by ondrejbudai** [comment]
Done in #556
