### ISSUE TITLE
iot-installer failing on aarch64 -  No such file or directory: '/run/osbuild/inputs/data/usr/share/syslinux/isolinux.bin'

### ISSUE THREAD

**Issue by pcdubs** [osbuild/osbuild-composer#3168]
**Describe the bug**
The Fedora IoT compose is currently failing when attempting to build an AArch64 IoT installer: 

https://koji.fedoraproject.org/koji/taskinfo?taskID=94935722

From https://kojipkgs.fedoraproject.org//work/tasks/5722/94935722/aarch64-iot-installer.log.json:

"/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory\n/usr/lib/tmpfiles.d/systemd.conf:23: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory\n/usr/lib/tmpfiles.d/systemd.conf:25: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory\n/usr/lib/tmpfiles.d/systemd.conf:26: Failed to replace specifiers in '/run/log/journal/%m/*.journal*': No such file or directory\n/usr/lib/tmpfiles.d/systemd.conf:29: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory\n/usr/lib/tmpfiles.d/systemd.conf:30: Failed to replace specifiers in '/var/log/journal/%m/system.journal': No such file or directory\n/usr/lib/tmpfiles.d/systemd.conf:32: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory\n/usr/lib/tmpfiles.d/systemd.conf:33: Failed to replace specifiers in '/var/log/journal/%m/system.journal': No such file or directory\nFailed to open file \"/sys/fs/selinux/checkreqprot\": Read-only file system\nTraceback (most recent call last):\n  File \"/run/osbuild/bin/org.osbuild.isolinux\", line 243, in <module>\n    ret = main(args[\"tree\"], args[\"inputs\"], args[\"options\"])\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/run/osbuild/bin/org.osbuild.isolinux\", line 216, in main\n    install(src, dst, mode)\n  File \"/run/osbuild/bin/org.osbuild.isolinux\", line 183, in install\n    shutil.copyfile(src, dst)\n  File \"/usr/lib64/python3.11/shutil.py\", line 256, in copyfile\n    with open(src, 'rb') as fsrc:\n         ^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '/run/osbuild/inputs/data/usr/share/syslinux/isolinux.bin'\n"

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): "fedora-36"
 

**To Reproduce**
Attempt to build an aarch64 Fedora IoT installer in F38.

**Comment by ondrejbudai** [comment]
@gicmo @bcl any ideas what changed in F38?

**Comment by gicmo** [comment]
Only saw this now, due to @bcl's comment, who is 100% correct. Yes, we should _not_ do hybrid boot on aarch64!

**Comment by achilleas-k** [comment]
This is on me.  I added hybrid boot for the edge/iot installers a while ago but did it unconditionally instead of basing it on architecture.

Opened fix PR.
