### ISSUE TITLE
RFC: compose types sanity tests

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#317]
From lorax-composer's test suite we have https://github.com/weldr/lorax/blob/master/tests/cli/test_compose_sanity.sh which does the following things:

* Calls `composer-cli compose types` and asserts the list matches a hard-coded value. This is dependent on the CPU arch we're running on. `compose types` is executed in `osbuild-tests` but the output is not checked. The list of output types can also be checked elsewhere, e.g. in API tests

* Starts a compose, waits for it to actually be running, wait for anaconda process to be present and then cancel the running compose. Expect `compose info $UUID` to return 1; expect `/var/run/anaconda.pid` to not exist. 

* Then start another compose again

^^^ the 2 items above were related to anaconda bug IIRC.

* Wait for compose to FINISH, download the resulting image and then assert internal locations for lorax-composer.

^^^ the download part is already covered in `osbuld-tests`, testCompose() without checking anything else, just making sure we can download successfully.

Questions: 
* do we want to check the list of supported compose types ? In the past this has lead to the need to update the test suite when new output types have been introduced. I don't recall having any errors or bugs reported in this area.  

* Do the cancel & start again scenarios apply for osbuild-composer ? Doesn't seem like they do.

**Comment by teg** [comment]
Thanks for writing this up.
 - I think verifying the output types would be a fine test as part of the welder tests. The benefit of having the tests in the upstream code base is that keeping this up-to-date should be fairly straight-forward, as any time people change them they are forced to also update the test suite.
 - Again, this would be something to potentially test in the weldr tests. Though I think we should restrict ourselves to the behavior of the API, not go looking for what processes are running etc. We currently do not make no guarantees about how long it takes to cancel the actual osbuild run after calling `cancel`, but from the API point of view it should immediately appear to be cancelled.

**Comment by atodorov** [comment]
@bcl I've explored api_test.go to add a test for /compose/types and assert the list of supported compose types.

The addition of a new test function is rather easy but I see that `createWeldrAPI` receives something called a fixture and I can't see how to make it talk to a real running API server instead of a mocked one. 

With `rpmmd_mock.BaseFixture` I only get a qcow2 compose in the list of available types which isn't what I want. Can you give me a hint where to look or if it is even possible to run an API test against a real API server?

**Comment by bcl** [comment]
The api_test.go code is a unit test, it runs against the mocked server code, not a live server.

I'm currently planning on adding compose tests to internal/client/compose_test.go which will cover this.

**Comment by atodorov** [comment]
The only remaining portion for test coverage is the cli sanity part:
- check the supported compose types against a well known list
- start, cancel, start again the compose:

That would be covered in https://github.com/weldr/lorax/pull/1007 or subsequent pull requests so I'm closing this.
