### ISSUE TITLE
RFC: blueprint sanity tests

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#318]
From https://raw.githubusercontent.com/weldr/lorax/master/tests/cli/test_blueprints_sanity.sh:

1) list all blueprints & verify expected examples are there
2) save a blueprint & verify it creates .toml file in the local directory, toml file contains blueprint name, some expected packages
3) saving a non-existing blueprint exists with 1
4) push new blueprint - verify it is found in the output of `blueprints list`.  Also verified against internal location
5) blueprints show - verify that output matches the toml file contents verbatim
6) Start with a blueprint version 0.0.1, append a change to the toml file and push it again. Verify version is 0.0.2 - that is version was incremented automatically
7) blueprints delete - verify list doesn't contain the deleted BP, also verify against internal location
8) push a BP, delete it and then start a compose with the deleted BP name - expect it was not possible to do this, exit code 1. IIRC this exists because of a bug which allowed starting composes with deleted blueprints

Note: in osbuild-tests there's hardly any coverage for blueprints. I still haven't examined API tests in details.

**Comment by teg** [comment]
I think, again, the behaviour here should be mostly verified in the API tests, which @bcl is looking into. We may do some more basic sanity tests in the cli tests, just to make sure the calls work at all (but I would not verify the details of the behaviour).

**Comment by jikortus** [comment]
@teg I agree basically with all you said - checks on API level that actually cover the blueprints functionality seem fine to me, but we should also do at least some basic test for blueprint handling for `composer-cli` just to check it handles blueprints as expected.

**Comment by bcl** [comment]
https://github.com/osbuild/osbuild-composer/blob/master/internal/client/blueprints_test.go should cover all of these, I think.

**Comment by jikortus** [comment]
@bcl Yes, `blueprints_test.go` covers this area thoroughly, but compared to the test we have for `lorax-composer`, it doesn't cover the integration with `composer-cli`. We need to cover `composer-cli` as well, as it's one of the user-facing tools to directly interact with osbuild-composer.

The only questions (IMHO) are if we should include those tests in the osbuild-composer test suite and how/when we should execute them - I think we should include them in osbuild-composer integration tests :).

**Comment by atodorov** [comment]
@jikortus  see `cmd/osbuild-tests/main_test.go` - there are multiple commented out lines for the blueprints commands. The only one which is implemented is "blueprints list".

That's the place to add integration tests which go through the cli. There is very little (almost none) checking as to what the actual output of these commands is because that is verified in other layers of the test suite. If the commands don't error out then we accept that everything is fine.

See `func TestSources` in that file for an example of a group of tests which need a common setup.

**Comment by atodorov** [comment]
IMO the remaining composer-cli testing is covered in https://github.com/weldr/lorax/pull/1007 and there is also test coverage in https://github.com/osbuild/osbuild-composer/blob/master/internal/client/blueprints_test.go. 

The remaining/commented out sections of `cmd/osbuild-tests/main_test.go` will close any gaps. I will open a separate issue for the commented out sections.
