### ISSUE TITLE
Fedora37 edge ostree commit cannot boot with virt-install

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3216]
Issue description:
ostree.sh test failed in these two update snapshot PR:
https://github.com/osbuild/osbuild-composer/pull/3200
https://github.com/osbuild/osbuild-composer/pull/3215

Error log output:
sudo virt-install  --initrd-inject=/tmp/tmp.R5D6LW8row/ks.cfg --extra-args="inst.ks=file:/ks.cfg console=ttyS0,115200" --name=test --disk path=/var/lib/libvirt/images/osbuild-composer-ostree-test-21e77d89-c851-48f4-bb25-336ae58b6a4a.qcow2,format=qcow2 --ram 2048 --vcpus 2 --network network=integration,mac=34:49:22:B0:83:30 --os-type linux --os-variant fedora-unknown --location /var/lib/libvirt/images/boot.iso --noautoconsole --wait=-1 --noreboot
WARNING  --os-type is deprecated and does nothing. Please stop using it.
Starting install...
**ERROR    Couldn't find kernel for install tree.**

This issue can be resolved by adding below parameter to --location, and then everything is fine.
initrd=images/pxeboot/initrd.img,kernel=images/pxeboot/vmlinuz

The root cause is unknown, because this failure only happens in update snapshot pr, suspect it is caused by some new packages. I compared a green PR, the difference I observed is that the successful job installed libvirt of 8.6.0.4, and the failed job installed libvirt of 8.6.0.5. But even if I changed libvirt to 8.6.0.3(cannot find 8.6.0.4 in my local fedora machine), the error still happens.

How to fix it:
1. find out which package caused this,(cannot find it now)
2. or, update ostree.sh to use below --location in virt-install when OS is fedora37
--location /var/lib/libvirt/images/boot.iso,initrd=images/pxeboot/initrd.img,kernel=images/pxeboot/vmlinuz

**Comment by achilleas-k** [comment]
Is this fixed now?  Can we close it?

**Comment by yih-redhat** [comment]
Yes, fixed it. I will close it.
