### ISSUE TITLE
iot-installer produced ISO fails to update "opening repo: opendir(/run/install/repo/ostree/repo): No such file or directory"

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3218]
**Describe the bug**
Systems installed with an iot-installer produced iso, cannot be updated:
```
rpm-ostree upgrade
error: While pulling fedora/rawhide/x86_64/iot: opening repo: opendir(/run/install/repo/ostree/repo): No such file or directory
```

**Environment**
 * Fedora Koji  

**To Reproduce**

* Download a recent Fedora IoT Iso created with osbuild-composer: 
      https://koji.fedoraproject.org/koji/packageinfo?packageID=36296

* Install a VM and attempt an update.
```
rpm-ostree upgrade
error: While pulling fedora/rawhide/x86_64/iot: opening repo: opendir(/run/install/repo/ostree/repo): No such file or directory

cat /etc/ostree/remotes.d/fedora.conf
[remote "fedora"]
url=file:///run/install/repo/ostree/repo
```

Adding a new remote and rebasing to 'fedora-iot' worked to update:
```
ostree remote add fedora-iot --contenturl=mirrorlist=https://ostree.fedoraproject.org/iot/mirrorlist --set=gpgkeypath=/etc/pki/rpm-gpg/ fedora-iot

rpm-ostree rebase -b fedora-iot:fedora/rawhide/x86_64/iot
```

**Comment by paulwhalen** [comment]
This [section](https://pagure.io/fedora-kickstarts/blob/main/f/fedora-iot.ks#_48-60l) of the fedora iot kickstarts shows how it was dealt with previously.

**Comment by nullr0ute** [comment]
I wonder if we need need a blueprint option to specify the ostree remote OTA (Over The Air) update

**Comment by supakeen** [comment]
@paulwhalen @nullr0ute I've been working on this PR (coming a bit later) by replicating the `%post` section in the kickstart through `osbuild` and `osbuild-composer`.

Currently the kickstart always sets the ostree remote to the Fedora upstream one after install. I would like to set the ostree remote to the one supplied during image build time after install.

Is that OK or *must* it be the Fedora upstream?

> I wonder if we need need a blueprint option to specify the ostree remote OTA (Over The Air) update

What is the "remote OTA"?

**Comment by supakeen** [comment]
So, after speaking with @ondrejbudai there's two ways I can go with the PR.

1. Include an RPM which contains the ostree remote information.
2. Write the ostree remote information in the kickstart stage's `%post` as the current kickstart does.

I've built 2, but would prefer 1. :)

**Comment by ondrejbudai** [comment]
@paulwhalen, @nullr0ute, can you please have a look at the solutions that Simon proposed and give us a guidance. We would love to close this asap to finish our preparations for Fedora 38. ;)

**Comment by paulwhalen** [comment]
I would agree with @supakeen , #1 would be preferable and can be used as needed.

**Comment by ondrejbudai** [comment]
No action required on our side, the IoT team will ship the remotes in an RPM.

**Comment by achilleas-k** [comment]
Once the rpm is shipped, we'd probably want to remove the hard-coded remote in the iot-raw-image (and add the rpm to our package set):
https://github.com/osbuild/osbuild-composer/blob/0e4a5b34b214a6496b22f808fae402f88bebe6a2/internal/distro/fedora/images.go#L397-L402

Should we open a separate issue for this?
