### ISSUE TITLE
AArch64 iot-raw-image should use '0x06' for ESP partition type (Raspberry Pi compatability) 

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3220]
**Describe the bug**
To be bootable on the Raspberry Pi family of SBC's, the ESP partition should be formatted as '0x06'. 

Fedora 37 disk Image (produced with ImageFactory):
```
fdisk -l Fedora-IoT-37-20220910.0.aarch64.raw
Disk Fedora-IoT-37-20220910.0.aarch64.raw: 4 GiB, 4294967296 bytes, 8388608 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x97a847b7

Device                                Boot   Start     End Sectors  Size Id Type
Fedora-IoT-37-20220910.0.aarch64.raw1 *       2048 1028095 1026048  501M  6 FAT16
Fedora-IoT-37-20220910.0.aarch64.raw2      1028096 3125247 2097152    1G 83 Linux
Fedora-IoT-37-20220910.0.aarch64.raw3      3125248 8386559 5261312  2.5G 83 Linux
```
Fedora 38 disk image (produced with Osbuild):
```
fdisk -l Fedora-IoT-38.20230112.0-20230112.0.aarch64.raw
Disk Fedora-IoT-38.20230112.0-20230112.0.aarch64.raw: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: D209C89E-EA5E-4FBD-B161-B461CCE297E0

Device                                             Start      End  Sectors  Size Type
Fedora-IoT-38.20230112.0-20230112.0.aarch64.raw1    2048  1028095  1026048  501M EFI System
Fedora-IoT-38.20230112.0-20230112.0.aarch64.raw2 1028096  3125247  2097152    1G Linux filesystem
Fedora-IoT-38.20230112.0-20230112.0.aarch64.raw3 3125248 20971486 17846239  8.5G Linux filesystem
```

**Environment**
 * Fedora Koji 

**Additional context**
Bug with more context:
https://bugzilla.redhat.com/show_bug.cgi?id=1975375

**Comment by bcl** [comment]
FYI 0xEF is correct if these systems are EFI and you are using msdos partitioning:
https://uefi.org/specs/UEFI/2.10/05_GUID_Partition_Table_Format.html#legacy-master-boot-record-mbr
If the rPi isn't recognizing that then it is buggy, and while a workaround may be needed for the Pi, make sure not to break it for everything else.

But really, you should be using GPT partitioning on EFI systems.

**Comment by supakeen** [comment]
I've had some talks around and have ended up with the following:

1. A hybrid partitioning approach is used, this is where a GPT is written but instead of the default GPT approach of claiming the entire disk in the DOS partition table an actual partition table is written to the DOS partition table to (at a minimum) identify the ESP.
2. This is because (some) ARM devices will read the DOS partition table to find the ESP, often with a custom DOS partition id.
3. The start of the first partition is moved to 8MB from the start of the disk, this is because some ARM systems reserve this disk space for firmware.

**Comment by supakeen** [comment]
Looking closer at the ImageFactory provided images they only have a DOS partition table so I'll mimic that.

**Comment by supakeen** [comment]
The linked PR, #3246 has made the necessary changes to provide a raw image that is the same as the one provided by ImageFactory. While there's some discussion on where the changes should live code-wise the produced image should be good.

@paulwhalen could you confirm that the image is good? I can either provide you with a built image or you can check out the above PR. If all is good then I can merge the PR :)

**Comment by paulwhalen** [comment]
The change looks good for aarch64, I am not sure if we want this for x86_64 though, @nullr0ute can you confirm?

**Comment by ondrejbudai** [comment]
Discussed this with Peter, and we decided that we will switch x86_64 to GPT.

For aarch64, we want to leave 8 MiB at the beginning of the disk (after MBR, before the first partition).

**Comment by supakeen** [comment]
Merged, followup for 8MB offset next.

**Comment by paulwhalen** [comment]
Looking at the disk images today, the partitioning looks right:

fdisk -l Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw
Disk Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw: 4 GiB, 4294967296 bytes, 8388608 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xc1748067

Device                                           Boot   Start     End Sectors  Size Id Type
Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw1 *       2048 1028095 1026048  501M  6 FAT16
Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw2      1028096 3125247 2097152    1G 83 Linux
Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw3      3125248 8388607 5263360  2.5G 83 Linux

However  I can't mount the first partition. 

Image here - https://kojipkgs.fedoraproject.org/compose/iot/Fedora-IoT-38-20230329.0/compose/IoT/aarch64/images/Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw.xz

**Comment by paulwhalen** [comment]
The latest F38 disk images (38.20230329.0) no longer boot in a vm, and drop to a uefi shell.

**Comment by supakeen** [comment]
Seems like I am not able to mount the first partition on that image either. I'll investigate.

```
user@muja tmp € fdisk -l Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw
Disk Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw: 4 GiB, 4294967296 bytes, 8388608 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xc1748067

Device                                           Boot   Start     End Sectors  Size Id Type
Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw1 *       2048 1028095 1026048  501M  6 FAT16
Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw2      1028096 3125247 2097152    1G 83 Linux
Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw3      3125248 8388607 5263360  2.5G 83 Linux
user@muja tmp € sudo mount -t vfat -o offset=2048 Fedora-IoT-38.20230329.0-20230329.0.aarch64.raw /mnt/iot/boot
mount: /mnt/iot/boot: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
user@muja tmp € dmesg | tail -n5
[41946.296279] FAT-fs (loop0): bogus number of reserved sectors
[41946.296282] FAT-fs (loop0): Can't find a valid FAT filesystem
[42024.802529] loop0: detected capacity change from 0 to 8388604
[42024.802804] FAT-fs (loop0): bogus number of reserved sectors
[42024.802807] FAT-fs (loop0): Can't find a valid FAT filesystem

**Comment by supakeen** [comment]
Ok this should now be complete, I'll close this ticket.
