### ISSUE TITLE
Fedora IoT: Rawhide(F39) composes failing due to "Unsupported distribution" in osbuild

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3306]
**Describe the bug**
Fedora 38 has now branched, Fedora 39 is now Rawhide. When attempting a Fedora IoT compose of Rawhide osbuild tasks fail with the error: "Unsupported distribution" .

Koji Task - https://koji.fedoraproject.org/koji/taskinfo?taskID=97639760

**Environment**
 * Fedora Infra, Koji

**To Reproduce**
Attempt to run a Rawhide compose. 

**Expected behavior**
F39 compose

**Comment by ondrejbudai** [comment]
The PR was merged, I will deploy this to prod later today/tomorrow.

**Comment by supakeen** [comment]
@ondrejbudai Can I assign this to you so you can close when deployed?

**Comment by ondrejbudai** [comment]
Deployed.
