### ISSUE TITLE
RPi firmware and Uboot missing from esp partition on aarch64 iot disk images

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3312]
**Describe the bug**
The RPi firmware and Uboot need to be copied to the esp partition on aarch64 Fedora IoT disk images in Fedora 38. Currently the files are on the disk image but not yet copied to the correct location.

**Environment**
 * Fedora 38
 * Koji 

**To Reproduce**
Create an aarch64 Fedora IoT disk image in F38. 

**Expected behavior**
Resulting image should be bootable on the RPi family of SBC's

**Additional context**
Snippet from the Fedora IoT kickstart that copies Uboot:

<pre class="syntaxhighlightblock"><code class="hljs bash">
# Setup Raspberry Pi uboot
if [[ $arch == "aarch64" ]]; then
cp -P /usr/share/uboot/rpi_3/u-boot.bin /boot/efi/rpi3-u-boot.bin
cp -P /usr/share/uboot/rpi_4/u-boot.bin /boot/efi/rpi4-u-boot.bin
cp -P /usr/share/uboot/rpi_arm64/u-boot.bin /boot/efi/rpi-u-boot.bin
fi
</code></pre>

The RPi firmware files are on the disk image in '/usr/lib/ostree-boot/efi/'  but should also be copied to '/boot/efi/' 

RPi Firmware packages:
bcm283x-overlays-20230118-1.2578acb.fc38.aarch64
bcm2835-firmware-20230118-1.2578acb.fc38.aarch64
bcm283x-firmware-20230118-1.2578acb.fc38.aarch64
bcm2711-firmware-20230118-1.2578acb.fc38.aarch64

**Comment by ondrejbudai** [comment]
@nullr0ute please clarify whether we can simplify the copying

**Comment by nullr0ute** [comment]
So confirmed we just need to do the following to support all current generations of the RPi on aarch64:

cp -P /usr/share/uboot/rpi_arm64/u-boot.bin /boot/efi/rpi-u-boot.bin

**Comment by paulwhalen** [comment]
The firmware files also need to end up there as well, currently they are installed to '/usr/lib/ostree-boot/efi/'

**Comment by supakeen** [comment]
I'm implementing this at the moment but had a thought (that might be entirely wrong), why don't the RPMs for these files place them in `/boot/efi`? @paulwhalen, @nullr0ute.
