### ISSUE TITLE
Set uefi-preferred for AWS AMI cloud images by default

### ISSUE THREAD

**Issue by nullr0ute** [osbuild/osbuild-composer#3356]
On AWS there's a new uefi-preferred flag that should be set by default for AMI cloud image. Details can be found in the Fedora change: https://fedoraproject.org/wiki/Changes/CloudEC2UEFIPreferred

**Comment by runcom** [comment]
> On AWS there's a new uefi-preferred flag that should be set by default for AMI cloud image. Details can be found in the Fedora change: https://fedoraproject.org/wiki/Changes/CloudEC2UEFIPreferred

I think this is a feature that has to be turned on when registering the ami with aws - not sure what has to be done on the osbuild-composer side of the world on-prem

**Comment by ondrejbudai** [comment]
There are basically two things we need to do:

1) Change the partitioning and the bootloader setup in order to support both legacy and UEFI.
2) Flip in the switch in the uploading code in composer to register the image as uefi-preferred.

**Comment by ondrejbudai** [comment]
This is done for quite some time! :)
