### ISSUE TITLE
Build fails becasue of an error getting the Autoscaling instances

### ISSUE THREAD

**Issue by matoval** [osbuild/osbuild-composer#3377]
**Describe the bug**

Osbuild build fails when building installer and ami images when running on aws.
The[ infra.osbuild Ansible Collection](https://github.com/redhat-cop/infra.osbuild) uses aws ec2 instances for our pipeline. Part of our pipeline is testing different image builds, currently installer and ami images are failing with the message `Error getting the Autoscaling instances: AccessDenied`
The pipeline ec2 instances do not have Autoscaling permission and we need a way to avoid Osbuild from Autoscaling .

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): rhel-8.4, rhel-8.5, rhel-8.6, rhel-8.7, rhel-9.0
 * osbuild-composer version (`rpm -qi osbuild-composer`): 62

**To Reproduce**
 * *for example starting osbuild-composer.service or running composer-cli command, don't forget to include all configuration files you created**
 *[ Run setup_server role](https://github.com/redhat-cop/infra.osbuild/tree/main/roles/setup_server)
 * [Run builder role](https://github.com/redhat-cop/infra.osbuild/tree/main/roles/builder)
Current blueprint:

`name = "test_blueprint_aap"
description = "test_blueprint_aap"
distro = "centos-8"
version = "0.0.1"

[[packages]]
name = "vim-enhanced"
version = "*"

[[packages]]
name = "git"
version = "*"

[[packages]]
name = "ansible-core"
version = "*"

[customizations]

[[customizations.user]]
name = "core"
description = "test user"
password = "openshift"
key = "ssh-rsa FAKEPUBKEY"
groups = ["users", "wheel"]`

**Expected behavior**

ami and installer images build successfully in our aws ec2 pipeline

**Additional context**

ami and installer images build fail after the build starts

**Comment by ondrejbudai** [comment]
Hi! The error message about autoscaling groups is unfortunately confusing, but it's harmless. No builds are ever failed due to this error.

The actual image build is failing. Can you post the compose result? `composer-cli compose results COMPOSE_ID` will get you the right file. Also, is there anything in `journalctl`?
