### ISSUE TITLE
tests/image: Test vmdk images on Vmware

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#338]
I see that vmdk images can be built so we should start exploring the option of uploading them to vCenter and booting an actual VM from the result.  QE already has access to an appropriate environment to launch vmware VMs.

**Comment by teg** [comment]
This makes sense to me, though I think it should be done as a follow-up to #337 using the same sort of methodology (aiming to always use our internal upload infrastructure for the tests as well as the upload functionality). We currently lack the vCenter integraiton though, so it would be some time out. Is the current setup you have publicly available anywhere? Could you link to that so we could get some better idea of what it would entail?

**Comment by atodorov** [comment]
> I think it should be done as a follow-up to #337 using the same sort of methodology

+1 here. Would be very easy for other folks, especially QE, to just reuse existing functions and encode the scenario for this.

> (aiming to always use our internal upload infrastructure for the tests as well as the upload functionality).

From the POV of the test build+upload should look the same, regardless of which cloud vendor that is, right? 

> Is the current setup you have publicly available anywhere? Could you link to that so we could get some better idea of what it would entail?

It is not public, I will send the details via email.

**Comment by teg** [comment]
Yes, once we have the upload support internally it should all look the same from the tests.
