### ISSUE TITLE
Package name with a wildcard makes blueprints freeze command fail

### ISSUE THREAD

**Issue by stebenoist** [osbuild/osbuild-composer#3393]
For some specific reasons, our users need to define some of their packages in blueprints with a wildcard in the name. This allows them matching with only one package according to current repositories.

The **Blueprints depsolve** command handles correctly the wildcard and returns expected package name but **Blueprints freeze** returns an error.

The image build is OK too.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): Fedora Linux 37
 * osbuild-composer version (`rpm -qi osbuild-composer)`:
 Name        : osbuild-composer
Version     : 77
Release     : 1.fc37
Architecture: x86_64
Install Date: Thu Mar 30 16:30:34 2023
Group       : Unspecified
Size        : 17586
License     : Apache-2.0
Signature   : RSA/SHA256, Wed Mar  8 13:50:01 2023, Key ID f55ad3fb5323552a
Source RPM  : osbuild-composer-77-1.fc37.src.rpm
Build Date  : Wed Mar  8 13:34:25 2023
Build Host  : buildvm-x86-14.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project

**To Reproduce**
Quite easy to reproduce with a simple package like openssh-server even if it doesn't make any sense !
The idea is to target only one package present in repos.

- Blueprint test.toml:
```
name = "test"
description = "test blueprint with wildcard in the package name"
version = "1.0.0"

[[packages]]
name = "openssh-serv*"
version = "*"
```
- Operations:

```
bash-5.2# composer-cli blueprints push test.toml
bash-5.2# composer-cli blueprints depsolve test|grep openssh-serv
    openssh-server-8.8p1-9.fc37.x86_64
bash-5.2# composer-cli blueprints freeze test                  
ERROR: BlueprintsError: test: openssh-serv* missing from depsolve results
bash-5.2#
```

Thanks !

**Comment by bcl** [comment]
Thanks for the report! I didn't take into account the possibility of package name globs when I rewrote the freeze handler and according to the blueprint documentation the package names should not be using globs - https://www.osbuild.org/guides/blueprint-reference/blueprint-reference.html#packages-and-modules so package name globs may be working on accident. But we should fix this.
