### ISSUE TITLE
Create RPM scriptlets for the rcm subpackage

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#340]
https://github.com/osbuild/osbuild-composer/blob/54e27e607ca865d1a7793640ca5f134daea13d45/golang-github-osbuild-composer.spec#L124

 - [ ] Investigate what the RPM scriptlets do and if it makes sense, create them for the rcm subpackage as well.

**Comment by teg** [comment]
This makes sense. I believe the policy is that we should do the systemd scriptlets for all unit files we ship, but we should verify that.

**Comment by msehnout** [comment]
Fixed in #344
