### ISSUE TITLE
RCM API includes official repositories in pipelines

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#341]
When running a compose through the RCM API, the official repositories for a distro are used in addition to the ones supplied by the API.

This is wrong: the semantics of the API is that only those repos that are provided are used. The resulting image might include packages from the wrong repos.

**Comment by teg** [comment]
Agreed, this was not the intention. The `distro` package must be refactored to no longer make the official repositories implicit. As discussed, the official repository logic should be specific to the `weldr` package.

**Comment by msehnout** [comment]
Except for `distro` refactoring, this sounds like something that could make use of a common transformation between the user request and fully defined image build. The transformation function would take care of argument validation (like arch and image type), depsolving (which can also fail). Each API could have its own tweaks to the function: `weldr` would add the repos, `rcm` would add implicit Koji targets.

**Comment by larskarlitski** [comment]
> Except for `distro` refactoring, this sounds like something that could make use of a common transformation between the user request and fully defined image build.

Yes, I think this makes sense (but is out of scope for this issue).
