### ISSUE TITLE
Fedora IoT composes frequently failing with file size mismatch

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3479]
**Describe the bug**

Fedora IoT composes frequently fail with:

"Could not import build into koji: Fault(1000): File size 731906048 for Fedora-IoT-38.20230531.0-20230531.0.aarch64.raw.xz (expected 732804884) doesn't match. Corrupted upload?"

Examples:
https://koji.fedoraproject.org/koji/taskinfo?taskID=101839225
https://koji.fedoraproject.org/koji/taskinfo?taskID=101729759
https://koji.fedoraproject.org/koji/taskinfo?taskID=101689128

**Environment**
 * Fedora Koji 

**To Reproduce**
 * * Attempt daily Fedora IoT compose

**Expected behavior**
Completed compose. 

**Additional context**

Previously the recommendation was to rerun the compose, unfortunately this is failing more often than it succeeds and most days we do not get a successful compose due to issues with the osbuild tasks.

**Comment by paulwhalen** [comment]
> Hi Paul, I hopefully fixed the issue in #3399. I'm currently deploying it, so let's give it few days and see whether it indeed fixed the issue.

Apologies, I thought it had been deployed already.

**Comment by ondrejbudai** [comment]
![successful osbuildImage jobs in Koji](https://github.com/osbuild/osbuild-composer/assets/119861/93eb08f6-3af2-47ec-bea7-b14571814525)


I think that the fix worked. Feel free to reopen if the issue reappears!
