### ISSUE TITLE
Local target only supports uploading one file

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#348]
https://github.com/osbuild/osbuild-composer/pull/347 changes the local upload target to only upload a single file from the result directory. That's a bit smelly (we ought to know the name) and will not work for pipelines that have multiple outputs (if we ever have those).

I see a few options of fixing that:
1. Include the filename(s) to upload in the UploadTarget that's passed to the job.
2. Base the filename on the compose id (this only works for one and might be a layer violation: `distro` package doesn't necessarily know the compose id yet)
3. Upload all files

Curious to hear your thoughts.

**Comment by teg** [comment]
Until we need to support multiple files, I suggest just fixing the filename of all image types as this is only internal and use that unconditionally.

**Comment by ondrejbudai** [comment]
I don't think we should bother with uploading multiple files - it's not needed now and we would need to change the store in a possibly significant way to support that.

I think both the Tom's solution and the 1) work for me.

**Comment by larskarlitski** [comment]
> I think both the Tom's solution and the 1) work for me.

Turns out, (1) isn't so easy, because we get upload requests from the outside. It requires a bit more thinking when to inject the source file name.

#366 implements Tom's solution.
