### ISSUE TITLE
iot-simplified-installer image cannot httpboot on fedora 38

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3525]
**Describe the bug**
cannot httpboot iot-simplified-installer image , virt-installer command took too long and hang there.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): fedora-38
 * osbuild-composer version (`rpm -qi osbuild-composer)` 

**To Reproduce**
1. build iot-container image and start it in podman.
2. build iot-simplified-installer image
3. extract image to http location, and change grub config file
sudo sed -i 's/timeout=60/timeout=10/' "${GRUB_CFG}"
sudo sed -i 's/coreos.inst.install_dev=\/dev\/sda/coreos.inst.install_dev=\/dev\/vda/' "${GRUB_CFG}"
sudo sed -i 's/linux \/images\/pxeboot\/vmlinuz/linuxefi \/httpboot\/images\/pxeboot\/vmlinuz/' "${GRUB_CFG}"
sudo sed -i 's/initrd \/images\/pxeboot\/initrd.img/initrdefi \/httpboot\/images\/pxeboot\/initrd.img/' "${GRUB_CFG}"
sudo sed -i "s/coreos.inst.image_file=\/run\/media\/iso\/${IMAGE_NAME}/coreos.inst.image_url=http:\/\/192.168.100.1\/httpboot\/disk.img.xz/" "${GRUB_CFG}"

4. boot it
sudo virt-install --name="${IMAGE_KEY}-httpboot"\
                  --disk path="${LIBVIRT_IMAGE_PATH}",format=qcow2 \
                  --ram 3072 \
                  --vcpus 2 \
                  --network network=integration,mac=34:49:22:B0:83:30 \
                  --os-type linux \
                  --os-variant "$OS_VARIANT" \
                  --pxe \
                  --boot "${BOOT_ARGS}" \
                  --tpm backend.type=emulator,backend.version=2.0,model=tpm-crb \
                  --nographics \
                  --noautoconsole \
                  --wait=-1 \
                  --noreboot

5. above command and grub config can be found at https://github.com/virt-s1/rhel-edge/blob/main/ostree-simplified-installer.sh#L656

**Expected behavior**
should boot

**Additional context**

**Comment by yih-redhat** [comment]
related to pr https://github.com/osbuild/osbuild-composer/pull/3282

**Comment by runcom** [comment]
@yih-redhat does it work by booting the simplified-installer iso directly?

**Comment by yih-redhat** [comment]
yes, boot directly works well.

**Comment by yih-redhat** [comment]
Closing  this bug, because I can httpboot iot-simplified-installer now.
