### ISSUE TITLE
iot-simplified-installer fdo client does not work as expected

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3527]
**Describe the bug**
/boot/device-credentials presents, but there is no log for fdo-client-linuxapp.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): fedora-38
 * osbuild-composer version (`rpm -qi osbuild-composer)`

**To Reproduce**
1. Setup fdo-admin-cli and start it at http://${FDO_SERVER_ADDRESS}:8080
2. build iot-container
3. build iot-simplified-installer
name = "installer"
description = "A rhel-edge simplified-installer image"
version = "0.0.1"
modules = []
groups = []

[customizations]
installation_device = "/dev/vda"

[customizations.fdo]
manufacturing_server_url="http://${FDO_SERVER_ADDRESS}:8080"
diun_pub_key_insecure="true"

4. boot iot-simplified-installer and login with user admin. check fdo status
[admin@localhost ~]$ systemctl status fdo-client-linuxapp.service 
○ fdo-client-linuxapp.service - FDO client
     Loaded: loaded (/usr/lib/systemd/system/fdo-client-linuxapp.service; disabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)

[admin@localhost boot]$ journalctl -u fdo-client-linuxapp
-- No entries --

[admin@localhost boot]$ ls
boot  device-credentials  efi  fdo-client-env  grub2  loader  loader.1  lost+found  ostree

[admin@localhost boot]$ rpm-ostree status
State: idle
Deployments:
● fedora-iot:fedora/38/x86_64/iot
                  Version: 38 (2023-06-27T12:30:29Z)
                   Commit: b672c524c058c5c617d739fba732817c3bf6584b4a94505cd16adb456a062379

**Expected behavior**

**Additional context**

**Comment by yih-redhat** [comment]
related to pr https://github.com/osbuild/osbuild-composer/pull/3282

**Comment by yih-redhat** [comment]
Verified with new fix, and fdo onboarding failed:

Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:  2023-06-29T03:49:35.308Z INFO  fdo_client_linuxapp > Performing TO2 protocol, URL: "http://10.0.188.20:8081"
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:  2023-06-29T03:49:35.380Z INFO  fdo_client_linuxapp::serviceinfo > Creating file "/etc/sudoers.d/fdouser" with 32 bytes (mode 384)
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:  2023-06-29T03:49:35.392Z INFO  fdo_client_linuxapp::serviceinfo > Initiating disk re-encryption, disk-label: /dev/vda4, pin: tpm2, config: {}, reencrypt: true
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]: Device /dev/vda4 does not exist or access denied.
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:  2023-06-29T03:49:35.392Z ERROR fdo_client_linuxapp              > ServiceInfo failed, error: Error processing returned serviceinfo
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]: Caused by:
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:     0: Error executing clevis
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:     1: Error executing disk encryption for disk label /dev/vda4
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:     2: Error opening device /dev/vda4
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:     3: IO error occurred: Block device required (os error 15)
Jun 29 03:49:35 localhost.localdomain fdo-client-linuxapp[1106]:  2023-06-29T03:49:35.394Z ERROR fdo_client_linuxapp              > Error performing TO2 ownership protocol

**Comment by 7flying** [comment]
@yih-redhat does this happen on top of #3529 ?

**Comment by yih-redhat** [comment]
@7flying yes.

**Comment by yih-redhat** [comment]
Per discussion with Antonio, I will change /dev/vda4 to /dev/vda3 in serviceinfo config file for fedora iot-simplified-installer image in our test cases. This is just a test for now, may change it later.

yih-redhat:
is this a workaround? I mean, if customer setup fdo servers in their work environment, there might be rhel, fedora or other devices, if I change to /dev/vda3 for serviceinfo, maybe it works for fedora, but will fail for rhel.
runcom:
that's by design - fleets aren't all the same, there will be per-device config and other things afaict
so, if fedora has only 3 partitions and you specify vda4, it's correct to fail
and thus we'd need to test cases
but this is just a test for now, maybe we need the  bios partition

**Comment by yih-redhat** [comment]
Closing this bug, changing to /dev/vda3 works on fedora.
