### ISSUE TITLE
iot-simplified-installer /sysroot lv size should be 9G on fedora 38

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3529]
**Describe the bug**
/sysroot lv size should be 9G

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): fedora-38
 * osbuild-composer version (`rpm -qi osbuild-composer)`

**To Reproduce**
1. build iot-simplified-installer image and boot it, check check /sysroot lv size
[admin@localhost ~]$ df -h | grep sysroot
/dev/mapper/rootvg-rootlv  2.9G  1.9G  877M  69% /sysroot

**Expected behavior**
/sysroot lv size should be 9G

**Additional context**

**Comment by yih-redhat** [comment]
[admin@localhost ~]$ df -h | grep sysroot
/dev/mapper/rootvg-rootlv  2.9G  1.9G  878M  69% /sysroot
[admin@localhost ~]$ lsblk
NAME                                          MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINTS
sr0                                            11:0    1    2K  0 rom
vda                                           252:0    0   20G  0 disk
├─vda1                                        252:1    0  501M  0 part  /boot/efi
├─vda2                                        252:2    0    1G  0 part  /boot
└─vda3                                        252:3    0 18.5G  0 part
  └─luks-344cb5d6-c58e-4397-acb6-25ccf80fe8a4 253:0    0 18.5G  0 crypt
    └─rootvg-rootlv                           253:1    0    3G  0 lvm   /var
                                                                        /sysroot/ostree/deploy/fedora/var
                                                                        /usr
                                                                        /etc
                                                                        /
                                                                        /sysroot

**Comment by yih-redhat** [comment]
related to pr https://github.com/osbuild/osbuild-composer/pull/3282

**Comment by achilleas-k** [comment]
The coreos-installer should be growing the root filesystem after installation to fill the disk and the raw image file in the simplified installer is already set to 10 GiB.

I did a local test and experienced the following error.
![image](https://github.com/osbuild/osbuild-composer/assets/2369197/b83c3d9d-19dd-41e1-b67b-52dad1d19200)

@yih-redhat Are you seeing anything like that in your testing?

**Comment by yih-redhat** [comment]
> The coreos-installer should be growing the root filesystem after installation to fill the disk and the raw image file in the simplified installer is already set to 10 GiB.
> 
> I did a local test and experienced the following error. ![image](https://user-images.githubusercontent.com/2369197/269598288-b83c3d9d-19dd-41e1-b67b-52dad1d19200.png)
> 
> @yih-redhat Are you seeing anything like that in your testing?

No, I didn't see this before, but I will keep an eye on it as I am going to test the fix in https://github.com/osbuild/images/pull/169
