### ISSUE TITLE
Extend the test suite with support for alternative architectures

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#353]
### ARM

 - [x] Request support for `partuuid` in OSBuild because aarch64 requires uefi and image-info tests require this id to be stable. ([Explanation of different UUIDs related to disks](https://unix.stackexchange.com/questions/375548/what-is-uuid-partuuid-and-ptuuid)) [1]
 - [x] As a temporary solution for the unstable `partuuid` remove the image-info part from the test and [only run the boot test](https://github.com/osbuild/osbuild-composer/blob/b0e28689fb1123c05fb2221bd1121a43db6429c0/cmd/osbuild-image-tests/main_test.go#L230)
 - [x] Extend the `/cmd/osbuild-image-tests/context-managers.go` file with support for aarch64, because it is currently [x86_64 specific](https://github.com/osbuild/osbuild-composer/blob/master/cmd/osbuild-image-tests/context-managers.go#L94)
 - [x] Generate test cases for aarch64 using the test case generation script
 - [x] Manually run the `aarch64` tests to make sure it works

### PowerPC and IBM s390x

- [ ] Reimplement support for legacy boot to match the latest update in osbuild: https://github.com/osbuild/osbuild/pull/327
- [ ] Add support for following arches and distros into appropriate `distro` subpackage:

Arch/Distro | `fedora30` | `fedora31`
------------ | ------------- | -------------
IBM `s390x` | □ | □
`ppc64le` | □ | □

- [ ] Extend the test generation script with support for `s390x` and `ppc64le`
- [ ] Manually run the `s390x` and `ppc64le` tests in any available IaaS offering (Beaker, PowerHub?)

Related PRs:
 * #376
 * https://github.com/osbuild/osbuild-composer/pull/395
 * https://github.com/osbuild/osbuild/pull/306 (authored by gicmo)
 * https://github.com/osbuild/osbuild-composer/pull/470
 * https://github.com/osbuild/osbuild-composer/pull/459
 * https://github.com/osbuild/osbuild-composer/pull/471
 * https://github.com/osbuild/osbuild-composer/pull/482
 * https://github.com/osbuild/osbuild-composer/pull/493
 * https://github.com/osbuild/osbuild-composer/pull/472
 * https://github.com/osbuild/osbuild-composer/pull/488
 * https://github.com/osbuild/osbuild-composer/pull/456
 * https://github.com/osbuild/osbuild-composer/pull/501

**Comment by atodorov** [comment]
> Extend the test generation script with 

Note: we should find a better name for that script b/c "test" is quite overloaded.

**Comment by msehnout** [comment]
ppc64le and s390x will be part of some future cycle

**Comment by atodorov** [comment]
@msehnout FTR are there even cloud vendors who provide ppc64le and/or s390x systems ? Some time ago I searched and didn't find anyone who offers such systems available.

Although Travis CI seems to offer s390x slaves.

**Comment by msehnout** [comment]
As of now, I could not find any, not even the IBM cloud, but I guess these architectures will more likely be used with self-hosted composer. In Red Hat internally, I found people interested in running cockpit-composer on PowerPC.

**Comment by leo-lb** [comment]
@atodorov @msehnout 

FWIW Travis CI supports ppc64le

https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures

You can otherwise have a list of cloud providers offering IBM POWER systems here: https://developer.ibm.com/linuxonpower/cloud-resources/
