### ISSUE TITLE
iot-simplified-installer fdo re-encryption failed

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3547]
**Describe the bug**
Found 'cipher: cipher_null-ecb' in lucksDump output, which should not be there if fdo encryption works as expected.
This issue related to https://github.com/osbuild/osbuild-composer/pull/3282
I found this issue when httpboot iot-simplified-installer image, not sure if it only happens with httpboot

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 * osbuild-composer version (`rpm -qi osbuild-composer)`

**To Reproduce**
1. httpboot vm with iot-simplified-installer image
2. install sanely failing health check unit and reboot
3. wait for vm to boot with previous commit
4. check fdo re-encryption status, run command 'cryptsetup luksDump /dev/vda3', output is:
[admin@localhost ~]$ sudo cryptsetup luksDump /dev/vda3
[sudo] password for admin: 
LUKS header information
Version:       	2
Epoch:         	6
Metadata area: 	16384 [bytes]
Keyslots area: 	16744448 [bytes]
UUID:          	160a5796-2eee-41c5-b134-8a3a67dbecf8
Label:         	crypt_root
Subsystem:     	(no subsystem)
Flags:       	(no flags)

Data segments:
  0: crypt
	offset: 16777216 [bytes]
	length: (whole device)
	cipher: cipher_null-ecb
	sector: 512 [bytes]

Keyslots:
  1: luks2
	Key:        256 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      pbkdf2
	Hash:       sha256
	Iterations: 1000
	Salt:       ed 79 d4 60 64 d6 e0 45 ea 49 98 60 5c 45 67 ee 
	            d9 4b 31 08 cd 4c 46 74 53 66 97 7c 2b 85 b2 52 
	AF stripes: 4000
	AF hash:    sha256
	Area offset:163840 [bytes]
	Area length:131072 [bytes]
	Digest ID:  0
Tokens:
  0: clevis
	Keyslot:    1
Digests:
  0: pbkdf2
	Hash:       sha256
	Iterations: 1000
	Salt:       9e 87 87 8c 31 be 27 ed e1 cb b5 a8 c9 63 d9 12 
	            e3 62 63 3d 6c f1 77 00 5f 57 4f 2c 8e 64 a2 03 
	Digest:     92 78 64 60 b3 64 88 b4 74 47 e1 5d aa 69 6a 14 
	            0b 37 5f 56 cc de 2c f6 b1 ac 86 a6 6e 0a 5e fe 

5. check fdo client log, run command 'journalctl -u fdo-client-linuxapp'
-- Boot 88f40c0eb49a45538e8ed1f6fd33dcd2 --
Jul 06 03:25:47 localhost.localdomain systemd[1]: Starting fdo-client-linuxapp.service - FDO client...
Jul 06 03:25:47 localhost.localdomain fdo-client-linuxapp[997]:  2023-07-06T03:25:47.403Z INFO  fdo_client_linuxapp > No usable device credential located, skipping Device Onboarding
Jul 06 03:25:47 localhost.localdomain mv[1015]: /usr/bin/mv: cannot stat '/boot/device-credentials': No such file or directory
Jul 06 03:25:47 localhost.localdomain systemd[1]: fdo-client-linuxapp.service: Deactivated successfully.
Jul 06 03:25:47 localhost.localdomain systemd[1]: Finished fdo-client-linuxapp.service - FDO client.

Comparing to similar log where fdo encryption is successful:

-- Boot 965b5c57275b47b390876ecf4c044e7a --
Jun 29 06:28:45 vm-3 systemd[1]: Starting FDO client...
Jun 29 06:28:45 vm-3 fdo-client-linuxapp[1104]:  2023-06-29T10:28:45.143Z INFO  fdo_client_linuxapp > Device Onboarding marker file "/etc/device_onboarding_performed" exists, not rerunning FDO onboarding
Jun 29 06:28:45 vm-3 fdo-client-linuxapp[1104]:  2023-06-29T10:28:45.152Z INFO  fdo_client_linuxapp::reencrypt > Reencryption of luks-eeabdfca-acef-433d-b4da-84908f381a62 in progress, resuming
Jun 29 06:29:55 vm-3 mv[3174]: /usr/bin/mv: cannot stat '/boot/device-credentials': No such file or directory
Jun 29 06:29:55 vm-3 systemd[1]: fdo-client-linuxapp.service: Deactivated successfully.
Jun 29 06:29:55 vm-3 systemd[1]: Finished FDO client.
Jun 29 06:29:55 vm-3 systemd[1]: fdo-client-linuxapp.service: Consumed 34.304s CPU time.

**Expected behavior**

**Additional context**

**Comment by 7flying** [comment]
this looks like the `device_credentials` were not properly generated. Do you have logs from the manufacturing server?

**Comment by yih-redhat** [comment]
@7flying I made a mistake, for iot-simplified-installer, should use /dev/vda3 in service info config file
Will try again, and close this bug if cannot reproduce.

**Comment by yih-redhat** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2220851 is the root cause.
