### ISSUE TITLE
iot-qcow2-image custom service status is not correct

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3548]
**Describe the bug**
Define customized files ,dirs and services in blueprint, after vm boot, the custom service status is not correct.
This pr is related to https://github.com/osbuild/osbuild-composer/pull/3282

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 * osbuild-composer version (`rpm -qi osbuild-composer)`

**To Reproduce**
1. build iot-container, with blueprint

name = "container"
description = "A base iot-container image"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "python3"
version = "*"

[[packages]]
name = "sssd"
version = "*"

2. build iot-qcow2-image, with blueprint

name = "iot-qcow2"
description = "A iot-qcow2 image"
version = "0.0.1"
modules = []
groups = []

[[customizations.user]]
name = "admin"
description = "Administrator account"
password = "*************"
key = "${SSH_KEY_PUB}"
home = "/home/admin/"
groups = ["wheel"]

[[customizations.directories]]
path = "/etc/custom_dir/dir1"
user = 1020
group = 1020
mode = "0770"
ensure_parents = true

[[customizations.files]]
path = "/etc/systemd/system/custom.service"
data = "[Unit]\nDescription=Custom service\n[Service]\nType=oneshot\nRemainAfterExit=yes\nExecStart=/usr/bin/false\n[Install]\nWantedBy=multi-user.target\n"

[[customizations.files]]
path = "/etc/custom_file.txt"
data = "image builder is the best\n"

[[customizations.directories]]
path = "/etc/systemd/system/custom.service.d"

[[customizations.files]]
path = "/etc/systemd/system/custom.service.d/override.conf"
data = "[Service]\nExecStart=\nExecStart=/usr/bin/cat /etc/custom_file.txt\n"

[customizations.services]
enabled = ["custom.service"]

3. boot vm with iot-qcow2-image, check the status of custom.service, 

Expected result is:
    - ['LoadState'] == 'loaded'
    - ['ActiveState'] == 'active'
    - ['SubState'] == 'exited'
    - ['UnitFileState'] == 'enabled'
Actual result is:
    - "LoadState": "loaded",
    - "ActiveState": "inactive",
    - "SubState": "dead",
    - "UnitFileState": "disabled",

**Expected behavior**

**Additional context**

**Comment by runcom** [comment]
This is likely because we now need presets to enable services in fedora ostree @achilleas-k

**Comment by achilleas-k** [comment]
I suspect that's the case, yes.  @yih-redhat can you add a preset file as well and see if that fixes the issue?

```toml
[[customizations.files]]
path = "/etc/systemd/system-preset/30-test.preset"
data = "enable custom.service\n"
```

and remove the `[customizations.services]` part.

That should work (for now) until we switch to using presets when needed by the blueprint and image type.

**Comment by yih-redhat** [comment]
@achilleas-k Failed to build iot-qcow2-image with this blueprint, I saw this error "cp: cannot create regular file '/run/osbuild/tree/etc/systemd/system-preset/30-test.preset': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911"

Full log:
ul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/systemd.conf:23: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/systemd.conf:25: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/systemd.conf:26: Failed to replace specifiers in '/run/log/journal/%m/*.journal*': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/systemd.conf:29: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/systemd.conf:30: Failed to replace specifiers in '/var/log/journal/%m/system.journal': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/systemd.conf:32: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    /usr/lib/tmpfiles.d/systemd.conf:33: Failed to replace specifiers in '/var/log/journal/%m/system.journal': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    Failed to open file \"/sys/fs/selinux/checkreqprot\": Read-only file system" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    copying '/run/osbuild/inputs/file-64bee67cb58f21e0864a7f096f11a5a65930fd6af39f60b9b15b0bce10ea264e/sha256:64bee67cb58f21e0864a7f096f11a5a65930fd6af39f60b9b15b0bce10ea264e' -> '/run/osbuild/tree/etc/systemd/system/custom.service'" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    copying '/run/osbuild/inputs/file-b12e4aaa312a0d47d2645da8010da985030f0497a3af61a8137ab225bde4371d/sha256:b12e4aaa312a0d47d2645da8010da985030f0497a3af61a8137ab225bde4371d' -> '/run/osbuild/tree/etc/custom_file.txt'" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    copying '/run/osbuild/inputs/file-3858d66c9da0509af1f75847bf49134bf8df01bd712b59ce251826744d3bafe2/sha256:3858d66c9da0509af1f75847bf49134bf8df01bd712b59ce251826744d3bafe2' -> '/run/osbuild/tree/etc/systemd/system/custom.service.d/override.conf'" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    copying '/run/osbuild/inputs/file-7a2e1a148f2f8e86abfdb9bd33d4401b937701f479ceadb2257976424210aede/sha256:7a2e1a148f2f8e86abfdb9bd33d4401b937701f479ceadb2257976424210aede' -> '/run/osbuild/tree/etc/systemd/system-preset/30-test.preset'" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    cp: cannot create regular file '/run/osbuild/tree/etc/systemd/system-preset/30-test.preset': No such file or directory" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    Traceback (most recent call last):" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="      File \"/run/osbuild/bin/org.osbuild.copy\", line 156, in <module>" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="        r = main(_args, _args[\"options\"])" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="      File \"/run/osbuild/bin/org.osbuild.copy\", line 149, in main" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="        subprocess.run(cmd + [src, dst], check=True)" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="      File \"/usr/lib64/python3.11/subprocess.py\", line 571, in run" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="        raise CalledProcessError(retcode, process.args," jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    subprocess.CalledProcessError: Command '['cp', '-a', '--reflink=auto', '--remove-destination', '/run/osbuild/inputs/file-7a2e1a148f2f8e86abfdb9bd33d4401b937701f479ceadb2257976424210aede/sha256:7a2e1a148f2f8e86abfdb9bd33d4401b937701f479ceadb2257976424210aede', '/run/osbuild/tree/etc/systemd/system-preset/30-test.preset']' returned non-zero exit status 1." jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="    " jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=error msg="osbuild job failed: osbuild build failed" jobId=6a8c282c-379b-4dad-b830-f40d406e6911
Jul 06 13:34:11 yih-f38 osbuild-worker[872464]: time="2023-07-06T13:34:11Z" level=info msg="Job '6a8c282c-379b-4dad-b830-f40d406e6911' (osbuild) finished"


Blueprint is as you suggested:
name = "iot-qcow2"
description = "A iot-qcow2 image"
version = "0.0.1"
modules = []
groups = []

[[customizations.user]]
name = "admin"
description = "Administrator account"
password = "*************"
key = "${SSH_KEY_PUB}"
home = "/home/admin/"
groups = ["wheel"]

[[customizations.directories]]
path = "/etc/custom_dir/dir1"
user = 1020
group = 1020
mode = "0770"
ensure_parents = true

[[customizations.files]]
path = "/etc/systemd/system/custom.service"
data = "[Unit]\nDescription=Custom service\n[Service]\nType=oneshot\nRemainAfterExit=yes\nExecStart=/usr/bin/false\n[Install]\nWantedBy=multi-user.target\n"

[[customizations.files]]
path = "/etc/custom_file.txt"
data = "image builder is the best\n"

[[customizations.directories]]
path = "/etc/systemd/system/custom.service.d"

[[customizations.files]]
path = "/etc/systemd/system/custom.service.d/override.conf"
data = "[Service]\nExecStart=\nExecStart=/usr/bin/cat /etc/custom_file.txt\n"

[[customizations.files]]
path = "/etc/systemd/system-preset/30-test.preset"
data = "enable custom.service\n"

**Comment by achilleas-k** [comment]
The parent directory `/etc/systemd/system-preset` should be created first using a `[[customizations.directories]]` option.

**Comment by achilleas-k** [comment]
Great to hear.  Can we close this issue or is there more to do?

**Comment by yih-redhat** [comment]
I will add this to test script, closing this issue.
