### ISSUE TITLE
Create osbuild-composer package in Fedora

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#355]
Goal: get rid of `golang-github-` prefix in the RPM package name

We need to start the whole review process again:
https://fedoraproject.org/wiki/Package_Renaming_Process
And retire the old package afterwards. 

We should also do the same for RHEL.

**Comment by larskarlitski** [comment]
@ondrejbudai you had written up a plan for this some time back, right? Are you ok with pasting it here?

**Comment by ondrejbudai** [comment]
When creating the spec file for osbuild-composer, I unfortunately missed the following paragraph from [golang packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/#_source_packages_src_rpm):

> Source packages that provide a well-known application such as `etcd` MUST be named after the application. End users do not care about the language their applications are written in. But do not name packages after an obscure utility binary that happens to be built by the package.

In other words, the package containing osbuild-composer in Fedora is named golang-github-osbuild-composer while it should be named just osbuild-composer. This is not only against Golang packaging guidelines but it also confuses users. We were able to solve it using `Provides: osbuild-composer` in the specfile but that's hacky and not recommended.

### Proposed solution
Introduce osbuild-composer package to Fedora obsoleting the golang-github-osbuild-composer package. The package renaming process in Fedora is documented [here](https://fedoraproject.org/wiki/Package_Renaming_Process).

As removing the old package is not possible in stable Fedora version, this proposal targets Fedora 33.

### Required steps
1) Modify our current specfile to reflect the name change.
2) Request and successfully pass the package review process.
    We must explicitly state in the review request we want to rename the package and add `Obsoletes` and `Provides` lines to the specfile. More info on [the Fedora wiki](https://fedoraproject.org/wiki/Package_Renaming_Process) and [in the packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#renaming-or-replacing-existing-packages).
3) Remove the old package. More info on [the Fedora wiki](https://fedoraproject.org/wiki/How_to_remove_a_package_at_end_of_life) and in [the packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/deprecating-packages/).

These steps MUST be done before Fedora 33 final freeze. If I understand the Fedora 33 schedule correctly, the earliest date for final freeze is [2020-10-06](https://fedorapeople.org/groups/schedule/f-33/f-33-key-tasks.html).

### Acceptance criteria
1) Fedora 33 contains the osbuild-composer package.
2) Fedora 33 does not contain the golang-github-osbuild-composer package.
3) While upgrading from F32 to F33 the golang-github-osbuild-composer package is cleanly upgraded to the osbuild-composer package.
