### ISSUE TITLE
Use separate functions for test cases in osbuild-tests

### ISSUE THREAD

**Issue by jikortus** [osbuild/osbuild-composer#356]
This is a follow-up to discussion in PR #352. It looks like we could create specialized functions for each test case (or something close to that), instead of the current, generic one (`runComposerCLI`).

**Comment by teg** [comment]
This makes sense to me.

**Comment by jrusz** [comment]
After some further internal discussion we decided to move this along. Some new notes:

- the `composer-cli` calls should be made without `--json` option to mimic how a user would use this
- only the exit code and some very basic output or file assertion should be made (eg. a pushed blueprint is listed or the created image exists)

With this we can separate this issue into sub-tasks like this:

- [ ] `composer-cli blueprints *`
- [ ] `composer-cli compose *`
- [ ] `composer-cli sources *`  (not sure if that works with osbuild-composer)
- [ ] `composer-cli *` (the rest)

I think that there are mainly commands for `blueprints` and `compose` so I would say those are the most important ones. Anything to add @jikortus ?

**Comment by ondrejbudai** [comment]
sources v0 are supported by osbuild-composer, sources v1 are being implemented in #578

**Comment by teg** [comment]
This makes a lot of sense to me. Thanks for working on this!

One question, you said
> a pushed blueprint is listed
What did you have in mind? We will not be parsing any output, right? Just wasn't sure what you meant by "listed" :)

**Comment by jrusz** [comment]
> What did you have in mind? We will not be parsing any output, right? Just wasn't sure what you meant by "listed" :)

By that I mean that if you run `composer-cli blueprints list` without any actual blueprints you will get nothing on the stdout, but when you push a blueprints before that it's name will appear on stdout. So just a simple `contains assert`, not parsing full outputs like `composer-cli blueprints show` and check the whole blueprints content from stdout. I'm not sure if this makes sense I can't define it really well I guess it will be best to discuss this in actual PRs when we get to it :)

**Comment by teg** [comment]
My suggestion would be to be strict and not parse anything at all, not even with `contains`. We could still do `composer-cli blueprints show FooBar` and just check for the return code whether the blueprint existed or not.

**Comment by atodorov** [comment]
After the latest commits the following commands remain untested.

```
upload info <UPLOAD-UUID>
    Details about an upload

upload start <BUILD-UUID> <IMAGE-NAME> [<PROVIDER> <PROFILE>|<PROFILE.TOML>]
    Upload a build image to the selected provider.

upload log <UPLOAD-UUID>
    Show the upload log

upload cancel <UPLOAD-UUID>
    Cancel an upload with that is queued or in progress

upload delete <UPLOAD-UUID>
    Delete the upload and remove it from the build

upload reset <UPLOAD-UUID>
    Reset the upload so that it can be tried again

providers list <PROVIDER>
    List the available providers, or list the <provider's> available profiles

providers show <PROVIDER> <PROFILE>
    show the details of a specific provider's profile

providers push <PROFILE.TOML>
    Add a new profile, or overwrite an existing one

providers save <PROVIDER> <PROFILE>
    Save the profile's details to a TOML file named <PROFILE>.toml

providers delete <PROVIDER> <PROFILE>
    Delete a profile from a provider
```

**Comment by jikortus** [comment]
> After the latest commits the following commands remain untested.
> 

I'd try to cover those, but don't know if there are still the issues with CLI support for `upload` and `providers` subcommands (if so, fixing that first would be needed before covering the related subcommands). Are there any updates @bcl ?

**Comment by jikortus** [comment]
From what I've tested, it looks like the support for `upload` and `providers` subcommands is still missing - AFAIK in osbuild-composer in the first place, but possibly some bits can be missing also in `composer-cli` (@bcl, please correct me if I'm wrong).

I created issue #735 to cover the missing functionality in osbuild-composer's API.

**Comment by teg** [comment]
The upload commands will be dropped from composer-cli, as they were never shipped in RHEL, and osbuild-composer does not support them.

**Comment by atodorov** [comment]
Based on the last comment from @teg I am closing this issue. 

The remaining commands that are not covered by tests will be removed and everything else seems to be covered already.
