### ISSUE TITLE
edge vsphere image should include vmware tools

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3583]
**Describe the bug**
As a vmware image, edge-vsphere image should include vmware tools, otherwise user need to define it in blueprint, like this:

[[packages]]
name = "open-vm-tools"
version = "*"

**Comment by 7flying** [comment]
this package needs to be added to the container image blueprint that servers the commit, not to the edge-vsphere blueprint

**Comment by miabbott** [comment]
FWIW, Red Hat CoreOS includes `open-vm-tools` in all of their x86_64 ostree commits, regardless of the artifacts being built from the commit - https://github.com/openshift/os/blob/0d39ee926d32c74191feaf261b911ebd883f44c6/common.yaml#L304

I would suggest that RHEL for Edge do the same.

**Comment by teg** [comment]
@miabbott I think there is an important distinction in that CoreOS (as far as I know) produces one commit that is meant to work everywhere, whereas with image builder we have the possibility to produce one commit per platform, so could tailer it to the needs of each.

Or is there a reason to include `open-vm-tools` on non VMware platforms?

**Comment by miabbott** [comment]
> Or is there a reason to include `open-vm-tools` on non VMware platforms?

I'm just thinking of the maintenance cost that users would incur if they had to build multiple commits for multiple platforms. 

If I have a set of packages/customizations that I want to include in my version of RHEL for Edge and then have them deployed via ISO, raw disk, VMDK, AMI, etc., it seems wasteful and burdensome to create different "flavors" of the same ostree commit for each type of disk image (i.e. 1:1 mapping of ostree commit to disk image). IMO, I should be able to create multiple disk images from the same ostree commit artifact (i.e. 1:`n` mapping of ostree commit to disk images).

I think giving the possibility to users to produce one commit per platform is fine, but we also shouldn't require users to know that platform A requires the inclusion of package Z, but platform B requires the inclusion of package Y. 

Maybe this question/problem gets easier with https://github.com/osbuild/images/pull/37?

**Comment by 7flying** [comment]
Just to update the status on this, for the time being we decided that the RPM should be added in the blueprint when building an `edge-commit` that will then be fed to the `edge-vsphere` artifact

**Comment by yih-redhat** [comment]
Closing this bug.
