### ISSUE TITLE
tests: increase coverage of blueprints tests + use asserts

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#362]
I'd like to try increase the coverage of `internal/blueprint/blueprint.go` and `internal/blueprint/customizations.go` by expanding the already existing `internal/blueprints/blueprint_test.go`. Also I'd like to rewrite a few lines there to use `testify/asserts` and `testify/require`

**Comment by atodorov** [comment]
@jrusz can you be more precise here - in particular which functions/code paths/test scebnarios would you like to cover if there are more than a handful ?  If there are sounds like a good opportunity to split.

If not, are you looking for help/guidance/advise or just stating your intentions with this issue ?

**Comment by jrusz** [comment]
@atodorov to be honest this is the first time I am doing something like this so I am not sure what I'll accomplish here. I looked at the coveralls report and saw which functions are not covered and I want to try covering them by adding test functions. I only want to work with the functions in the files I mentioned. I'll consider splitting this if I find it overwhelming but right now I am just stating my intention and will update this issue if needed. Once I have something I'll create a PR and we can discuss it there.

**Comment by teg** [comment]
Sounds reasonable to me. Happy to review the PR once you got started.
