### ISSUE TITLE
tests: increase coverage of osbuild tests - assemblers

### ISSUE THREAD

**Issue by jikortus** [osbuild/osbuild-composer#363]
As part of the initiative to increase code testing coverage, I'd like to create tests for assemblers - `internal/osbuild/*assembler.go`.

**Comment by atodorov** [comment]
Same comment as in https://github.com/osbuild/osbuild-composer/issues/362#issuecomment-601622921

**Comment by jikortus** [comment]
@atodorov I used `internal/osbuild/stage_test.go` as inspiration, so I'm basically working on implementing a similar set of scenarios (invalid json, missing name/options, unknown assembler, etc.).
