### ISSUE TITLE
packit not building Fedora 39 packages

### ISSUE THREAD

**Issue by nullr0ute** [osbuild/osbuild-composer#3677]
**Describe the bug**
For some reason packit isn't building osbuild/osbuild-composer packages so F-39 builds are out of date.

**Environment**
 * Fedora 39
 * Not the latest tagged release

**To Reproduce**
 * Upgrade from F-38 -> F-39 downgrades the packages to an older version

**Expected behavior**
The latest available releases.

**Additional context**
Nothing really, basically no automated package builds :-(

**Comment by ondrejbudai** [comment]
Seems to work just fine nowadays: https://copr.fedorainfracloud.org/coprs/g/osbuild/osbuild-composer/build/6447998/

I guess this was just a random failure related to branching?
