### ISSUE TITLE
fedora iot-simplified-installer fdo re-encryption failed

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3726]
**Describe the bug**
provision edge vm with iot-simplified-installer, install a failing health check unit and rollback, then check fdo re-encryption by command "cryptsetup luksDump /dev/vda3". The expected result is there is no "cipher_null-ecb" in output, but actually "cipher_null-ecb" is in the output.
The same test passed on rhel and centos-stream, the difference is we check /dev/vda4 on these os, with command "cryptsetup luksDump /dev/vda4", so I guess maybe the root reason is that fedora image only has /dev/vda3, and rhel/centos has /dev/vda4.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 * osbuild-composer version (`rpm -qi osbuild-composer)`

**To Reproduce**
1. build iot-simplified-installer and provision vm.
2. install sanely failing health check unit and reboot
"rpm-ostree install --cache-only https://s3.amazonaws.com/org.osbuild.test-dependencies/greenboot-failing-unit-1.0-1.el8.noarch.rpm --reboot"
3. vm failed to boot and then rollback automatically.
4. check fdo re-encryption status.
[simple@localhost ~]$ sudo cryptsetup luksDump /dev/vda3
[sudo] password for simple: 
LUKS header information
Version:       	2
Epoch:         	6
Metadata area: 	16384 [bytes]
Keyslots area: 	16744448 [bytes]
UUID:          	05ad1795-54bc-4a57-bb01-9082f86a774d
Label:         	crypt_root
Subsystem:     	(no subsystem)
Flags:       	(no flags)

Data segments:
  0: crypt
	offset: 16777216 [bytes]
	length: (whole device)
	cipher: cipher_null-ecb
	sector: 512 [bytes]

Keyslots:
  1: luks2
	Key:        256 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      pbkdf2
	Hash:       sha256
	Iterations: 1000
	Salt:       6c 19 c0 8e 05 f0 05 21 42 70 98 5a 07 c9 19 8a 
	            d0 7a d8 ef 16 14 95 be 94 9e d2 d8 46 bf 16 0f 
	AF stripes: 4000
	AF hash:    sha256
	Area offset:163840 [bytes]
	Area length:131072 [bytes]
	Digest ID:  0
Tokens:
  0: clevis
	Keyslot:    1
Digests:
  0: pbkdf2
	Hash:       sha256
	Iterations: 1000
	Salt:       75 96 82 66 56 55 02 a1 0a 63 58 db b2 c9 60 fd 
	            3b cd 8d fe ef cf 39 76 73 7d 68 8e b0 6f f7 aa 
	Digest:     b9 fb 7b a8 6f 2b 91 20 e2 8f b7 b4 2a 6f 67 09 
	            7e bf b3 2b 45 2b c1 1c be 23 d9 dc e0 54 f2 48 

**Expected behavior**
there is no "cipher_null-ecb" in output

**Additional context**

**Comment by yih-redhat** [comment]
@runcom @7flying Could you please take a look of this bug? I don't know much about fdo re-encryption, and this bug is found according to QE's fdo re-encryption test case.

**Comment by yih-redhat** [comment]
fdo client log:

[simple@localhost home]$ journalctl -u fdo-client-linuxapp.service 
Display all 177 possibilities? (y or n)
[simple@localhost home]$ journalctl -u fdo-client-linuxapp.service 
Oct 09 13:49:10 localhost.localdomain systemd[1]: Starting fdo-client-linuxapp.service - FDO client...
Oct 09 13:49:10 localhost.localdomain fdo-client-linuxapp[1077]:  2023-10-09T13:49:10.386Z INFO  fdo_client_linuxapp > No usable device>
Oct 09 13:49:10 localhost.localdomain systemd[1]: fdo-client-linuxapp.service: Deactivated successfully.
Oct 09 13:49:10 localhost.localdomain systemd[1]: Finished fdo-client-linuxapp.service - FDO client.
-- Boot cd6c4a0071004e97bf4bae580ac5d3d1 --
Oct 09 13:50:43 localhost.localdomain systemd[1]: Starting fdo-client-linuxapp.service - FDO client...
Oct 09 13:50:43 localhost.localdomain fdo-client-linuxapp[956]:  2023-10-09T13:50:43.400Z INFO  fdo_client_linuxapp > No usable device >
Oct 09 13:50:43 localhost.localdomain mv[976]: /usr/bin/mv: cannot stat '/boot/device-credentials': No such file or directory
Oct 09 13:50:43 localhost.localdomain systemd[1]: fdo-client-linuxapp.service: Deactivated successfully.
Oct 09 13:50:43 localhost.localdomain systemd[1]: Finished fdo-client-linuxapp.service - FDO client.

**Comment by 7flying** [comment]
@yih-redhat we need the logs from the manufacturing-client.service, if you have them

> @runcom @7flying Could you please take a look of this bug? And I found a similar bug was filed before https://bugzilla.redhat.com/show_bug.cgi?id=2220851

that one was a TPM issue, don't know yet if this will also be the case, but we'll need the manufacturing logs.

Thanks

**Comment by henrywang** [comment]
This might be selinux issue, I think.

**Comment by yih-redhat** [comment]
> This might be selinux issue, I think. @yih-redhat Could you please check the selinux fix in RHEL 9 in Fedora? Thanks.

sure, could you please let me know the steps to check the selinux fix?

**Comment by yih-redhat** [comment]
I do found below denied avc log for /tmp/fdouser, but after I changed to use /var/lib/fdo/fdouser, I didn't see it anymore.

type=AVC msg=audit(10/09/2023 08:35:03.580:9660) : avc:  denied  { open } for  pid=232024 comm=fdo-serviceinfo path=/tmp/fdouser dev="tmpfs" ino=251 scontext=system_u:system_r:fdo_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=0

**Comment by henrywang** [comment]
It's selinux issue. The selinux fdo fix in RHEL should be landed in Fedora.

**Comment by 7flying** [comment]
Linked the issue to our issue tracker: https://github.com/fedora-iot/iot-distro/issues/8

**Comment by yih-redhat** [comment]
Verifying this bug with build https://koji.fedoraproject.org/koji/buildinfo?buildID=2320649

**Comment by yih-redhat** [comment]
Verified this bug with build https://koji.fedoraproject.org/koji/buildinfo?buildID=2320649, fixed, the fdo re-encryption works as expected.
