### ISSUE TITLE
Test coverage for internal/common

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#419]
Add test coverage for the following files in internal/common:

- [x] compose_result
- [ ] helpers
- [ ] states
- [ ] types

**Comment by jrusz** [comment]
Starting work on `compose_result`

**Comment by teg** [comment]
Just a heads-up, some of these things may be re-factored/removed in the not-too-distant future.

**Comment by jrusz** [comment]
Thanks for the info @teg . I guess I'll move along to more permanent pieces of code for now then :)

**Comment by jrusz** [comment]
Some work has been done here and since it's likely to change soon I'm going to close this now.
