### ISSUE TITLE
Access RHEL content through the CDN

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#426]
*osbuild-composer* can only build RHEL from within Red Hat’s network right now. For people to use it from the outside, it needs to access repositories using a valid Red Hat subscription.

There’s no need to consume an additional entitlement when making images. Only when instantiating those images do they need to be subscribed themselves. Thus, *osbuild-composer* and *osbuild-worker* can reuse a subscription that exists on the hosts they’re running on.

Because a subscription is tied to a host (*system*), it can be auto-detected and doesn't need to be passed in explicitly: a host can either access RHEL content or it cannot. Thus, passing the subscription secrets from *osbuild-composer* to *osbuild-worker*—which might be running on a different system—is wrong conceptually.

RHEL repositories need to be marked as needing authentication via a subscription. For *osbuild-composer*, this can be done by adding a key to `RepoConfig`: `"rhsm": true`. This means that we’ll need a new repository struct for passing to `dnf-json` which contains the subscription data.

This fact (`"rhsm": true`) needs to be passed down to the files source of *osbuild*, which needs to find subscription secrets from the host it is running on. Thus, *osbuild* needs a more dynamic way of accessing secrets. Do this by removing the current (static json objects) approach to secrets, which is not used, and introduce a `secrets/` directory with executables that can be accessed from sources. This allows us to ship these in separate packages. For example, we might not want to ship the subscription source on non-RHEL systems. (CC @gicmo and @dvdhrm for these *osbuild* parts.)

Subscription secrets can be queried through subscription-manager’s D-Bus API, or as a first step discovered by looking at `/etc/pki/entitlement`.

**Comment by bcl** [comment]
This sounds like it is different from the way you did it in lorax-composer, passing the subscription certs to dnf, right?

It sounds like you are saying that any workers building RHEL content need to have their own subscriptions, instead of letting them 'borrow' the primary system's subscription. That sounds like a good idea to me. Also remember to take that into account when selecting a worker to hand off to so that there aren't any surprises when there is a mixed set of workers (not sure if that's even possible, but if it is).

**Comment by larskarlitski** [comment]
> This sounds like it is different from the way you did it in lorax-composer, passing the subscription certs to dnf, right?

It is similar, but more general, because workers can run on different hosts. *osbuild-composer* still passes the certs to dnf when it depsolves.

> It sounds like you are saying that any workers building RHEL content need to have their own subscriptions, instead of letting them 'borrow' the primary system's subscription. That sounds like a good idea to me.

Right, this proposal accepts that a subscription is really tied to a host and should not be passed around.

> Also remember to take that into account when selecting a worker to hand off to so that there aren't any surprises when there is a mixed set of workers (not sure if that's even possible, but if it is).

Great point! I briefly discussed this with @teg, and we were thinking that workers will advertise that they have access to RHEL content in a similar way that they advertise which architecture they can build. When making the request for a new job, a worker would include its capabilities (none of this exists yet, but that's the rough idea).

**Comment by jkozol** [comment]
My current implementation for accessing RHEL through the CDN can be found in #598. When the repos are loaded in rppmd the `sslcacert`, `sslclientkey`, and `sslclientcert` are added to the RepoConfigs which is passed to dnf-json.

When obsuild-composer calls osbuild on a RHEL machine it should include `{rhsm: true}` for all of the packages alongside their urls. Then osbuild will use it's machine's certs when curling the package urls.

**Comment by teg** [comment]
This was implemented by #396.
