### ISSUE TITLE
Improve output of osbuild-image-tests 

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#448]
The output from osbuild is often so long that the testing framework refuses to dump it to stdout, but even if we fix that it is still difficult to read the error as it is an escaped single line json bigger than 64kB.

https://github.com/osbuild/osbuild-composer/blob/09109b4f8efbe4e84f5c3ee3ba53d92a64ce87fd/cmd/osbuild-image-tests/main_test.go#L53

To read the error I usually copy the error, remove the escaping with `sed` and than process it using `jq`.

I propose to dump the output from osbuild into a file, but I am of course open to alternatives or recommendations how to run the test and get the output.
```patch
@@ -38,7 +39,7 @@ type testcaseStruct struct {
 }

 // runOsbuild runs osbuild with the specified manifest and store.
-func runOsbuild(manifest []byte, store string) (string, error) {
+func runOsbuild(manifest []byte, store string, reportDir, reportFileName string) (string, error) {
        cmd := getOsbuildCommand(store)

        cmd.Stderr = os.Stderr
@@ -50,6 +51,15 @@ func runOsbuild(manifest []byte, store string) (string, error) {

        if err != nil {
                if _, ok := err.(*exec.ExitError); ok {
+                       fd, err := os.Create(path.Join(reportDir, reportFileName))
+                       if err != nil {
+                               panic(err)
+                       }
+                       defer fd.Close()
+                       _, err = fd.Write(outBuffer.Bytes())
+                       if err != nil {
+                               panic(err)
+                       }
                        return "", fmt.Errorf("running osbuild failed: %s", outBuffer.String())
                }
                return "", fmt.Errorf("running osbuild failed from an unexpected reason: %#v", err)
```

**Comment by msehnout** [comment]
cc @ondrejbudai

**Comment by ondrejbudai** [comment]
I kinda dislike the idea of having the tests creating other files, I usually just pipe the test output and dump the whole testing VM after the tests are finished. But that's my workflow. However, I agree that we should solve the missing log problem. I have two thoughts:

- In #400 the json output from osbuild is now indented, so it's now correctly (and quite readable) printed to the test log.
- We can go even further and parse the json and print out the failed stage name and the error.

What do you think?

**Comment by msehnout** [comment]
The workflow with creating new machine every time gets annoying when using Beaker. The time needed to spin up a new machine is far away from qemu with kvm support can achieve. But basically you propose to just run:
"/usr/libexec/tests/osbuild-composer/osbuild-image-tests > test_result",
right?

That sounds good, at least I will see the whole output because the terminal won't cut it, but let me elaborate more on the files.

What I miss in all our tests is a hierarchy in the output. Our tests interleave long error messages with the results. I'd prefer to have a list of results at the end but I don't think that is easily possible with the framework we use. That's where the output to files comes in handy. I can create a set of files for each test specifying the result and the output separately. It does not matter that I create some files, because we drop the whole system anyway.

**Comment by atodorov** [comment]
@msehnout are you still having issues with readability of osbuild-image-tests results ? If not let's close this issue.

**Comment by msehnout** [comment]
I haven't run them in a while, so no. Let's close this :)
