### ISSUE TITLE
Report errors from generate-test-case{,s}

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#449]
The usage of Python's `subprocess.check_output` function hides all the output from osbuild and osbuild-pipeline in the generator making it really hard to figure out what is going on:
https://github.com/osbuild/osbuild-composer/blob/09109b4f8efbe4e84f5c3ee3ba53d92a64ce87fd/tools/test-case-generators/generate-test-cases#L18
... and few other occurences

I suggest to report the errors. e.g. like this:
```patch
@@ -28,7 +28,11 @@ It then outputs a json test case as standard output.

 def run_osbuild(manifest, store):
     osbuild_cmd = ["osbuild", "--store", store, "--json", "-"]
-    result = json.loads(subprocess.check_output(osbuild_cmd, encoding="utf-8", input=json.dumps(manifest)))
+    sp = subprocess.run(osbuild_cmd, input=json.dumps(manifest), encoding="utf-8", stdout=subprocess.PIPE)
+    if sp.returncode != 0:
+        print("Error running osbuild: ", sp.stdout)
+        sys.exit(1)
+    result = json.loads(sp.stdout)
     return result.get("output_id")


```

**Comment by teg** [comment]
cc: @jkozol

**Comment by jkozol** [comment]
@msehnout Thanks for the suggestion! I can improve the error output.
