### ISSUE TITLE
Add compose tests to osbuild-weldr-tests

### ISSUE THREAD

**Issue by bcl** [osbuild/osbuild-composer#451]
Integration testing of composes. Possibly disabled by a cmdline flag for those times when you don't want long running tests.

**Comment by teg** [comment]
The plan so far was to only have the image test generate all the images. What did you have in mind here? It may make sense to generate one image type just to verify the weldr API works, and testing different image types would still be left to the image tests, right? (Just to try to keep the overall run-time somewhat in check).

**Comment by bcl** [comment]
I was thinking about doing the same thing I did in lorax, passing a ?test=1|2 argument that makes it generate a fake successful or fake failed compose. You can then examine the queue and status responses without needing to wait for an actual compose to finish.

**Comment by teg** [comment]
Ah, ok. I didn't know that was possible. Makes sense.

**Comment by larskarlitski** [comment]
I must say I'm not a fan of adding test code to production. (We could say this is for backwards compat to lorax-composer, though :wink:).

Could we have quick-running composes by passing in a mock store, that makes `PushCompose` be a noop?

**Comment by bcl** [comment]
Yeah, I agree in principle. But if we want to be able to run this against both API servers then it needs them unless we change the tests to run lorax specific compose tests with the arguments, and osbuild tests with a noop image or somesuch.

The goal of the test is to populate the results so that the queue, log, etc. APIs can be tested. I'd prefer to do it without a full compose because that just introduces unrelated places for it to break.

**Comment by larskarlitski** [comment]
>  But if we want to be able to run this against both API servers [...]

Ah I'm sorry, I didn't think about running it against both servers. Ignore my comment then :)

**Comment by bcl** [comment]
PR #503 finishes this.
