### ISSUE TITLE
Add coverage for awsupload.go

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#454]

**Comment by ondrejbudai** [comment]
What's your plan on this? Imo this is a very hard part to cover with unit tests without mocking all the AWS code out.

**Comment by jrusz** [comment]
Yes I do plan to use mocking here for all of the AWS functions. Once I have at least one test function ready I'll create a draft PR and we can discuss it there further :)

**Comment by atodorov** [comment]
@jrusz send PR for the code you currently have but it's not worth it mocking out everything on the AWS side. Most of this will be covered by #337

**Comment by jrusz** [comment]
@atodorov Alright thanks for the info. I suppose we can close this then and wait for #337 and the outcome from it?

**Comment by ondrejbudai** [comment]
#337 landed, I'm closing this now, feel free to reopen if not satisfied with it
