### ISSUE TITLE
Add coverage for store.go

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#455]
Seems like there's a lot to cover but I plan to start from the top and work my way trough the file.. Any changes planned in the near future for this part of code @teg ?

**Comment by teg** [comment]
@larskarlitski, could you comment on this? I assume most of this will stay unchanged?

**Comment by larskarlitski** [comment]
> @larskarlitski, could you comment on this? I assume most of this will stay unchanged?

I don't think it makes sense to test anything related to jobs at this point, because of https://github.com/osbuild/osbuild-composer/issues/342 (like `PushCompose()` and `PopJob()`).

Everything else is fair game. Thanks!

**Comment by jrusz** [comment]
In PR #499 I have tests for the functions working with Blueprints. Once that gets merged I could either continue with Composes or Sources I think, are you doing some refactoring there @larskarlitski ?

**Comment by larskarlitski** [comment]
Still working on it.

**Comment by teg** [comment]
I think this is pretty stable now. So anyone wanting to work an adding tests to the store would be appreciated. Do you agree @larskarlitski?

**Comment by larskarlitski** [comment]
> I think this is pretty stable now. So anyone wanting to work an adding tests to the store would be appreciated. Do you agree @larskarlitski?

Yes, these changes have landed some time ago.

**Comment by jrusz** [comment]
Great I'll pick this up again then :)
