### ISSUE TITLE
Jenkins: why not run all the integration tests

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#468]
In here https://github.com/osbuild/osbuild-composer/blob/master/jenkins/run_tests.sh most of the integration tests are actually commented out. 

@major is there any particular reason for that? I think everything except `osbuild-image-tests` should work without any more configuration of the Jenkins slave.

**Comment by atodorov** [comment]
I see #466 now

**Comment by major** [comment]
@atodorov That's a good question! We're trying to enable them one by one so we don't overload ourselves with errors. @larskarlitski and @teg are working with me to debug the tests and get them turned on for every PR.

**Comment by major** [comment]
@atodorov We've onboarded all test types now and we're onboarding the image tests in groups right now.
