### ISSUE TITLE
The source API only implements v0 even though the server advertises v1

### ISSUE THREAD

**Issue by bcl** [osbuild/osbuild-composer#475]
In WELDR API v1 the source response was changed to add an id field. The osbuild-composer API currently doesn't support the id field even though the server advertises V1 support.

Which brings up a good question about API version support. Should a V1 server be expected to support both versions of an API call? Seems to me like it shouldn't need to, but this may cause problems with UI that expects support for both. We never really defined this behavior, since lorax-composer supports both.

**Comment by teg** [comment]
I think we probably want to support both v0 and v1.

**Comment by bcl** [comment]
After digging through the code it looks like source is really the only thing that needs v1 added. I'm ignoring the upload routes/json on purpose since the osbuild implementation is so differet from lorax's, and I don't really expect the one in lorax to get any use since it's only in Fedora.

**Comment by teg** [comment]
Out of curiosity, what are we doing differently? Or are we only missing some bits?
