### ISSUE TITLE
Kerberos authentication for RCM API

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#504]
As opposed to Weldr API where access is managed by unix permissions, the RCM API runs on a network facing TCP socket so we need to control access to it. The most convenient way for users is to support Kerberos authentication.

Acceptance criteria:
 - [ ] Create or find a container with Kerberos KDC which can be used for testing
 - [ ] Use [gokrb5](https://github.com/jcmturner/gokrb5) to create a kerberos-aware service from the RCM API 

Reference:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system-level_authentication_guide/using_kerberos#About_Kerberos

**Comment by msehnout** [comment]
Update:

Explore possibilities of using Kerberos implementations that are already present in Fedora and RHEL. These include:

* Using C-bingings to GSSAPI from the krb5 package
* Using Apache httpd as a HTTP proxy for the RCM API

**Comment by msehnout** [comment]
Update:

Current plan is to use GSSAPI from the krb5-devel package. It provides the API described in this RFC:
https://tools.ietf.org/html/rfc2744.html
As a complement to the GSSAPI we also need to use a protocol negotiation as described here:
https://tools.ietf.org/html/rfc4178
and finally wrap the negotiation into HTTP request-response as described here:
https://tools.ietf.org/html/rfc4559

The goal is to be able to
 * authenticate the user
 * get the user name so that we know who is using the HTTP service

Advantages of using GSSAPI:
 * API stability
 * Available as a shared library
 * Using common system library gives us interoperability for "free"

**Comment by bcl** [comment]
> Current plan is to use GSSAPI from the krb5-devel package.

Do you have a link to that code?

**Comment by msehnout** [comment]
> > Current plan is to use GSSAPI from the krb5-devel package.
> 
> Do you have a link to that code?

I'm still working on a prototype. It is not easy, at least for me, to find the right way to call gssapi from go.

**Comment by bcl** [comment]
Ah! I thought you were referring to some existing code, good luck!

**Comment by msehnout** [comment]
The code is available here: https://github.com/msehnout/go-gssapi

It uses C code to call GSSAPI and really small Go wrapper. It lacks support for multiple HTTP requests-responses so that the GSSAPI calls can run in loop as recommended in the RFC and I'm unsure how to implement the logic for making the decision if the user is authenticated or not.

**Comment by msehnout** [comment]
This issue is not currently the top priority but, as of now, it is still something we would like to have.
