### ISSUE TITLE
The jenkins instance cannot be accessed using http

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#514]
The Jenkins instance cannot be accessed using http:

http://jenkins.osbuild.org

Https works OK:

https://jenkins.osbuild.org

cc @major

**Comment by major** [comment]
@ondrejbudai Should we allow it to be accessed via http? :) I'd like to avoid that if at all possible. We could add a redirect, though.

**Comment by larskarlitski** [comment]
+1 for redirect only. Always encrypt :sunglasses:

**Comment by ondrejbudai** [comment]
Yeah, I also thought of redirect.

**Comment by major** [comment]
Okay, I'll set that up on Monday.

**Comment by major** [comment]
🥰

```
~ ➜ curl -I jenkins.osbuild.org
HTTP/1.1 301 Moved Permanently
Server: nginx/1.17.10
Date: Mon, 27 Apr 2020 14:58:19 GMT
Content-Type: text/html
Content-Length: 170
Connection: keep-alive
Location: https://jenkins.osbuild.org/
```

@ondrejbudai @larskarlitski Can you verify this works for you and close this out?

**Comment by ondrejbudai** [comment]
Works for me

**Comment by larskarlitski** [comment]
Like a charm. Thank you!
