### ISSUE TITLE
API: replace the RCM API with two new APIs

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#518]
The current intention was for the RCM API to serve all non-weldr use-cases, and to be implemented as just another socket unit. With this I propose that we instead split it into two new binaries, that will be separate from the weldr implementation (though compiled from the same code).

The reason for this is that the three use-cases we have (weldr, installer and koji) are all different in their integration into the system (in particular, they all use different methods of authentication), and they are unlikely to be used on the same machine (weldr would be used on the local machine, and the others would be in different kinds of cloud infrastructure).

# osbuild-composer API

This will be used by osbuild-installer. Authentication must be done via SSL Client Certificates and only upload to cloud will be supported as upload targets. For the time being only subscription manager customization will be supported, but more can be added as osbuild-installer needs it.

Proposed API: https://app.swaggerhub.com/apis-docs/tomegun/osbuild-composer/1

cc @Gundersanne 

# osbuild-composer-koji API

This will be used by RCM and OSCI internally at Red Hat. Only Kerberos authentication is supported, and only Koji is supported as an upload target. For the time being, no customizations are supported, but for instance package selection could be added in the future, if and when the use-cases become clear.

Proposed API: https://app.swaggerhub.com/apis-docs/tomegun/osbuild-composer-koji/1

cc @msehnout @ondrejbudai

**Comment by msehnout** [comment]
I was actually thinking something very similar, so I could not agree more. As an addition to your proposal I suggest we drop the rcm subpackage as I don't expect anyone to deploy osbuild-composer from RPM.

I expect us to deploy both APIs into openshift, so I think we should just implement both of them for deployment in containers without systemd (so we can drop the rcm socket unit as well).

Finally, if the OpenShift cluster supports it, we don't need to implement the client certificate validation ourselves, because the router in OS cluster can do it for us.

**Comment by larskarlitski** [comment]
> [...] I don't expect anyone to deploy osbuild-composer from RPM.

Hm. I really like that we're shipping everything in the same way. I'm happy to have this discussion, but I think it's independent of splitting the APIs as described in this issue.

**Comment by dvdhrm** [comment]
I like the proposals. As mentioned before, I would make `UploadTarget` an explicit type, rather than hiding the union deep down in the `/compose` parameter type.

**Comment by dvdhrm** [comment]
Oh, and can you provide the source files for these? I don't see where I can download them from the links you posted, but I might be missing something.

**Comment by msehnout** [comment]
> > [...] I don't expect anyone to deploy osbuild-composer from RPM.
> 
> Hm. I really like that we're shipping everything in the same way. I'm happy to have this discussion, but I think it's independent of splitting the APIs as described in this issue.

We can ship it, but I don't think we will use it for deployment anyway.

**Comment by teg** [comment]
> I would make `UploadTarget` an explicit type, rather than hiding the union deep down in the `/compose` parameter type.

Done. Thanks!

> Oh, and can you provide the source files for these?

As we seem to be in general agreement, I'll make a PR (I thought there would have been a link to the source, but it doesn't seem that way).

> As an addition to your proposal I suggest we drop the rcm subpackage

As a general principle, I agree with @larskarlitski that just uniformly providing our stuff as RPMs with all that that gives us (dependencies, build and install instructions, consistency, etc) makes the most sense to me. If nothing else, as a way to document how our software can be deployed. That said, let's evaluate the alternatives, and see if we can find a way to get the best of all worlds. I think we should discuss that separately though, so I'd make a PR out of this where things are sub-packages as before.

**Comment by ondrejbudai** [comment]
Done!
