### ISSUE TITLE
Fedora 31/32: osbuild-tests failing (got FINISHED instead of FAILED)

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#566]
This was found when testing RHEL 8.2 with the `osbuild-tests` test in osbuild/osbuild-composer#564:

```
Logs from osbuild-tests
----------------------------------------------------------------------
stderr:

----------------------------------------------------------------------
stdout:
=== RUN   TestEverything
    TestEverything: main_test.go:104: 
        	Error Trace:	main_test.go:104
        	            				main_test.go:61
        	Error:      	Not equal: 
        	            	expected: "FAILED"
        	            	actual  : "FINISHED"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-FAILED
        	            	+FINISHED
        	Test:       	TestEverything
        	Messages:   	Unexpected compose result: FAILED
--- FAIL: TestEverything (68.00s)
=== RUN   TestSources
--- PASS: TestSources (1.23s)
FAIL
```

**Comment by ondrejbudai** [comment]
Can you point me at a build where osbuild-tests failed on RHEL 8.2? I cannot find one.

**Comment by major** [comment]
@ondrejbudai Here's one: https://jenkins.osbuild.org/job/osbuild-composer-fedora32-base/125/

**Comment by ondrejbudai** [comment]
This is Fedora though.

**Comment by major** [comment]
Hmm, I'll keep looking to see if i can find another one. It seems to be intermittent. Sometimes I can tell Jenkins to re-run the test and the issue disappears on the second run.

**Comment by ondrejbudai** [comment]
I think this happens only on Fedora because of bad mirrors, but I'm not sure though. I'm planning to add more logging to the `osbuild-tests` in the case of failure.

**Comment by atodorov** [comment]
This is the same as https://github.com/osbuild/osbuild-composer/issues/611 but we don't have the logs from the compose to see what happened.

@major is this still an issue you are seeing or can this be closed ?

**Comment by ondrejbudai** [comment]
I'm not convinced that this happens on RHEL 8.2. @major can you find a build where this happens? If not, let's change the title to Fedora, this happens often there because of flaky mirrors.

See
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-621/17/pipeline/14
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-594/7/pipeline/13
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-616/2/pipeline/15
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-625/1/pipeline/13

**Comment by ondrejbudai** [comment]
Here you can see the journal log from one of these failed logs:

https://osbuildci.cloud.paas.psi.redhat.com/job/osbuild/job/osbuild-composer/job/PR-625/1/artifact/fedora31-base/systemd-journald.log

**Comment by major** [comment]
@ondrejbudai I have not seen this on 8.2 in a good while, so I changed the title as you requested.

**Comment by larskarlitski** [comment]
According to the logs, this seems to be a faulty mirror (returning `503`s).

It works for the other tests, because the use `download.fedoraproject.com` instead of one of the mirrors returned by the metalink that's configured in `repositories/`.

@teg what was the result from the metalink-in-osbuild discussion?

**Comment by teg** [comment]
> @teg what was the result from the metalink-in-osbuild discussion?

We initially decided not to pursue it, as we found a flaw in the model:

By re-resolving the base repo to a potential different one for downloading the rpms than the one we used to download the metadata, we are no longer guaranteed that the rpms will be there (if the metedata repo is newer than the rpm repo).

However, on further inspection, it seems that does not matter. Apparently itself ignores the problem and reresolves all the time, and that 404s are just an expected thing to deal with. I have not spent enough time verifying exactly the logic they have there to deal with missing rpms though.

I would be very happy to see support for metalink land in osbuild, it is just a matter of finding the time. @dvdhrm was looking into this again recently, so probably has the best overview of what is needed.

**Comment by bcl** [comment]
download.fedoraproject.org isn't a single host:

```
download.fedoraproject.org is an alias for wildcard.fedoraproject.org.
wildcard.fedoraproject.org has address 209.132.190.2
wildcard.fedoraproject.org has address 152.19.134.142
wildcard.fedoraproject.org has address 152.19.134.198
wildcard.fedoraproject.org has address 209.132.181.16
wildcard.fedoraproject.org has address 8.43.85.73
wildcard.fedoraproject.org has address 67.219.144.68
wildcard.fedoraproject.org has address 8.43.85.67
wildcard.fedoraproject.org has address 140.211.169.196
wildcard.fedoraproject.org has address 140.211.169.206
wildcard.fedoraproject.org has address 209.132.181.15
wildcard.fedoraproject.org has IPv6 address 2604:1580:fe00:0:dead:beef:cafe:fed1
wildcard.fedoraproject.org has IPv6 address 2620:52:3:1:dead:beef:cafe:fed7
wildcard.fedoraproject.org has IPv6 address 2605:bc80:3010:600:dead:beef:cafe:fed9
wildcard.fedoraproject.org has IPv6 address 2605:bc80:3010:600:dead:beef:cafe:feda
wildcard.fedoraproject.org has IPv6 address 2610:28:3090:3001:dead:beef:cafe:fed3
wildcard.fedoraproject.org has IPv6 address 2620:52:3:1:dead:beef:cafe:fed6
```
I thought we'd picked the kernel.org mirror at some point? Or was that for something else?
When I need a consistent view of the Fedora repos I use dl.fedoraproject.org

**Comment by atodorov** [comment]
@major I think we haven't seen this in a while. Is the original issue gone ? Does something else need to be done here or do we need to change scope for this issue ?

**Comment by major** [comment]
I haven't seen this much since we pinned internal repos in some of the testing. We can close it for now.
