### ISSUE TITLE
Test the remote worker code path in CI

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#572]
The remote worker code isn't tested in CI yet, but we should offer a setup that follows @ondrejbudai's guide from [his commit](https://github.com/osbuild/osbuild-composer/commit/820d23fd).

* Mask the default worker (`osbuild-worker@1`)
* Create certificates for the worker and composer
* Setup the remote worker service to talk to composer on 127.0.0.1 port 8700
* Setup the remote worker socket for composer to listen for the remote worker on 127.0.0.1
* Run the same tests afterwards

This should be an option in ansible-osbuild.

**Comment by teg** [comment]
Could we just always run workers "remotely" like this? It would mean that we'd need some default certificates created to work out-of-the box, but I would be happy if we could remove the UDS codepath.

**Comment by teg** [comment]
(Please don't block on my suggestion, making something work with the current code would definitely still be worth it).

**Comment by major** [comment]
@teg That works for me.

**Comment by ondrejbudai** [comment]
We do that now. :partying_face:
