### ISSUE TITLE
TestBlueprintDepsolveV0 frequently hits a timeout

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#601]
I'm seeing `TestBlueprintDepsolveV0` frequently hit a timeout across Fedora 31/32 and RHEL 8.2.

```
=== RUN   TestBlueprintDepsolveV0
    TestBlueprintDepsolveV0: blueprints_test.go:680:
                Error Trace:    blueprints_test.go:680
                Error:          Received unexpected error:
                                Get "http://localhost/api/v0/blueprints/depsolve/test-deps-blueprint-v0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                Test:           TestBlueprintDepsolveV0
                Messages:       Depsolve blueprint failed with a client error
```

It doesn't occur *every* time, but it's happening often on PSI's infrastructure.

It occurred while working on #600 several times.

**Comment by major** [comment]
During the test, `dnf-json` has the CPU pegged at 100% multiple times. I wonder if we ought to run these in parallel to save time or extend the timeout?

**Comment by larskarlitski** [comment]
The timeout's at 60 seconds right now ([here](internal/client/unit_test.go) and [here](https://github.com/osbuild/osbuild-composer/blob/master/internal/client/integration_test.go#L24)). dnf's cache will be filled after hitting the first route, so increasing time timeout for all tests is probably not a good idea. Could we explicitly fill the cache once on startup, by hitting one of the routes with a bigger timeout once?

**Comment by major** [comment]
For what it's worth, if I remove F31/32's modular repositories, I can get this test to pass without timeouts about 99% of the time. That `base.fill_sack()` is fairly slow...

**Comment by teg** [comment]
I would argue that we should not have any timeouts at all, except potentially in jenkins itself to kill the whole test-suite. What is the timout meant to achieve / protect against?

**Comment by major** [comment]
I think there's just a default 60s timeout set somewhere either in our code or in `net/http` from what I can tell. We could certainly just extend the default to 120s or find some way to prime the cache first.

**Comment by teg** [comment]
My suggestion was to set the timeout to two weeks or something like that. Why would we ever fail early?

**Comment by major** [comment]
*Major and Tom are typing...*
