### ISSUE TITLE
tests: uncomment/enable remaining sanity checks in cmd/osbuild-tests/main_test.go

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#615]
I see commented out sections for some compose and blueprints commands which should be uncommented and implemented properly. The focus here is executing the commands and making sure they don't crash rather than validating the resulting state afterwards. Some asserts/validation is fine but if it needs to go too deep maybe it should be places in the API portion of the test suite.

**Comment by jrusz** [comment]
I agree this should be implemented into some proper integration test. I think this can be done as a part of #356 with the new information we have there.

**Comment by atodorov** [comment]
The remaining items for this issue are:

1) Lines 85-90 in osbuild-tests/main_test.go - composer-cli cancel - blocked by missing API route
2) Lines 122-125 - composer-cli blueprints undo

**Comment by teg** [comment]
@atodorov is undo blocked by anything?

**Comment by atodorov** [comment]
> @atodorov is undo blocked by anything?

I don't think so. It's on my todo list to look into it.
