### ISSUE TITLE
tests: use osbuild-composer when building images for Jenkins slaves

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#629]
From a recent discussion that we've had Major said he's taking a known image for RHEL (I guess the latest) adding a bunch of Jenkins related libraries on top of it and then pushing the result to OpenStack before the testing can continue on that VM. 

All of this can start using osbuild-composer and build these slave images from a customized blueprint in order to go full circle. Filing here for discussion and consideration.

**Comment by atodorov** [comment]
@major I see https://github.com/osbuild/imagebuilder-ci-images and https://github.com/osbuild/jenkins-images which I think resolve this issue but I'm not sure how these 2 repos relate to one another and why their Jenkins pipelines have been failing/disabled. Can you comment on that?

**Comment by ondrejbudai** [comment]
Currently, we don't use images built by osbuild-composer. Currently, the stock images are used (cloud base for Fedora, not sure which one for rhel).

Not sure how this issue plays with rpmci.

**Comment by msehnout** [comment]
We thought about using Image builder service for generating test images for `rpmci` but we haven't agreed on it. On one hand it would be nice to use our own service to generate images for our own CI, on the other hand it is also valid assumption that our users will actually install osbuild-composer into their own systems so it makes sense to test what our users will do. Bottom line is: we haven't reached a conclusion and it is not a top priority as we first need the service anyway.

**Comment by larskarlitski** [comment]
> We thought about using Image builder service for generating test images for `rpmci` but we haven't agreed on it.

Please try to use it. Not only would we eat our own dogfood and find issues, I also think this can make us much more efficient. I am happy to help working towards removing any blockers.

> @major I see https://github.com/osbuild/imagebuilder-ci-images and https://github.com/osbuild/jenkins-images which I think resolve this issue but I'm not sure how these 2 repos relate to one another and why their Jenkins pipelines have been failing/disabled. Can you comment on that?

Indeed, @major are these repositories still used somewhere?

**Comment by major** [comment]
> > @major I see https://github.com/osbuild/imagebuilder-ci-images and https://github.com/osbuild/jenkins-images which I think resolve this issue but I'm not sure how these 2 repos relate to one another and why their Jenkins pipelines have been failing/disabled. Can you comment on that?
> 
> Indeed, @major are these repositories still used somewhere?

These should probably be archived. Originally, we were using images that were set up to make CI go as fast as possible. Then we realized that we ought to use the base images as they come from RHEL/Fedora so we could ensure RPM dependencies worked. Also, we wanted to ensure we used the same image every single time.

**Comment by thozza** [comment]
We don't use Jenkins any more, but in a sense, I think that @croissanne fixed this problem for our current setup with the CI image build pipeline. Feel free to reopen if I'm wrong.
