### ISSUE TITLE
tests: composer-cli compose results fails

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#644]
```
# composer-cli compose list
56621ea8-de30-41d2-bf78-32aa3cde0669 FINISHED test-blueprint 0.0.2 ami
# composer-cli compose results 56621ea8-de30-41d2-bf78-32aa3cde0669
No Content-Disposition header; cannot get filename
# echo $?
1
```

This causes one of the new sanity tests introduced in #642 to fail.

**Comment by bcl** [comment]
This is the same kind of thing as #643, in lorax-composer results is the metadata + the image file. Not sure if that makes sense for osbuild-composer.

**Comment by atodorov** [comment]
Same comment for reference: https://github.com/osbuild/osbuild-composer/issues/643#issuecomment-631400176

**Comment by teg** [comment]
Same comment from me too ;) I think we should add support.
