### ISSUE TITLE
composer-cli requires root on RHEL 8 but not on Fedora 31/32

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#646]
While working on osbuild/ansible-osbuild#58, I found that running `composer-cli` with osbuild-composer on RHEL 8.2 requires `sudo`, but Fedora 31 and 32 allow the normal `fedora` user to use `composer-cli` to talk to osbuild-composer.

I'm not sure if this is by design, or if we have a bug.

**Comment by larskarlitski** [comment]
Oops. Fixed in #674.

**Comment by major** [comment]
@larskarlitski Nicely done, sir!
