### ISSUE TITLE
osbuild-weldr-tests times out frequently in CI

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#648]
All tests have their own timeout: https://github.com/osbuild/osbuild-composer/blob/master/schutzbot/vars.yml#L14.

Timeouts are hard to get right—is bumping to 15 minutes enough? Also, they're of questionable value to me.

I propose removing them all in favor of the a global timeout on the Jenkins level, or setting them all to a high number, such as 60 minutes.

**Comment by teg** [comment]
I agree. The only reason to have a timeout, I think, is to put a cap on our costs. But only as a very last resort, hitting the timeout is never helpful, so make it as high as our wallets permit.

**Comment by major** [comment]
@larskarlitski No objection here. We can change those out. My main goal was to ensure we got as much testing feedback as possible. If the first timed out but we got results for the other three, then that's valuable.

If the first one runs for an hour, hits the timeout, and we get no results on the others, then that is a little frustrating.

**Comment by larskarlitski** [comment]
> If the first one runs for an hour, hits the timeout, and we get no results on the others, then that is a little frustrating.

Right now, we're only running into these timeouts as false negatives. I think it's fine to not see results from other tests should we introduce a bug that introduces a hang. This doesn't seem to happen often in practice so far :)
