### ISSUE TITLE
osbuild-composer.service fails to start on ppc64le

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#665]
I can start the `osbuild-composer.socket` but when it tries to start `osbuild-composer.service` it fails with:
```
osbuild-composer[32881]: 2020/05/25 08:53:41 Host distro does not support host architecture: invalid architecture: ppc64le 
```
Steps to reproduce:

1. Build and install `osbuild` and `osbuild-composer` from source.
2. Either `systemctl start osbuild-composer.service` or `systemctl start osbuild-composer.socket` followed by CLI command (eg. `composer-cli compose types`)

Distro used: Fedora-32

**Comment by msehnout** [comment]
As can be seen in the `internals/distro/fedora32` package, this is not implemented:
https://github.com/osbuild/osbuild-composer/blob/7c0d384fde3bd48ff98a85ffd7ee7e83b07059ae/internal/distro/fedora32/distro.go#L456

Only x86_64 and aarch64 are supported as of today.
