### ISSUE TITLE
composer-cli blueprints freeze show displays JSON, not TOML

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#667]
composer-cli blueprints --help:

```
blueprints freeze show <BLUEPRINT,...>
    Display the frozen blueprint in TOML format
```

Actual results:

```
# composer-cli blueprints freeze show test-blueprint
{"blueprints":[{"blueprint":{"name":"test-blueprint","description":"JSON test blueprint","version":"0.0.6","packages":[{"name":"0ad","version":"0.0.23b-13.fc32.x86_64"},{"name":"2048-cli","version":"0.9.1-9.fc32.x86_64"},{"name":"0xFFFF","version":"0.8-3.fc32.x86_64"}],"modules":[],"groups":[],"customizations":{"user":[{"name":"user1"},{"name":"user2"}]}}}],"errors":[]}
```

**Comment by larskarlitski** [comment]
This should be an issue on the lorax repository, because `composer-cli` simply prints the result from those routes: https://github.com/weldr/lorax/blob/master/src/composer/cli/blueprints.py#L476

Should be the same when running against lorax-composer. Feel free to reopen this issue if it isn't.

**Comment by atodorov** [comment]
With lorax-composer everything works as expected:

```
# composer-cli blueprints freeze example-http-server
blueprint: example-http-server v0.0.1
    httpd-2.4.37-21.module+el8.2.0+5008+cca404a3.x86_64
    mod_ssl-1:2.4.37-21.module+el8.2.0+5008+cca404a3.x86_64
    php-7.2.24-1.module+el8.2.0+4601+7c76a223.x86_64
    php-mysqlnd-7.2.24-1.module+el8.2.0+4601+7c76a223.x86_64
    openssh-server-8.0p1-5.el8.x86_64
    rsync-3.1.3-7.el8.x86_64
    tmux-2.7-1.el8.x86_64
[root@kvm-08-guest38 ~]# composer-cli blueprints freeze show example-http-server
name = "example-http-server"
description = "An example http server with PHP and MySQL support."
version = "0.0.1"
groups = []

[[modules]]
name = "httpd"
version = "2.4.37-21.module+el8.2.0+5008+cca404a3.x86_64"

[[modules]]
name = "mod_ssl"
version = "1:2.4.37-21.module+el8.2.0+5008+cca404a3.x86_64"

[[modules]]
name = "php"
version = "7.2.24-1.module+el8.2.0+4601+7c76a223.x86_64"

[[modules]]
name = "php-mysqlnd"
version = "7.2.24-1.module+el8.2.0+4601+7c76a223.x86_64"

[[packages]]
name = "openssh-server"
version = "8.0p1-5.el8.x86_64"

[[packages]]
name = "rsync"
version = "3.1.3-7.el8.x86_64"

[[packages]]
name = "tmux"
version = "2.7-1.el8.x86_64"
```

The cli calls `/blueprints/freeze/%s?format=toml"`:
https://github.com/weldr/lorax/blob/master/src/composer/cli/blueprints.py#L477

which doesn't appear to be taken into account in `blueprintsFreezeHandler()`

**Comment by atodorov** [comment]
> The cli calls `/blueprints/freeze/%s?format=toml"`:
> https://github.com/weldr/lorax/blob/master/src/composer/cli/blueprints.py#L477

There is also a small bug in the cli b/c the enclosing function receives a `show_json` parameter but never makes use of it so it only displays toml!

**Comment by larskarlitski** [comment]
> The cli calls `/blueprints/freeze/%s?format=toml"`

Indeed, I missed that it requests a different format. Awkward that it doesn't check whether the format is right.

Sorry for closing this prematurely.
