### ISSUE TITLE
Local boot tests

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#68]
We want to do a minimal test to verify that our images boot. For each output type, select one test case with a blueprint that allows an ssh connection (might require some coordination with other issues for this cycle). Boot the image, connect to it and use systemctl to verify that the image booted correctly.
For the images that can be booted locally, use qemu or nspawn for this (whichever makes sense for the output type). If some images cannot be booted locally, but only in the target environment, document that.

- [ ] qcow2
- [ ] ami
- [ ] vhd
- [ ] openstack
- [ ] vmdk
- [ ] partitioned-disk
- [ ] ext4-filesystem
- [ ] tar

**Comment by msehnout** [comment]
I'm afraid this is blocked by working customizations in order to configure sshd and add ssh keys for a user.

**Comment by teg** [comment]
That is true. My suggestion is to start off with a hand-crafted pipeline (based on one of the empty pipelines), to at least get the infrastructure up and going. I'll have a look at getting the missing customizations up-to-speed to unblock this ASAP.

**Comment by teg** [comment]
Closed by PR #92
