### ISSUE TITLE
composer crashes when store.New() wants to log in non-verbose mode

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#685]
Logging behaviour got slightly changed in a22cd78e. In non-verbose mode, `nil` Logger is passed to `store.New()`. However, the store tries to use the logger anyway, resulting in crashes when the store is invalid or ignoring some composes.

cc @teg

**Comment by stefwalter** [comment]
I think I'm seeing this after I upgraded to v 13.
