### ISSUE TITLE
"The compose result is empty" when building fedora-iot-commit

### ISSUE THREAD

**Issue by stefwalter** [osbuild/osbuild-composer#689]
I've tried to build a blueprint for the fedora-iot-commit output type. When I do this, the build fails pretty quickly and I see "The compose result is empty" in the output.

```
$ rpm -qa | grep osbuild
osbuild-composer-13-1.20200529git375b6eb.fc32.x86_64
osbuild-composer-debuginfo-13-1.20200529git375b6eb.fc32.x86_64
osbuild-composer-tests-debuginfo-13-1.20200529git375b6eb.fc32.x86_64
osbuild-composer-worker-13-1.20200529git375b6eb.fc32.x86_64
osbuild-composer-debugsource-13-1.20200529git375b6eb.fc32.x86_64
osbuild-15-2.fc32.noarch
osbuild-composer-rcm-13-1.20200529git375b6eb.fc32.x86_64
osbuild-composer-tests-13-1.20200529git375b6eb.fc32.x86_64
python3-osbuild-15-2.fc32.noarch
osbuild-composer-worker-debuginfo-13-1.20200529git375b6eb.fc32.x86_64
```

![Screenshot from 2020-05-29 13-34-16](https://user-images.githubusercontent.com/795070/83255655-20cfe400-a1b1-11ea-9a88-4936814fde38.png)

And:

```
$ sudo composer-cli compose info 7702f102-cf30-46d2-8e78-dcb0db8dd757 
7702f102-cf30-46d2-8e78-dcb0db8dd757 FAILED   IoT             0.0.0 fedora-iot-commit 2147483648
Packages:
Modules:
Dependencies:
$ sudo composer-cli compose log 7702f102-cf30-46d2-8e78-dcb0db8dd757 
The compose result is empty.
```

Neither the journal output of osbuild-composer or osbuild-composer-worker have any output since startup, or further details of the problem.

**Comment by gicmo** [comment]
This is probably due to the `osbuild-ostree` package not being installed.

**Comment by teg** [comment]
My bad for forgetting to add the dependency when I introduced the `fedora-iot-commit` image type.

**Comment by stefwalter** [comment]
@teg No worries, that's expected, everyone makes mistakes like that. I suspect the code review policy for this project needs to state that every change must come with an integration test. Otherwise it's too easy for any individual to forget this sorta thing.

**Comment by ondrejbudai** [comment]
I'm currently rolling out a patch to fix this downstream (Fedora31-33).

**Comment by teg** [comment]
> I suspect the code review policy for this project needs to state that every change must come with an integration test.

Yeah, that's (of course) our general policy. I was a bit too eager to get Fedora IoT out early to get the ball rolling. As we discussed in our meeting on Thursday, we are waiting on a user story to test against.

I'll try to better contain my eagerness in the future ;)
