### ISSUE TITLE
Basic cloud boot tests

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#69]
Similarly to the local boot test, make a simple tool in Golang that uses the AWS sdk to upload and boot our ami image and run the same tests against it.

**Comment by msehnout** [comment]
Any reason that Golang is specifically requested here? If the local boot tests are going to be part of `test/run` this could be as well.

**Comment by msehnout** [comment]
Update: write a tool in Golang to upload the image and use it from the Python framework. The Go code will be shared with our worker.
