### ISSUE TITLE
Uploading to AWS leaves upload task in WAITING state

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#702]
After starting a compose on Fedora 32 and requesting an upload to AWS, the state of the upload job is stuck in `WAITING`.

Job started with:
```
composer-cli compose start bash ami "majors image via composer-cli" aws.toml
```

Output of `composer-cli compose info`:

```json
{
    "id": "d2dad6f0-c97b-43f7-8428-ebc2cc643a81",
    "config": "",
    "blueprint": {
        "name": "bash",
        "description": "A base system with bash",
        "version": "0.0.1",
        "packages": [
            {
             	"name": "bash"
            }
	],
	"modules": [],
        "groups": [],
        "customizations": {
            "services": {
                "enabled": [
                    "sshd",
                    "cloud-init",
                    "cloud-init-local",
                    "cloud-config",
                    "cloud-final"
                ]
            }
	}
    },
    "commit": "",
    "deps": {
	"packages": []
    },
    "compose_type": "ami",
    "queue_status": "FINISHED",
    "image_size": 6442450944,
    "uploads": [
        {
            "uuid": "ae8519f3-490e-493c-9c3c-6b2a5afffd94",
            "status": "WAITING",
            "provider_name": "aws",
            "image_name": "majors image via composer-cli",
            "creation_time": 1591122803.673745,
            "settings": {
                "region": "us-east-2",
                "accessKeyID": "******",
                "secretAccessKey": "***",
                "bucket": "***",
                "key": "DOOT"
            }
	}
    ]
}

```

The snapshot imported just fine and I was able to build an instance from it. The instance fully booted. 🎉

However, even 30 minutes later, the status still shows as `WAITING`. The system journal has no log lines for it.

**Comment by teg** [comment]
`queue_status: FINISHED` should imply `upload`'s  `status: FINISHED`, so we are failing to update the enum. I assume. Should be a mostly harmless bug otherwise, but definitely something to fix.

**Comment by ondrejbudai** [comment]
It seems to me that it was broken by the `jobqueue` refactoring. `worker.Server.JobStatus()` is responsible for returning the status. However, it determines the status from the osbuild result json, which does not reflect the status of upload targets. Worker reports the status correctly but the new jobqueue implementation doesn't use and just relies on the osbuild result json. This is something @larskarlitski should be able to fix quickly. :)
