### ISSUE TITLE
Missing support for cloud provider profiles and image upload handling via CLI

### ISSUE THREAD

**Issue by jikortus** [osbuild/osbuild-composer#735]
To the best of my knowledge, the API still doesn't allow for handling cloud provider profiles, and also uploads of existing images, so it's not possible to use commands such as `composer-cli providers ...` or `composer-cli upload ...`.

If I remember correctly, last time I tried to investigate the state of this functionality and we had a discussion about that, the conclusion was that the this functionality is not implemented in osbuild-composer and probably doesn't have a high priority, but should not be very difficult to implement. I'm not sure if there was also a need to do some changes on the CLI tool part - if yes, I can create an issue also for weldr/lorax.

**Comment by teg** [comment]
@bcl is working on dropping this from `composer-cli` for RHEL8.3.
