### ISSUE TITLE
The exception handler in generate-test-case script results in subtle issues

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#769]
https://github.com/osbuild/osbuild-composer/blob/6bc200df149846e580ab12f9f723b30377740b5a/tools/test-case-generators/generate-test-case#L52

This exception handler is unfortunate because it does not end the process with status code different than 0 and it also prints the error to stdout which is captured and thrown away by `generate-test-cases` script.

This results in subtle bug, for example nbd fails with "no availble network devices" because it cannot open the image, which does not exist, but it keeps trying until it fails with completely unrelated error.

**Comment by ondrejbudai** [comment]
I think this was fixed by #770, can you close this issue, @msehnout ?
