### ISSUE TITLE
Compose fails if you specify timezone customization but forget chrony

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#787]
I was making an OpenStack image recently and I added a timezone customization to my blueprint like so:

```toml
[customizations.timezone]
timezome = "UTC"
ntpservers = ["clock.corp.redhat.com"]
```

The compose failed to build because chrony was not installed and the config file did not exist:

```
 Traceback (most recent call last):
   File "/run/osbuild/lib/stages/org.osbuild.chrony", line 53, in <module>
     r = main(args["tree"], args["options"])
   File "/run/osbuild/lib/stages/org.osbuild.chrony", line 32, in main
     with open(f"{tree}/etc/chrony.conf") as f:
 FileNotFoundError: [Errno 2] No such file or directory: '/run/osbuild/tree/etc/chrony.conf'
```

This could be by design since I should specify that I want chrony installed within my blueprint, but I figured it was worth a discussion. 🤔

**Comment by larskarlitski** [comment]
Nice catch!

There seems to be a TODO for it already :confused: : https://github.com/osbuild/osbuild-composer/blob/master/internal/distro/rhel8/distro.go#L269

**Comment by major** [comment]
![https://media.giphy.com/media/2d98nRiVVB6HS/giphy.gif](https://media.giphy.com/media/2d98nRiVVB6HS/giphy.gif)
