### ISSUE TITLE
First request for a compose fails if dnf-json cache is empty

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#790]
If I request a compose to start after installing osbuild-composer, the first run fails because `dnf-json` takes a very long time to run:

```
# composer-cli --json compose start bash ami major-errortest aws.toml 
2020-06-19 20:26:09,671: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
# composer-cli --json compose start bash ami major-errortest aws.toml 
{
    "build_id": "c0035904-3845-4eba-942f-187a59ab5348",
    "status": true
}
```

**Comment by teg** [comment]
This is "just" composer-cli timing out. The compose should have been started correctly. I believe @bcl fixed this upstream.

**Comment by ondrejbudai** [comment]
Fixed in https://github.com/weldr/lorax/pull/1037 and https://github.com/weldr/lorax/pull/1038
