### ISSUE TITLE
Missing support for Fedora Rawhide

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#803]
When a user tries to start `osbuild-composer.service` on Rawhide (currently 33), composer crashes immediately with the following message:

```
Could not determine distro from host: unknown distro: fedora-33
```

The cause for this crash is that composer simply doesn't support rawhide yet.

Adding support for fedora 33 is rather easy from the code perspective. However, having it covered with tests is non-trivial and we don't like code without test coverage. Rawhide moves very quickly and the chance that something breaks is quite high from our perspective. I discussed this issue with @teg and we decided that the best solution is to create a snapshot of the rawhide repositories and test composer against this fixed version of rawhide. This snapshot would be updated regularly. The proposed solution requires some work on our infrastructure though. The team is aware that users want to use composer on rawhide and consider this issue's priority quite high.

Originally reported as rhbz#1848477

**Comment by msehnout** [comment]
This has been "fixed" by introducing distro name aliases. We still need to create a new one for each Fedora release but it is not a huge issue like it used to be.
