### ISSUE TITLE
distros: don't exclude packages that should be possible to install manually

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#806]
Most of our image types install `@core` and some additional set of packages. Some image types on some distros aditionally exclude certain packages that are not strictly speaking necessary to exclude (presumably to save space). It is not possible to both include and exclude a package, so overriding this is not possible.

For instance, including `firewalld` in a blueprint for `qcow2` in `fedora-32` is not possible.

This should be possible to work around by dropping `@core` + excludes in favor of an explicit list of included packages, without any groups.

**Comment by msehnout** [comment]
Isn't this a problem with the definition of the `@core` group? I mean, if a group of packages defines "Core" of Fedora, we shouldn't exclude anything from it.

**Comment by teg** [comment]
> Isn't this a problem with the definition of the `@core` group? I mean, if a group of packages defines "Core" of Fedora, we shouldn't exclude anything from it.

Yeah, to I agree. We had to do it like this for backwards compatibility. And `@core` isn't as minimal as the name leads one to assume.

**Comment by thozza** [comment]
I think this is not an issue any more with chain depsolving, right @teg? In that case we can close this issue...

**Comment by teg** [comment]
Indeed! Thanks for cleaning this up!
