### ISSUE TITLE
useradd step fails on Fedora 31

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#816]
```
useradd: cannot create directory /home/redhat
Traceback (most recent call last):
File \"/run/osbuild/lib/stages/org.osbuild.users\", line 168, in <module>
    r = main(args[\"tree\"], args[\"options\"])
  File \"/run/osbuild/lib/stages/org.osbuild.users\", line 157, in main
    useradd(tree, name, uid, gid, groups, description, home, shell, password)
  File \"/run/osbuild/lib/stages/org.osbuild.users\", line 100, in useradd
    subprocess.run([\"chroot\", root, \"useradd\", *arguments, name], check=True)
  File \"/usr/lib64/python3.7/subprocess.py\", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['chroot', '/run/osbuild/tree', 'useradd', 'redhat']' returned non-zero exit status 12.
```

Pipeline: https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/master/148/pipeline

Full osbuild log: https://osbuildci.cloud.paas.psi.redhat.com/job/osbuild/job/osbuild-composer/job/master/148/artifact/fedora31-image/fedora_31-x86_64-vhd-boot.json.log

**Comment by major** [comment]
I can't reproduce this when run manually on a Fedora 31 VM. 🤦🏻‍♂️

**Comment by major** [comment]
Hmm, I shuffled the test order in https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild/detail/PR-467/1/pipeline/111/ and then the openstack image failed instead.

**Comment by major** [comment]
This seems to be happening less often lately, although I can't explain why.

**Comment by ondrejbudai** [comment]
Happens also on `aarch64`:

https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-858/4/pipeline/454

**Comment by ondrejbudai** [comment]
Fedora 31 is EOL
