### ISSUE TITLE
Get rid of Travis

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#855]
The https://github.com/osbuild/osbuild-composer/pull/799 PR is currently blocked on the fact that image build with SELinux stage does not work on Ubuntu. As far as I know, the only remaining test not present in Jenkins is upload to Azure (@ondrejbudai please correct me if I am wrong). If we can get this test to work in Jenkins, we can stop using Travis.

**Comment by ondrejbudai** [comment]
It's the highest item on my todolist!

**Comment by msehnout** [comment]
Fixed in #867
