### ISSUE TITLE
Relabel `cp` in buildroot for Fedora 31 and RHEL 8

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#878]
By labeling `cp` with `system_u:object_r:install_exec_t:s0` we allow it to copy labels unknown to the host. PR #799 introduces this for Fedora 32, but we should do the same for Fedora 31 and RHEL 8 as soon as the PR gets merged.

This work requires changing the build pipeline generation to something like this:
```go

	selinuxOptions := osbuild.SELinuxStageOptions{
		FileContexts: "etc/selinux/targeted/contexts/files/file_contexts",
		Labels: map[string]string{
			"/usr/bin/cp": "system_u:object_r:install_exec_t:s0",
		},
	}
```
and regenerating all relevant test cases.

**Comment by larskarlitski** [comment]
This might not work on Fedora 31 (which is nearing end of life anyway) and RHEL 8, because of [bug 1777831](https://bugzilla.redhat.com/show_bug.cgi?id=1777831).

**Comment by msehnout** [comment]
Fedora 31 is EOL and RHEL 8 seems to work. Closing this.
