### ISSUE TITLE
Ship all the integration/image tests in -tests RPM subpackage

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#879]
We would like the CI system to be as indepentent as possible on the internal structure of osbuild-composer. In order to achieve this, we should ship all the tests, that we run as part of CI, in the `-tests` subpackage. This is currently not the case for these two scripts:
https://github.com/osbuild/osbuild-composer/blob/master/test/image-tests/qemu.sh
https://github.com/osbuild/osbuild-composer/blob/master/test/image-tests/aws.sh

It would also be nice to move out this logic:
https://github.com/osbuild/osbuild-composer/blob/master/schutzbot/Jenkinsfile#L361
to the RPM subpackage so that `Jenkinsfile` only contains calls to whatever we ship in the RPM.

Finally, do we want to keep these tests in bash? All the other tests are written in golang so it might make sense to have these in golang as well. Any thoughts @major , @ondrejbudai (IIRC you were the one to rewrite python tests to golang)?

**Comment by major** [comment]
So the goal with keeping them in bash originally is that I wanted to keep the tests as close to the commands that a customer would run. The "integration" (terrible name) tests are really just a customer process walkthrough to ensure that things work there, too.

**Comment by teg** [comment]
I think we should allow the tests to be written in any language, including bash. We should unify how the tests are called and fix some API (probably just environment variables?) to describe the environment the test is run in, but apart from that, I think we should not place any restrictions on how the tests are written.

**Comment by atodorov** [comment]
I believe this was fixed in https://github.com/osbuild/osbuild-composer/pull/1016. @msehnout, @major, @teg is there anything else left here ?

**Comment by msehnout** [comment]
I believe we can close this issue now. We are now working on the `rpmci` tool which will replace parts of the logic currently found in the Jenkinsfile.
