### ISSUE TITLE
parity with lorax-composer on depsolve

### ISSUE THREAD

**Issue by jgiardino** [osbuild/osbuild-composer#890]
When using lorax-composer, if I run `sudo curl --unix-socket /run/weldr/api.socket "http://localhost/api/v0/blueprints/depsolve/node"`, I get the following result:
`{"blueprints":[{"blueprint":{"description":"","groups":[],"modules":[],"name":"node","packages":[{"name":"node","version":"0.2.*"}],"version":"0.0.3"},"dependencies":[],"modules":[]}],"errors":[{"id":"BlueprintsError","msg":"node: The following package(s) had problems: node-0.2.* (No match)"}]}`

If I run the same command when using osbuild-composer, I get the following result:
`{"status":false,"errors":[{"id":"BlueprintsError","msg":"node: DNF error occured: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\nmissing packages: node-0.2.*"}]}`

When using lorax-composer, the following is what the user sees when trying to edit this blueprint:
<img width="945" alt="Screen Shot 2020-07-27 at 10 29 31 AM" src="https://user-images.githubusercontent.com/21063328/88561359-4df81180-cffd-11ea-8e77-349f610aedf6.png">

But because we get different results from osbuild-composer, the following is what's currently returned: 
<img width="945" alt="Screen Shot 2020-07-27 at 10 53 09 AM" src="https://user-images.githubusercontent.com/21063328/88561447-6c5e0d00-cffd-11ea-8d24-0c37d11ba7a4.png">

I'm not really sure where this issue belongs, between here and cockpit-composer. Chatting with @jkozol, it's possible to support both sets of results in cockpit-composer and provide a similar experience to the user. But for now I'm posting this here to get thoughts from the team on how to proceed with this one.

**Comment by teg** [comment]
Thanks for the detailed bug report @jgiardino! Which distro is this on?

**Comment by jgiardino** [comment]
> Which distro is this on?

osbuild-composer 17, on Fedora 32
