### ISSUE TITLE
AWS credentials for previous builds available via API

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#907]
After starting a compose with AWS upload enabled, the AWS credentials are available to anyone via the API:

```
# composer-cli --json compose info 3ada5fd7-7eee-4623-bee3-cb462493a6d2
{
    -- SNIP --
    "uploads": [
        {
            "uuid": "68f2d2e6-81ba-4fe7-a39a-a7d8047a9e9f",
            "status": "RUNNING",
            "provider_name": "aws",
            "image_name": "major-aws-test",
            "creation_time": 1596460680.0325832,
            "settings": {
                "region": "us-east-2",
                "accessKeyID": "SUPERSECRETACCESSKEY😱",
                "secretAccessKey": "SUPERSECRETACCESSKEY😱",
                "bucket": "...",
                "key": ""
            }
        }
    ]
}
```

Should we make these available via the API or hide them in some way?

**Comment by teg** [comment]
@bcl, @ondrejbudai  are there any lorax compatibility concerns here? I would not be opposed to restricting the output we give.

@jkozol, @jgiardino what of this information is used in the frontend and what could we drop?

One could also argue that as the weldr API does not have any notion of user management, all the information should be expecetd to be shared. I would prefer not to spurprise anyone by leaking something they thought was private though....

**Comment by jgiardino** [comment]
> @jkozol, @jgiardino what of this information is used in the frontend and what could we drop?

In the create image flow, these values are obscured via `type="password"` in the text input, and we don't show them in the list of images that were created.
```
"accessKeyID": "...",
"secretAccessKey": "...",
```

The following values are entered in regular text input fields in the create image flow. We currently only display "image_name" in the list of images, but I think it would be helpful to provide region and bucket as well. For example, in the scenario where the user is making the same image available across multiple regions, seeing which ones succeeded and which ones failed is ideal. 
```
"image_name": "major-aws-test",
// snip
"region": "us-east-2",
"bucket": "...",
```

**Comment by bcl** [comment]
composer-cli doesn't care about those fields at all so changes there shouldn't be a problem.
