### ISSUE TITLE
ci: exceeding openstack quota

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#914]
Now that our image tests spawn openstack instances we risk exceeding our quota, leading to test failure.

A simple solution to this would be to limit the number of parallel tests we run to account for how many openstack instances each test may need.

**Comment by major** [comment]
Can we do this in AWS instead?

**Comment by teg** [comment]
> Can we do this in AWS instead?

The tests are testing the openstack images, so need access to an openstack instance. Can we do that outside the VPN?

**Comment by atodorov** [comment]
> Now that our image tests spawn openstack instances we risk exceeding our quota, leading to test failure.

What's the reason for this ? From what I can tell VMs aren't removed properly b/c we hardly have 40 parallel tests running at the same time. FTR we have discussed this in the past at https://github.com/weldr/lorax/pull/842.

**Comment by teg** [comment]
> we hardly have 40 parallel tests running at the same time.

We run many tests in parallel, so one test run spins up around 15 of them, I believe, maybe more.

**Comment by ondrejbudai** [comment]
I think balancing our usage of PSI OpenStack is going to be an endless pain until we fully switch to AWS. Currently, we are fine, builds are not failing because of the quota. Closing it for now, feel free to reopen if builds start to fail again.
