### ISSUE TITLE
Weldr API needs an option to skip upload from worker to composer

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#920]
When I request an image to be built with an upload to AWS, the image is still uploaded from the worker to composer. This causes disk space to run out quickly as we offer composer as a service.

It would be great to have an option where I could say:

* Build this image
* Upload it to AWS
* Don't store it on composer

**Comment by bcl** [comment]
Seems like that should be the default when uploading. If you're uploading it someplace else I'd bet that almost nobody will care if composer has a copy of it so I'd do the opposite and add a switch for keeping it which defaults to false for uploaded images.

**Comment by major** [comment]
@bcl I feel the same way as you.

This one is a blocker for getting the deployment done in AWS.

**Comment by teg** [comment]
For now, could you clean up each compose from your test script? This problem goes away with the cloud API, which will be ready real soon now

**Comment by major** [comment]
That's what I am doing now (manual cleanups).

**Comment by ondrejbudai** [comment]
For this use-case, it's better to use the new Composer API.
