### ISSUE TITLE
worker: remove hack that returns vmdk's as streamoptimized

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#938]
Due to time constraints, we introduced a hack which converts vmdk images to streamoptimized with https://github.com/osbuild/osbuild-composer/pull/934.

osbuild should be able to set this option in the `qemu` assembler, which is more efficient and the correct place to do such things. Once it does, remove this hack.

**Comment by ondrejbudai** [comment]
Hehe, we did this probably years ago. :)
