### ISSUE TITLE
dnf-json not in PATH of the sytemd unit

### ISSUE THREAD

**Issue by gicmo** [osbuild/osbuild-composer#95]
@jkozol discovered that after d05673afb1162f3a4443a193b6c15aba49f23c7b the systemd unit would not start anymore:
```
Nov 12 19:29:18 hanada.local osbuild-composer[75894]: panic: exec: "dnf-json": executable file not found in $PATH
Nov 12 19:29:18 hanada.local osbuild-composer[75894]: goroutine 1 [running]:
Nov 12 19:29:18 hanada.local osbuild-composer[75894]: main.main
Nov 12 19:29:18 hanada.local osbuild-composer[75894]:         /home/gicmo/Code/src/osbuild-composer/cmd/osbuild-composer/main.go:43
Nov 12 19:29:18 hanada.local systemd[1]: osbuild-composer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

We had a look and go uses [`LookPath(name)`](https://github.com/golang/go/blob/1fe33e3cb20295b5120f82b02b0a9ab4ad303cc0/src/os/exec/exec.go#L174) to find the executable, but it only [looks](https://github.com/golang/go/blob/1fe33e3cb20295b5120f82b02b0a9ab4ad303cc0/src/os/exec/lp_unix.go#L34) in `PATH` and not in the current working directory. Since `dnf-json` is not in `PATH` but in `/usr/libexec/osbuild-composer` and the env for the systemd unit does not include the latter directory it wont indeed find `dnf-json` (cf. `cmd: &{Path:dnf-json Args:[dnf-json] Env:[] Dir: ...  lookPathErr:0xc0000107a0 ...}`).

`env` of the systemd unit:
```
Nov 12 19:32:05 hanada.local env[76758]: LANG=en_GB.UTF-8
Nov 12 19:32:05 hanada.local env[76758]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Nov 12 19:32:05 hanada.local env[76758]: LISTEN_PID=76758
Nov 12 19:32:05 hanada.local env[76758]: LISTEN_FDS=2
Nov 12 19:32:05 hanada.local env[76758]: LISTEN_FDNAMES=osbuild-composer.socket:osbuild-composer.socket
Nov 12 19:32:05 hanada.local env[76758]: LOGNAME=_osbuild-composer
Nov 12 19:32:05 hanada.local env[76758]: USER=_osbuild-composer
Nov 12 19:32:05 hanada.local env[76758]: INVOCATION_ID=76348a3dd8a946308ee04f56bf21e215
Nov 12 19:32:05 hanada.local env[76758]: JOURNAL_STREAM=9:1066442
Nov 12 19:32:05 hanada.local env[76758]: STATE_DIRECTORY=/var/lib/osbuild-composer
```
Easiest fix would be to add `Environment="PATH=$PATH:/usr/libexec/osbuild-composer` to the systemd unit file.
(That or @jkozol and I missing something obvious)

**Comment by larskarlitski** [comment]
Ah, we need integration tests and I need to think more before doing stuff. Very sorry (again this week!) about messing this up.

I only needed that commit for testing rpmmd (#83), but we've postponed that. I've reverted the commit in #96. No need to find a good solution for this right now.

Thanks!
