### ISSUE TITLE
url should be part of every source

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#951]
Unless I'm missing something, the source specification is useless without URL. I suggest to add "url" to this check:
https://github.com/osbuild/osbuild-composer/blob/05fd221bd4763040afd9a17b8c6567dc9ef97409/internal/weldr/api.go#L596

Related: https://github.com/weldr/lorax/issues/1066

**Comment by teg** [comment]
This sounds reasonable. How would this affect lorax compatibility?

**Comment by bcl** [comment]
It shouldn't have any effect. url is assumed to be present. it's useless without it.
