### ISSUE TITLE
failing vmdk image tests

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#953]
VMDK image tests have recently started to fail with

```
/usr/libexec/tests/osbuild-composer/osbuild-image-tests: default resource pool resolves to multiple instances, please specify
```

See https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/master/225/pipeline

@atodorov any ideas?

**Comment by atodorov** [comment]
Opened https://github.com/vmware/govmomi/issues/2097 with upstream b/c ATM I have no idea how to resolve this other than deleting/black-listing the rest of the clusters in the datacenter.
