### ISSUE TITLE
tests: Start splitting image info from upload & boot tests

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#962]
See discussion here
https://github.com/osbuild/osbuild-composer/pull/949#pullrequestreview-476585040

and also here:
https://github.com/osbuild/osbuild-composer/issues/888#issuecomment-662933161

* The image info portion should be moved to osbuild
* The upload to cloud & boot portion in golang is also duplicated to some extent by `test/image-tests/*.sh` (these are not in the -tests RPM I think)
* The upload & boot tests should be adjusted appropriately so that the images are actually built from the currently configured sources in osbuild-composer (e.g. nightly builds)

**Comment by msehnout** [comment]
> 
>     * The upload to cloud & boot portion in golang is also duplicated to some extent by `test/image-tests/*.sh` (these are not in the -tests RPM I think)
> 

We would like to move the `test/image-tests/*.sh` scripts to the -tests RPM but noone has done it yet.

As for the golang implementation of cloud boot, if #956 and #960 get merged we will also use the code for running the "base" tests (https://github.com/osbuild/osbuild-composer/blob/master/schutzbot/run_base_tests.sh).

**Comment by teg** [comment]
> > ```
> > * The upload to cloud & boot portion in golang is also duplicated to some extent by `test/image-tests/*.sh` (these are not in the -tests RPM I think)
> > ```
> 
> We would like to move the `test/image-tests/*.sh` scripts to the -tests RPM but noone has done it yet.
> 
> As for the golang implementation of cloud boot, if #956 and #960 get merged we will also use the code for running the "base" tests (https://github.com/osbuild/osbuild-composer/blob/master/schutzbot/run_base_tests.sh).

Much of this was now done/changed, but moving out image-info itself is still on the TODO.

**Comment by thozza** [comment]
Also note that the `test/cases/api.sh` now also boots images. At least AWS and GCP one...
