### ISSUE TITLE
AWS: Share AMI/snapshot with customer's AWS account

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#973]
## Why?

If we share the snapshot/AMI with the customer account, we don't need to get sensitive credentials from the customer or ask the customer to do work inside AWS IAM (which is error prone).

## What?

The process looks like this:

1. Get the customer's numeric AWS account ID.
2. Upload the image to S3 in a centralized account, import the snapshot, and register the AMI.
3. Add the [Launch Permission](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html) to the registered AMI so the customer can launch new instances with it.
4. [Modify the EC2 snapshot](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-modifying-snapshot-permissions.html) to share it with the customer account so the customer can copy it to their account and any other region(s) where they need it.

💸 **This will cause our AWS expenses to increase.** This is because we have the EC2 snapshots inside the Image Builder account and not in the customer's account.

## AWS Go SDK documentation

* [ModifyImageAttribute](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.ModifyImageAttribute)
* [ModifySnapshotAttribute](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.ModifySnapshotAttribute)

**Comment by ondrejbudai** [comment]
Done by #1098
