### ISSUE TITLE
Make composer easier to run in a container

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#983]
Running osbuild-composer in a container (especially on OpenShift) has some benefits:

- OpenShift can verify that composer started properly and re-verify that it is working properly on an interval
- We can ensure that the OS + dependencies + composer are identical each time and we can test them together
- Once there's a shared database, we can easily scale composer up/down based on our needs

However, composer's startup is heavily tied to systemd's socket activation. That is not available in containers on OpenShift and we need a way to start the daemon and have it listen on a port.

**Comment by teg** [comment]
Absolutely. We should figure out exactly what this would take and how to test it. Happy to discuss that. Not sure we'll have the resources to schedule this work in the immediate future, but definitely high on the list.

**Comment by dvdhrm** [comment]
This is "easy" to do with `ubi-init`, *IF* you run it on modern podman, that is >=OpenShift-4.

**Comment by teg** [comment]
@major did we conclude that OpenShift-4 is not an option? so we have to run this in a `ubi` container?

**Comment by major** [comment]
From what I understand, you still need to run privileged containers (which isn't possible). I also hunted around and can't find anyone using ubi-init on OpenShift 4 on clouddot right now.

**Comment by ondrejbudai** [comment]
Fixed in  #1097

**Comment by ondrejbudai** [comment]
Ah, it isn't merged yet, reopening this.

**Comment by dvdhrm** [comment]
There is now a base container in the repository, filed as `./containers/osbuild-composer/`. While there might be adjustments necessary, this does allow running composer in a container with its full feature set.

Closing this now. For more specific requests, we can start opening new issues.
