### ISSUE TITLE
OpenStack boot test is flaky

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#987]
The OpenStack boot test is flaky and doesn't output enough information to investigate the issue. For example:

```
=== RUN   TestImages
=== RUN   TestImages/fedora_32-x86_64-openstack-boot.json
=== RUN   TestImages/fedora_32-x86_64-openstack-boot.json/image_info
=== RUN   TestImages/fedora_32-x86_64-openstack-boot.json/boot
    main_test.go:192: ssh test failure, 20 attempts were made
--- FAIL: TestImages (516.02s)
    --- FAIL: TestImages/fedora_32-x86_64-openstack-boot.json (515.95s)
        --- PASS: TestImages/fedora_32-x86_64-openstack-boot.json/image_info (25.59s)
        --- FAIL: TestImages/fedora_32-x86_64-openstack-boot.json/boot (266.80s)
FAIL
```

**Comment by larskarlitski** [comment]
@atodorov do you mind taking a look at this one?

**Comment by atodorov** [comment]
FTR none of the boot tests provides any information in case ssh attempts fail so it could be a multitude of issues here.

**Comment by atodorov** [comment]
> @atodorov do you mind taking a look at this one?

Do you mind providing some more info:
- Which PR/branch it failed
- which jobs
- How often/since when did you start seeing this issue
- Which commit/osbuild-composer version is being tested

**Comment by larskarlitski** [comment]
> Do you mind providing some more info:

Sorry for not answering earlier. I did see this a couple of times, but it seems to have been temporary. I'm closing this issue, as I haven't seen this in any of the recent PRs.
