### ISSUE TITLE
kojiapi: logs for a compose

### ISSUE THREAD

**Issue by gicmo** [osbuild/osbuild-composer#993]
Currently there is no way to get the logs for a compose. As long as we can't stream logs, the easiest would probably to just have a `compose/id/logs` with a json object containing the overall log and the logs for the individual images. 
Or we could pretend to support streaming of Logs already, and combine that API with the wait-for-compose to finish API and stream json-line/json-records that could contain log updates.

**Comment by teg** [comment]
The first solution sounds the simpler with what we currently have, and I also think the most relevant. Streaming logs for this isn't all that important, is it? I would be happy to add that too once we have the infrastructure though.
For now, let's add `compose/id/logs` as you proposed, which I think would be good to have even if we one day get streaming logs, no?

**Comment by gicmo** [comment]
Yes, totally agree, sounds all good to me!
