### ISSUE TITLE
kojiapi: ablity to get the manifests for a compose job

### ISSUE THREAD

**Issue by gicmo** [osbuild/osbuild-composer#996]
If a compose fails, It probably would be handy to get the complete manifests for all the image builds and attach that as a log to the (failed) koji task. Could be combined with the full log API or a separate call.

**Comment by teg** [comment]
I think we should expose the manifest as a separate endpoint/object. The logs could be the raw ones for humans to read, and the manifest should be something one could download and pass directly to osbuild. Also, we would have the manifest as soon as the job had been scheduled, but the logs only when it had finished (or failed).

**Comment by ondrejbudai** [comment]
This was done by #1053.

**Comment by ondrejbudai** [comment]
Hmm, we don't guarantee the format of the logs route and the logs won't probably contain the manifest in the future. Let's reopen this issue as we still need to have a nice way to extract the manifest from composer.
